unpackaged/main/default/objects/Add_On_Lead_Opp_Cleanup__e/Add_On_Lead_Opp_Cleanup__e.object-meta.xml
<CustomObject>
    <description>This Event is used to facilitate the deletion of Opportunities with the Record Type of &quot;Lead&quot; and the Deal Type of &quot;Add-On&quot; after an Opportunity with the Record Type of &quot;Add-On&quot; is created.  This allows the system to delete the records after a user without the explicit permission to delete has created the new Add-On Opp.</description>
    <label>Add On Lead Opp Cleanup</label>
    <pluralLabel>Add On Lead Opp Cleanup</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Opportunity/fields/Meeting_Occurred_Stage_Set_Date__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Occurred_Stage_Set_Date__c</fullName>
    <label>Meeting Occurred Stage Set Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Meeting_Pending_Stage_Set_Date__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Pending_Stage_Set_Date__c</fullName>
    <label>Meeting Pending Stage Set Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Meeting_Scheduled_Stage_Set_Date__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Scheduled_Stage_Set_Date__c</fullName>
    <label>Meeting Scheduled Stage Set Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Named_Account__c.field-meta.xml
<CustomField>
    <fullName>Named_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Named Account</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Named_Account_Tier__c.field-meta.xml
<CustomField>
    <fullName>Named_Account_Tier__c</fullName>
    <label>Named Account Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
            <value>
                <fullName>Tier 3</fullName>
            </value>
            <value>
                <fullName>Tier 4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6QA__c.field-meta.xml
<CustomField>
    <fullName>X6QA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>6QA</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <businessProcess>Lead</businessProcess>
    <label>Lead</label>
</RecordType>

unpackaged/main/default/classes/AddOnRelatedStageZeroHandler.cls
/**
 * This class is responsible for facilitating the syncing of data between existing
 * Opportunities with the "Lead" Record Type with newly created Opportunities with
 * the "Add-On" Record Type. After syncing, the Lead Opportunities are deleted.
 *
 * This is required as the existing "Convert" process for New Business Opportunities
 * is not possible for Add-Ons due to the requirement that they must originate from
 * Contracts that are amended.
 */
public with sharing class AddOnRelatedStageZeroHandler extends DomainLogicHandler {
    BCMap qualifiedOppsByAccountId = new BCMap('AccountId');

    public override void check(SObject newObj) {
        if (isQualified(newObj)) {
            qualifiedOppsByAccountId.put(newObj);
        }
    }

    public override void processRecords() {
        if (!qualifiedOppsByAccountId.isAllEmpty()) {
            BCMap existingLeadOpps = new BCMap(
                [
                    SELECT
                        Id,
                        AccountId,
                        Meeting_Occurred_Stage_Set_Date__c,
                        Meeting_Pending_Stage_Set_Date__c,
                        Meeting_Scheduled_Stage_Set_Date__c,
                        X6QA__c,
                        Named_Account__c,
                        Named_Account_Tier__c
                    FROM Opportunity
                    WHERE
                        IsClosed = FALSE
                        AND RecordType.Name = 'Lead'
                        AND AccountId IN :qualifiedOppsByAccountId.keyAllSet()
                ],
                'AccountId'
            );
            List<Add_On_Lead_Opp_Cleanup__e> events = new List<Add_On_Lead_Opp_Cleanup__e>();
            for (Id accountId : existingLeadOpps.keySet()) {
                for (
                    SObject addOnOpp : qualifiedOppsByAccountId.getAll(
                        accountId
                    )
                ) {
                    events.add(
                        new Add_On_Lead_Opp_Cleanup__e(
                            Opportunity_Id__c = existingLeadOpps.get(accountId)
                                .Id
                        )
                    );
                    setFields(addOnOpp, existingLeadOpps.get(accountId));
                }
            }

            EventBus.publish(events);
        }
    }

    Boolean isQualified(SObject newObj) {
        return RecordTypeUtility.getName(newObj) == 'Add-On';
    }

    void setFields(SObject addOnOpp, SObject leadOpp) {
        List<SObjectField> fields = new List<SObjectField>{
            Opportunity.Meeting_Occurred_Stage_Set_Date__c,
            Opportunity.Meeting_Pending_Stage_Set_Date__c,
            Opportunity.Meeting_Scheduled_Stage_Set_Date__c,
            Opportunity.X6QA__c
        };

        for (SObjectField field : fields) {
            addOnOpp.put(field, leadOpp.get(field));
        }

        addOnOpp.put(Opportunity.LeadSource, 'QA');
    }
}