unpackaged/main/default/objects/Campaign/fields/Campaign_Offer_Type__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Offer_Type__c</fullName>
    <label>Campaign Offer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ABM</fullName>
                <isActive>false</isActive>
                <label>ABM</label>
            </value>
            <value>
                <fullName>Analyst Report</fullName>
            </value>
            <value>
                <fullName>Blog</fullName>
            </value>
            <value>
                <fullName>Case Study</fullName>
            </value>
            <value>
                <fullName>Communication Opt-In</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
                <isActive>false</isActive>
                <label>Content</label>
            </value>
            <value>
                <fullName>Content Bundle</fullName>
            </value>
            <value>
                <fullName>Data Sheet</fullName>
            </value>
            <value>
                <fullName>Demo</fullName>
            </value>
            <value>
                <fullName>Direct Mail</fullName>
                <isActive>false</isActive>
                <label>Direct Mail</label>
            </value>
            <value>
                <fullName>Direct Response (Conversation)</fullName>
            </value>
            <value>
                <fullName>eBook</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Event Inquiry</fullName>
            </value>
            <value>
                <fullName>Event - Webcast</fullName>
                <isActive>false</isActive>
                <label>Event - Webcast</label>
            </value>
            <value>
                <fullName>Follow / Like / Friend</fullName>
                <isActive>false</isActive>
                <label>Follow / Like / Friend</label>
            </value>
            <value>
                <fullName>Gift</fullName>
            </value>
            <value>
                <fullName>Guide</fullName>
            </value>
            <value>
                <fullName>Infographic</fullName>
            </value>
            <value>
                <fullName>Inquiry</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
                <isActive>false</isActive>
                <label>Not Applicable</label>
            </value>
            <value>
                <fullName>Online Office Hours</fullName>
                <isActive>false</isActive>
                <label>Online Office Hours</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>PLAY TV</fullName>
            </value>
            <value>
                <fullName>Product Beta Application</fullName>
            </value>
            <value>
                <fullName>Product Trial</fullName>
                <isActive>false</isActive>
                <label>Product Trial</label>
            </value>
            <value>
                <fullName>Promotional Offer</fullName>
                <isActive>false</isActive>
                <label>Promotional Offer</label>
            </value>
            <value>
                <fullName>Purchase Promotion</fullName>
                <isActive>false</isActive>
                <label>Purchase Promotion</label>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Sales Follow-up (Other)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CampaignMember/fields/Response_Date__c.field-meta.xml
<CustomField>
    <fullName>Response_Date__c</fullName>
    <label>Response Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Last_Live_Chat_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Live_Chat_Date__c</fullName>
    <label>Last Live Chat Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/LastLiveDateChatHandlerTest.cls
@IsTest(isparallel=true)
public with sharing class LastLiveDateChatHandlerTest {
  @TestSetup
  static void makeData() {
    LeadTestFactory.createLead();

    ContactTestFactory.createContact();

    Campaign parentCampaign = new Campaign(
      Name = 'Parent',
      Type = 'webinar',
      StartDate = Date.today(),
      EndDate = Date.today().addYears(1),
      Status = 'In Progress'
    );
    insert parentCampaign;

    insert new Campaign(
      Name = 'Conversations from Drift 2024',
      Type = 'webinar',
      StartDate = Date.today(),
      EndDate = Date.today().addYears(1),
      Status = 'In Progress',
      Campaign_Offer_Type__c = 'Direct Response (Conversation)',
      ParentId = parentCampaign.Id
    );
  }

  @IsTest
  static void testFromSetLastLiveChatDate() {
    Lead lead = [
      SELECT Id, Last_Live_Chat_Date__c
      FROM Lead
      WHERE Email = 'LeadTestFactory@example.com'
      LIMIT 1
    ];
    lead.Last_Live_Chat_Date__c = Datetime.now();

    Contact contact = [
      SELECT Id, Last_Live_Chat_Date__c
      FROM Contact
      WHERE LastName LIKE 'ContactTestFactory%'
      LIMIT 1
    ];
    contact.Last_Live_Chat_Date__c = Datetime.now().addDays(-1);

    Campaign campaign = [
      SELECT Id
      FROM Campaign
      WHERE
        Name LIKE 'Conversations from Drift%'
        AND Status = 'In Progress'
        AND Campaign_Offer_Type__c = :Label.Campaign_Offer_Type_Direct_Response
      ORDER BY CreatedDate DESC
      LIMIT 1
    ];

    insert new List<CampaignMember>{
      new CampaignMember(LeadId = lead.Id, CampaignId = campaign.Id),
      new CampaignMember(ContactId = contact.Id, CampaignId = campaign.Id)
    };

    Test.startTest();
    update lead;
    update contact;
    Test.stopTest();

    List<CampaignMember> members = [
      SELECT
        LeadId,
        Lead.Last_Live_Chat_Date__c,
        ContactId,
        Contact.Last_Live_Chat_Date__c,
        Response_Date__c
      FROM CampaignMember
      WHERE
        Campaign.Campaign_Offer_Type__c = :Label.Campaign_Offer_Type_Direct_Response
        AND Campaign.Status = 'In Progress'
        AND Campaign.ParentId != NULL
        AND Campaign.Name = 'Conversations from Drift 2024'
        AND (ContactId = :contact.Id
        OR LeadId = :lead.Id)
    ];

    System.assertEquals(
      2,
      members.size(),
      'Incorrect number of Campaign Member records.'
    );

    for (CampaignMember member : members) {
      Date expected = member.LeadId != null
        ? lead.Last_Live_Chat_Date__c.date()
        : contact.Last_Live_Chat_Date__c.date();
      System.assertEquals(
        expected,
        member.Response_Date__c,
        'Response_Date__c not set.'
      );
    }
  }

  @IsTest
  static void testNewCampaignMember() {
    Lead lead = [
      SELECT Id, Last_Live_Chat_Date__c
      FROM Lead
      WHERE Email = 'LeadTestFactory@example.com'
      LIMIT 1
    ];
    lead.Last_Live_Chat_Date__c = Date.today();
    update lead;

    Contact contact = [
      SELECT Id, Last_Live_Chat_Date__C
      FROM Contact
      WHERE LastName LIKE 'ContactTestFactory%'
      LIMIT 1
    ];
    contact.Last_Live_Chat_Date__c = Date.today().addDays(-1);
    update contact;

    Test.startTest();

    Campaign campaign = [
      SELECT Id
      FROM Campaign
      WHERE
        Status = 'In Progress'
        AND Campaign_Offer_Type__c = :Label.Campaign_Offer_Type_Direct_Response
        AND ParentId != NULL
        AND Name LIKE 'Conversations from Drift%'
      ORDER BY CreatedDate DESC
      LIMIT 1
    ];

    List<CampaignMember> members = new List<CampaignMember>{
      new CampaignMember(LeadId = lead.Id, CampaignId = campaign.Id),
      new CampaignMember(ContactId = contact.Id, CampaignId = campaign.Id)
    };
    insert members;

    Test.stopTest();

    members = [
      SELECT
        Id,
        LeadId,
        ContactId,
        Lead.Last_Live_Chat_Date__c,
        Contact.Last_Live_Chat_Date__c,
        Response_Date__c
      FROM CampaignMember
      WHERE Id IN :members
    ];
    for (CampaignMember member : members) {
      Date expected = member.LeadId != null
        ? member.Lead.Last_Live_Chat_Date__c.date()
        : member.Contact.Last_Live_Chat_Date__c.date();
      Date actual = member.Response_Date__c;

      System.assertEquals(expected, actual, 'Response Date not correctly set.');
    }
  }
}