unpackaged/main/default/objects/Campaign/fields/Campaign_Offer_Type__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Offer_Type__c</fullName>
    <label>Campaign Offer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ABM</fullName>
                <isActive>false</isActive>
                <label>ABM</label>
            </value>
            <value>
                <fullName>Analyst Report</fullName>
            </value>
            <value>
                <fullName>Blog</fullName>
            </value>
            <value>
                <fullName>Case Study</fullName>
            </value>
            <value>
                <fullName>Communication Opt-In</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
                <isActive>false</isActive>
                <label>Content</label>
            </value>
            <value>
                <fullName>Content Bundle</fullName>
            </value>
            <value>
                <fullName>Data Sheet</fullName>
            </value>
            <value>
                <fullName>Demo</fullName>
            </value>
            <value>
                <fullName>Direct Mail</fullName>
                <isActive>false</isActive>
                <label>Direct Mail</label>
            </value>
            <value>
                <fullName>Direct Response (Conversation)</fullName>
            </value>
            <value>
                <fullName>eBook</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Event Inquiry</fullName>
            </value>
            <value>
                <fullName>Event - Webcast</fullName>
                <isActive>false</isActive>
                <label>Event - Webcast</label>
            </value>
            <value>
                <fullName>Follow / Like / Friend</fullName>
                <isActive>false</isActive>
                <label>Follow / Like / Friend</label>
            </value>
            <value>
                <fullName>Gift</fullName>
            </value>
            <value>
                <fullName>Guide</fullName>
            </value>
            <value>
                <fullName>Infographic</fullName>
            </value>
            <value>
                <fullName>Inquiry</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
                <isActive>false</isActive>
                <label>Not Applicable</label>
            </value>
            <value>
                <fullName>Online Office Hours</fullName>
                <isActive>false</isActive>
                <label>Online Office Hours</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>PLAY TV</fullName>
            </value>
            <value>
                <fullName>Product Beta Application</fullName>
            </value>
            <value>
                <fullName>Product Trial</fullName>
                <isActive>false</isActive>
                <label>Product Trial</label>
            </value>
            <value>
                <fullName>Promotional Offer</fullName>
                <isActive>false</isActive>
                <label>Promotional Offer</label>
            </value>
            <value>
                <fullName>Purchase Promotion</fullName>
                <isActive>false</isActive>
                <label>Purchase Promotion</label>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Sales Follow-up (Other)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CampaignMember/fields/Response_Date__c.field-meta.xml
<CustomField>
    <fullName>Response_Date__c</fullName>
    <label>Response Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Last_Live_Chat_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Live_Chat_Date__c</fullName>
    <label>Last Live Chat Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/DirectResponseHandler.cls
/**
 * Triggers on BEFORE_INSERT of CampaignMember
 * Stamps the value of the CampaignMember's Response_Date__c field
 * with the value of the Last_Live_Chat_Date__c field of related
 * Contacts or Leads on related CampaignMembers.
 *
 * Test coverage is found in LastLiveDateChatHandlerTest.
 */
public with sharing class DirectResponseHandler extends DomainLogicHandler {
    List<Id> leadIds = new List<Id>();
    List<Id> contactIds = new List<Id>();
    List<Id> campaignIds = new List<Id>();
    Map<Id, SObject> relatedRecords = new Map<Id, SObject>();
    List<CampaignMember> newMembers = new List<CampaignMember>();

    public override void check(SObject newObj) {
        addToRelatedIds((CampaignMember) newObj);
        newMembers.add((CampaignMember) newObj);
    }

    public override void processRecords() {
        setRelatedMaps();
        Set<Id> qualifiedCampaignIds = getQualifiedCampaignIds();
        for (CampaignMember member : newMembers) {
            if (qualifiedCampaignIds.contains(member.CampaignId)) {
                Id relatedId = member.LeadId != null
                    ? member.LeadId
                    : member.ContactId;
                member.Response_Date__c = ((Datetime) relatedRecords.get(
                            relatedId
                        )
                        ?.get('Last_Live_Chat_Date__c'))
                    ?.date();
            }
        }
    }

    Set<Id> getQualifiedCampaignIds() {
        return new Map<Id, Campaign>(
                [
                    SELECT Id, Status, Campaign_Offer_Type__c, ParentId
                    FROM Campaign
                    WHERE
                        Campaign_Offer_Type__c = :Label.Campaign_Offer_Type_Direct_Response
                        AND Name LIKE 'Conversations from Drift%'
                        AND ParentId != NULL
                        AND Status = 'In Progress'
                        AND Id IN :campaignIds
                    ORDER BY CreatedDate DESC
                    LIMIT 1
                ]
            )
            .keySet();
    }

    void addToRelatedIds(CampaignMember newMember) {
        if (newMember.ContactId != null) {
            contactIds.add(newMember.ContactId);
        }

        if (newMember.LeadId != null) {
            leadIds.add(newMember.LeadId);
        }
        campaignIds.add(newMember.CampaignId);
    }

    void setRelatedMaps() {
        if (!contactIds.isEmpty()) {
            relatedRecords.putAll(
                [
                    SELECT Id, Last_Live_Chat_Date__c
                    FROM Contact
                    WHERE Id IN :contactIds AND Last_Live_Chat_Date__c != NULL
                ]
            );
        }

        if (!leadIds.isEmpty()) {
            relatedRecords.putAll(
                [
                    SELECT ID, Last_Live_Chat_Date__c
                    FROM Lead
                    WHERE Id IN :leadIds AND Last_Live_Chat_Date__c != NULL
                ]
            );
        }
    }
}