unpackaged/main/default/objects/API_Mapping__mdt/API_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Defines how the values in a request payload to the DataService API are mapped to SObjects and their fields.</description>
    <label>API Mapping</label>
    <pluralLabel>API Mappings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/API_Mapping__mdt/fields/Data_Servicer__c.field-meta.xml
<CustomField>
    <fullName>Data_Servicer__c</fullName>
    <label>Data Servicer</label>
    <referenceTo>Data_Servicer__mdt</referenceTo>
    <relationshipLabel>API Mappings</relationshipLabel>
    <relationshipName>API_Mappings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

unpackaged/main/default/objects/API_Mapping__mdt/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <label>Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DATE</fullName>
            </value>
            <value>
                <fullName>DATETIME</fullName>
            </value>
            <value>
                <fullName>REFERENCE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/API_Mapping__mdt/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <label>SObject</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brightcove_Account__c</fullName>
                <default>true</default>
                <label>Brightcove_Account__c</label>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/API_Mapping__mdt/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <label>Target</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Data_Servicer__mdt/Data_Servicer__mdt.object-meta.xml
<CustomObject>
    <description>Defines valid requests to the DataService API. These records are related to API_Mapping__mdt records so that data is correctly mapped based on the request type.</description>
    <label>Data Servicer</label>
    <pluralLabel>Data Servicers</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Data_Servicer__mdt/fields/Id_Field__c.field-meta.xml
<CustomField>
    <fullName>Id_Field__c</fullName>
    <defaultValue>&quot;GUID__c&quot;</defaultValue>
    <label>Id Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Data_Servicer__mdt/fields/Key_Field__c.field-meta.xml
<CustomField>
    <fullName>Key_Field__c</fullName>
    <defaultValue>&quot;GUID__c&quot;</defaultValue>
    <description>Notes the field to use to find the existing record.  Assumes that the value is unique to the object.</description>
    <label>Key Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/DataService.cls
@RestResource(urlMapping='/DataService/*')
global with sharing class DataService {
    static Map<String, Object> requestMap = new Map<String, Object>();
    static Map<String, Object> responseMap = new Map<String, Object>{
        'success' => true
    };
    static String requestName;
    public static DataResponse response = new DataResponse();

    @HttpPut
    global static void doPut() {
        RestContext.response.statusCode = 201;
        String requestJson = RestContext.request.requestBody.toString();
        try {
            requestMap = (Map<String, Object>) JSON.deserializeUntyped(
                requestJson
            );
            requestName = (String) requestMap.get('requestName');
            processRequest();
            RestContext.response.responseBody = Blob.valueOf(
                JSON.serialize(response)
            );
        } catch (Exception e) {
            ExceptionHandler.process(
                e,
                'DataService :: ' + requestName,
                requestJson
            );
            response.success = false;
            response.message =
                'Error: ' +
                e.getMessage() +
                '\n\n\n' +
                e.getStackTraceString();
            RestContext.response.statusCode = 500;
        }
    }

    // @HttpGet
    // global static DataResponse doGet() {
    //     RestRequest req = RestContext.request;

    //     Map<String, String> params = req.params;
    //     if (!params.containsKey('requestName') || !params.containsKey('guid')) {
    //         response.success = false;
    //         response.message = 'Invalid Record Identifier.';
    //         return response;
    //     }
    //     requestName = params.get('requestName');
    //     requestMap.put('data', params);
    //     processRequest();
    //     return response;
    // }

    static void processRequest() {
        DataServiceProcessor processor = getProcessor();
        if (processor == null) {
            response.success = false;
            response.message = 'Invalid Request';
            return;
        }

        response.init(processor.execute(requestMap.get('data')));
    }

    private static DataServiceProcessor getProcessor() {
        List<Data_Servicer__mdt> servicerMdts = [
            SELECT
                Apex_Class__c,
                Key_Field__c,
                Id_Field__c,
                (
                    SELECT Source__c, Target__c, SObject__c, Data_Type__c
                    FROM API_Mappings__r
                )
            FROM Data_Servicer__mdt
            WHERE Label = :requestName
        ];
        if (servicerMdts.isEmpty()) {
            return null;
        }
        DataServiceProcessor processor;
        Type myType = Type.forName(servicerMdts[0].Apex_Class__c);
        if (myType != null) {
            processor = (DataServiceProcessor) myType.newInstance();
            processor.init(servicerMdts[0]);
        }

        return processor;
    }

    global class DataResponse {
        public String data;
        public Boolean success;
        public String message;

        public void init(Map<String, Object> processorData) {
            this.success = (Boolean) processorData.get('success');
            if (processorData.containsKey('message')) {
                this.message = (String) processorData.get('message');
            }
            if (processorData.containsKey('data')) {
                this.data = Json.serialize(processorData.get('data'));
            }
        }
    }
}