unpackaged/main/default/objects/BCAccount__c/BCAccount__c.object-meta.xml
<CustomObject>
    <description>Yummy delicious technical debt.  All because there&#39;s no stomach for best practice, at least when it requires a modicum of effort or work on someone else&#39;s behalf. So yes, this object effectively duplicates the data that&#39;s in another object, simply to support the Fusion project. I wish that I could be hopeful that some day this object could be deprecated in favor of the object it should be using, but I know that as soon as this is implemented, it will be cemented indefinitely.  So don&#39;t hate me, future owner of this system, just know that we were ordered to do these things, despite our most fervent objections.</description>
    <label>BCAccount</label>
    <nameField>
        <label>BCAccount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BCAccounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BCAccount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>BCAccounts</relationshipLabel>
    <relationshipName>BCAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/BCAccount__c/fields/Brightcove_Account__c.field-meta.xml
<CustomField>
    <fullName>Brightcove_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Brightcove Account</label>
    <referenceTo>Brightcove_Account__c</referenceTo>
    <relationshipLabel>BCAccounts</relationshipLabel>
    <relationshipName>BCAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/BCAccount__c/fields/Publisher_Status__c.field-meta.xml
<CustomField>
    <fullName>Publisher_Status__c</fullName>
    <formula>TEXT( Brightcove_Account__r.Publisher_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Publisher Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BCAccount_Edition_History__c/BCAccount_Edition_History__c.object-meta.xml
<CustomObject>
    <description>Only used for the Fusion project.</description>
    <label>BCAccount_Edition_History</label>
    <nameField>
        <displayFormat>Change-{0000000}</displayFormat>
        <label>BCAccount_Edition_History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BCAccount_Edition_History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BCAccount_Edition_History__c/fields/BCAccount__c.field-meta.xml
<CustomField>
    <fullName>BCAccount__c</fullName>
    <label>BCAccount</label>
    <referenceTo>BCAccount__c</referenceTo>
    <relationshipLabel>BCAccount_Edition_History</relationshipLabel>
    <relationshipName>BCAccount_Edition_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/BCAccount_Edition_History__c/fields/Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>Changed_Date__c</fullName>
    <label>Changed Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/Brightcove_Account__c.object-meta.xml
<CustomObject>
    <label>Brightcove Account</label>
    <nameField>
        <label>Brightcove Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brightcove Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brightcove Account</relationshipLabel>
    <relationshipName>Brightcove_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Brightcove_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Brightcove_Account_Id__c</fullName>
    <description>The Pub ID of the Brightcove account&#39;s Id in our own database. Updated via sync from origin-services account.</description>
    <externalId>true</externalId>
    <inlineHelpText>The Pub ID of the Brightcove account&#39;s Id in our own database. Updated via sync from origin-services account.</inlineHelpText>
    <label>Brightcove Account Id</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Publisher_Status__c.field-meta.xml
<CustomField>
    <fullName>Publisher_Status__c</fullName>
    <description>Current status of the publisher&#39;s account.</description>
    <inlineHelpText>Current status of the publisher&#39;s account. Updated via sync from origin-services account.</inlineHelpText>
    <label>Publisher Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED</fullName>
            </value>
            <value>
                <fullName>UNREQUESTED</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
            </value>
            <value>
                <fullName>ENROLLED</fullName>
            </value>
            <value>
                <fullName>DENIED</fullName>
            </value>
            <value>
                <fullName>CLOSED</fullName>
            </value>
            <value>
                <fullName>LOCKED</fullName>
            </value>
            <value>
                <fullName>LOCKED_NON_PAYMENT</fullName>
            </value>
            <value>
                <fullName>LOCKED_TRIAL_EXPIRED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/BrightcoveAccountToBCAccountHandlerTest.cls
@isTest(isparallel=true)
public with sharing class BrightcoveAccountToBCAccountHandlerTest {
  @isTest
  static void testProcess() {
    Account account = AccountTestFactory.createCustomer();

    List<Brightcove_Account__c> brightcoveAccounts = new List<Brightcove_Account__c>{
      new Brightcove_Account__c(
        Email_Address__c = 'mhigel@example.com',
        Brightcove_Account_Id__c = '123456',
        Account__c = account.Id
      ),
      new Brightcove_Account__c(
        Email_Address__c = 'mhigel@example.com',
        Brightcove_Account_Id__c = '67890'
      )
    };

    insert brightcoveAccounts;

    Test.getEventBus().deliver();
    Test.startTest();

    List<BCAccount__c> bcAccounts = [
      SELECT Id, Account__c, Brightcove_Account__c
      FROM BCAccount__c
      WHERE Brightcove_Account__c IN :brightcoveAccounts
    ];
    System.assertEquals(
      brightcoveAccounts.size(),
      bcAccounts.size(),
      'No BCAccount record created from Brightcove Account record.'
    );

    Map<Id, Brightcove_Account__c> brightcoveAccountsMap = new Map<Id, Brightcove_Account__c>(
      brightcoveAccounts
    );
    for (BCAccount__c bcAccount : bcAccounts) {
      Brightcove_Account__c brightcoveAccount = brightcoveAccountsMap.get(
        bcAccount.Brightcove_Account__c
      );
      System.assertEquals(
        brightcoveAccount.Account__c,
        bcAccount.Account__c,
        'Account reference incorrectly applied.'
      );
    }

    brightcoveAccounts[0].Publisher_Status__c = 'LOCKED';
    brightcoveAccounts[1].Account__c = account.Id;
    update brightcoveAccounts;

    Test.getEventBus().deliver();
    Test.stopTest();

    bcAccounts = [
      SELECT Id, Account__c, Brightcove_Account__c
      FROM BCAccount__c
      WHERE Brightcove_Account__c IN :brightcoveAccounts
    ];
    System.assertEquals(
      brightcoveAccounts.size(),
      bcAccounts.size(),
      'No BCAccount record created from Brightcove Account record.'
    );

    brightcoveAccountsMap = new Map<Id, Brightcove_Account__c>(
      brightcoveAccounts
    );
    for (BCAccount__c bcAccount : bcAccounts) {
      Brightcove_Account__c brightcoveAccount = brightcoveAccountsMap.get(
        bcAccount.Brightcove_Account__c
      );
      System.assertEquals(
        brightcoveAccount.Account__c,
        bcAccount.Account__c,
        'Account reference incorrectly applied.'
      );
    }

    List<BCAccount_Edition_History__c> histories = [
      SELECT Id, Changed_Date__c
      FROM BCAccount_Edition_History__c
      WHERE BCAccount__r.Brightcove_Account__c = :brightcoveAccounts[0].Id
    ];
    System.assertEquals(
      1,
      histories.size(),
      'BCAccount Edition History record not created when Brightcove Account record was locked.'
    );
    System.assertEquals(
      Date.today(),
      histories[0].Changed_Date__c,
      'Changed Date on BCAccount Edition History record not correctly set.'
    );
  }
}