unpackaged/main/default/objects/BCAccount__c/BCAccount__c.object-meta.xml
<CustomObject>
    <description>Yummy delicious technical debt.  All because there&#39;s no stomach for best practice, at least when it requires a modicum of effort or work on someone else&#39;s behalf. So yes, this object effectively duplicates the data that&#39;s in another object, simply to support the Fusion project. I wish that I could be hopeful that some day this object could be deprecated in favor of the object it should be using, but I know that as soon as this is implemented, it will be cemented indefinitely.  So don&#39;t hate me, future owner of this system, just know that we were ordered to do these things, despite our most fervent objections.</description>
    <label>BCAccount</label>
    <nameField>
        <label>BCAccount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BCAccounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BCAccount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>BCAccounts</relationshipLabel>
    <relationshipName>BCAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/BCAccount__c/fields/Brightcove_Account__c.field-meta.xml
<CustomField>
    <fullName>Brightcove_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Brightcove Account</label>
    <referenceTo>Brightcove_Account__c</referenceTo>
    <relationshipLabel>BCAccounts</relationshipLabel>
    <relationshipName>BCAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/BCAccount__c/fields/Publisher_Status__c.field-meta.xml
<CustomField>
    <fullName>Publisher_Status__c</fullName>
    <formula>TEXT( Brightcove_Account__r.Publisher_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Publisher Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/Brightcove_Account__c.object-meta.xml
<CustomObject>
    <label>Brightcove Account</label>
    <nameField>
        <label>Brightcove Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brightcove Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brightcove Account</relationshipLabel>
    <relationshipName>Brightcove_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Brightcove_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Brightcove_Account_Id__c</fullName>
    <description>The Pub ID of the Brightcove account&#39;s Id in our own database. Updated via sync from origin-services account.</description>
    <externalId>true</externalId>
    <inlineHelpText>The Pub ID of the Brightcove account&#39;s Id in our own database. Updated via sync from origin-services account.</inlineHelpText>
    <label>Brightcove Account Id</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Publisher_Status__c.field-meta.xml
<CustomField>
    <fullName>Publisher_Status__c</fullName>
    <description>Current status of the publisher&#39;s account.</description>
    <inlineHelpText>Current status of the publisher&#39;s account. Updated via sync from origin-services account.</inlineHelpText>
    <label>Publisher Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED</fullName>
            </value>
            <value>
                <fullName>UNREQUESTED</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
            </value>
            <value>
                <fullName>ENROLLED</fullName>
            </value>
            <value>
                <fullName>DENIED</fullName>
            </value>
            <value>
                <fullName>CLOSED</fullName>
            </value>
            <value>
                <fullName>LOCKED</fullName>
            </value>
            <value>
                <fullName>LOCKED_NON_PAYMENT</fullName>
            </value>
            <value>
                <fullName>LOCKED_TRIAL_EXPIRED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account_Event__e/Brightcove_Account_Event__e.object-meta.xml
<CustomObject>
    <description>This platform event is used to create a new BCAccount__c record when a new Brightcove_Account__c record is created. If  that sounds like data-duplicate, you&#39;re correct.  This technical debt is brought to you by the letter F, as in Fusion.  Instead of taking 5 minutes to change &quot;BCAccount__c&quot; to &quot;Brightcove_Account__c&quot;, we&#39;re going to create a new custom object called &quot;BCAccount__c&quot; and then create automation to create a record for it every time a new Brightcove_Account__c record is created.  If all of that sounds like more than 5 minutes of work, you&#39;d be correct!  If this sounds like madness, you&#39;d also be correct.  To whomever inherits this, you have my sincerest apologies.  I did not want this hell for me, and I do not wish it on you.  Like so much evil in this world, this all exists because I was ordered to do it.  May god have mercy on my soul.</description>
    <label>Brightcove Account Event</label>
    <pluralLabel>Brightcove Account Events</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Brightcove_Account_Event__e/fields/Brightcove_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Brightcove_Account_Id__c</fullName>
    <label>Brightcove Account Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account_Event__e/fields/Requires_History__c.field-meta.xml
<CustomField>
    <fullName>Requires_History__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires History</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/BrightcoveAccountToBCAccountHandler.cls
public with sharing class BrightcoveAccountToBCAccountHandler extends DomainLogicHandler {
    public List<Brightcove_Account_Event__e> events = new List<Brightcove_Account_Event__e>();
    List<Id> brightcoveAccountIds = new List<Id>();

    public override void check(SObject newObj) {
        events.add(getEvent((Brightcove_Account__c) newObj));
    }

    public override void check(SObject newObj, SObject oldObj) {
        Brightcove_Account__c newBrightcoveAccount = (Brightcove_Account__c) newObj;
        if (isQualified(newBrightcoveAccount, oldObj)) {
            Brightcove_Account_Event__e event = getEvent(newBrightcoveAccount);
            event.Requires_History__c = isNowLocked(
                newBrightcoveAccount,
                oldObj
            );
            events.add(event);
        } else {
            brightcoveAccountIds.add(newBrightcoveAccount.Id);
        }
    }

    public override void processRecords() {
        if (!events.isEmpty()) {
            Eventbus.publish(events);
        }

        /**
         * This is one the dumbest (may actually THE dumbest) thing I've ever had to do.
         * Oracle queries the LastModifiedDate of BCAccount__c records during the Subcription
         * integration, and since BCAccount__c is just a shell-duplication of the actual
         * Brightcove_Account__c records, we have to do a no-change update DML to get the
         * LastModifiedDate of the related BCAccount__c records updated anytime their parent
         * Brightcove_Account__c record is updated.  All of this just because "we" don't want
         * to take 5 minutes to change the name of an object in a query from "BCAccount__c" to
         * "Brightcove_Account__c".  I am now dumber for having done this, regardless of the
         * justification.
         */
        if (!brightcoveAccountIds.isEmpty()) {
            List<BCAccount__c> bcAccounts = [
                SELECT Id
                FROM BCAccount__c
                WHERE Brightcove_Account__c IN :brightcoveAccountIds
            ];
            update bcAccounts;
        }
    }

    Brightcove_Account_Event__e getEvent(
        Brightcove_Account__c newBrightcoveAccount
    ) {
        Brightcove_Account_Event__e event = new Brightcove_Account_Event__e(
            Brightcove_Account_Id__c = newBrightcoveAccount.Id,
            Name__c = newBrightcoveAccount.Name
        );
        if (hasAccount(newBrightcoveAccount)) {
            event.Account_Id__c = newBrightcoveAccount.Account__c;
        }

        return event;
    }

    Boolean hasAccount(Brightcove_Account__c newBrightcoveAccount) {
        return newBrightcoveAccount.Account__c != null;
    }

    Boolean isQualified(
        Brightcove_Account__c newBrightcoveAccount,
        SObject oldObj
    ) {
        return isAccountChanged(newBrightcoveAccount, oldObj) ||
            isNowLocked(newBrightcoveAccount, oldObj);
    }

    Boolean isAccountChanged(
        Brightcove_Account__c newBrightcoveAccount,
        SObject oldObj
    ) {
        List<SObjectField> fields = new List<SObjectField>{
            Brightcove_Account__c.Account__c,
            Brightcove_Account__c.Name
        };
        return TriggerUtility.isChanged(
            newBrightcoveAccount,
            oldObj,
            fields  
        );
    }

    Boolean isNowLocked(
        Brightcove_Account__c newBrightcoveAccount,
        SObject oldObj
    ) {
        return TriggerUtility.isChanged(
                newBrightcoveAccount,
                oldObj,
                Brightcove_Account__c.Publisher_Status__c
            ) && isLocked(newBrightcoveAccount);
    }

    Boolean isLocked(Brightcove_Account__c newBrightcoveAccount) {
        return newBrightcoveAccount.Publisher_Status__c == 'LOCKED';
    }
}