unpackaged/main/default/objects/Account_Products_Events__e/Account_Products_Events__e.object-meta.xml
<CustomObject>
    <label>AccountProduct Event</label>
    <pluralLabel>AccountProduct Events</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Account_Products_Events__e/fields/Subscription_Id__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Id__c</fullName>
    <label>Subscription Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/SubscriptionsToAccountProductsHandler.cls
/*
Object: Subcriptions (CPQ)
Events: AFTER_INSERT, AFTER_UPDATE
Description: called when a CPQ subscription is created/updated it publish a platform event called: Subscription_Events__e passing the ID of the Subscription
and it's managed by the 'SubscriptionPlatformEventHandler'
*/
public with sharing class SubscriptionsToAccountProductsHandler extends DomainLogicHandler {
  public List<Account_Products_Events__e> events = new List<Account_Products_Events__e>();

  public override void check(SObject obj) {
    events.add(getEvent((SBQQ__Subscription__c) obj));
  }
  public override void processRecords() {
    if (!events.isEmpty()) {
      EventBus.publish(events);
    }
  }

  private Account_Products_Events__e getEvent(SBQQ__Subscription__c record) {
    return new Account_Products_Events__e(Subscription_Id__c = record.Id);
  }
}