unpackaged/main/default/objects/Account/fields/Account_Stage__c.field-meta.xml
<CustomField>
    <fullName>Account_Stage__c</fullName>
    <label>Account Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Stages</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>for customer &amp; Prospect</description>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Client_Termination_Status__c.field-meta.xml
<CustomField>
    <fullName>Client_Termination_Status__c</fullName>
    <label>Client Termination Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Account_Stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
        <default>true</default>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <customValue>
        <fullName>Former</fullName>
    </customValue>
    <masterLabel>Account Stages</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/OpportunityClientTerminationHandlerTest.cls
@isTest
public with sharing class OpportunityClientTerminationHandlerTest {
    @TestSetup
    static void makeData() {
        Account account = AccountTestFactory.getCustomer();
        account.Account_Stage__c = 'Customer';
        account.Name = 'OpportunityClientTerminationHandlerTest';
        insert account;

        Opportunity opp = OpportunityTestFactory.getStage1Opp(account.Id);
        opp.RecordTypeId = RecordTypeUtility.getId(
            Opportunity.getSObjectType(),
            'Add-On'
        );
        insert opp;
    }

    @isTest
    static void testUpdateAccounts() {
        Opportunity opp = [
            SELECT Id, AccountId, Client_Termination_Status__c
            FROM Opportunity
            WHERE Account.Name = 'OpportunityClientTerminationHandlerTest'
            LIMIT 1
        ];
        opp.Client_Termination_Status__c = 'Approved';

        Test.startTest();
        update opp;
        Test.stopTest();

        Account account = [
            SELECT Id, Account_Stage__c
            FROM Account
            WHERE Id = :opp.AccountId
        ];
        System.assertEquals(
            'Former',
            account.Account_Stage__c,
            'Account Stage was not set to Former.'
        );
    }
}