unpackaged/main/default/objects/Account/fields/Account_Stage__c.field-meta.xml
<CustomField>
    <fullName>Account_Stage__c</fullName>
    <label>Account Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Stages</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Named_Account__c.field-meta.xml
<CustomField>
    <fullName>Named_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Named Account</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6QA__c.field-meta.xml
<CustomField>
    <fullName>X6QA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>6QA</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6sense_Account_6QA_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Account_6QA_Start_Date__c</fullName>
    <label>6sense Account 6QA Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6sense_Account_Buying_Stage__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Account_Buying_Stage__c</fullName>
    <label>6sense Account Buying Stage</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6sense_Account_Intent_Score__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Account_Intent_Score__c</fullName>
    <label>6sense Account Intent Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6sense_Account_Profile_Fit__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Account_Profile_Fit__c</fullName>
    <label>6sense Account Profile Fit</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6sense_Account_Reach_Score__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Account_Reach_Score__c</fullName>
    <label>6sense Account Reach Score</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6Sense_Segment_Name__c.field-meta.xml
<CustomField>
    <fullName>X6Sense_Segment_Name__c</fullName>
    <label>6Sense Segment Name</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6sense_Stage_Awareness__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Stage_Awareness__c</fullName>
    <label>6sense Stage – Awareness</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6sense_Stage_Decision__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Stage_Decision__c</fullName>
    <label>6sense Stage – Decision</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6sense_Stage_Purchase__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Stage_Purchase__c</fullName>
    <label>6sense Stage – Purchase</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Account_Stage_at_Creation__c.field-meta.xml
<CustomField>
    <fullName>Account_Stage_at_Creation__c</fullName>
    <label>Account Stage at Creation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Stages</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Named_Account__c.field-meta.xml
<CustomField>
    <fullName>Named_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Named Account</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Named_Account_Tier__c.field-meta.xml
<CustomField>
    <fullName>Named_Account_Tier__c</fullName>
    <label>Named Account Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
            <value>
                <fullName>Tier 3</fullName>
            </value>
            <value>
                <fullName>Tier 4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6QA__c.field-meta.xml
<CustomField>
    <fullName>X6QA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>6QA</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6sense_6QA__c.field-meta.xml
<CustomField>
    <fullName>X6sense_6QA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>6sense 6QA</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6sense_Account_6QA_End_Date__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Account_6QA_End_Date__c</fullName>
    <label>6sense Account 6QA End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6sense_Account_Buying_Stage__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Account_Buying_Stage__c</fullName>
    <label>6sense Account Buying Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6sense_Account_Profile_Fit__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Account_Profile_Fit__c</fullName>
    <label>6sense Account Profile Fit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6Sense_Segment_Name__c.field-meta.xml
<CustomField>
    <fullName>X6Sense_Segment_Name__c</fullName>
    <label>6Sense Segment Name</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6sense_Stage_Consideration__c.field-meta.xml
<CustomField>
    <fullName>X6sense_Stage_Consideration__c</fullName>
    <label>6sense Stage – Consideration</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <businessProcess>Lead</businessProcess>
    <label>Lead</label>
</RecordType>

unpackaged/main/default/globalValueSets/Account_Stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
        <default>true</default>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <customValue>
        <fullName>Former</fullName>
    </customValue>
    <masterLabel>Account Stages</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/OpportunityAccountStamperTest.cls
@isTest
public with sharing class OpportunityAccountStamperTest {
  @TestSetup
  static void makeData() {
    Account account = AccountTestFactory.getCustomer();
    account.Name = 'OpportunityAccountStamperTest';
    account.X6sense_Account_6QA_End_Date__c = Date.today().addDays(-1);
    account.X6sense_Account_6QA_Start_Date__c = Date.today().addDays(-2);
    account.X6sense_Account_Buying_Stage__c = 'Definitely buying';
    account.X6sense_Account_Intent_Score__c = 123;
    account.X6sense_Account_Profile_Fit__c = 'Nice fit';
    account.X6sense_Account_Reach_Score__c = '456';
    account.X6Sense_Segment_Name__c = 'Nice segment my friend';
    account.X6sense_Stage_Awareness__c = Date.today().addDays(-4);
    account.X6sense_Stage_Consideration__c = Date.today().addDays(-3);
    account.X6sense_Stage_Decision__c = Date.today().addDays(-2);
    account.X6sense_Stage_Purchase__c = Date.today().addDays(-1);
    account.Named_Account__c = true;
    account.Named_Account_Tier__c = 'Tier 1';

    insert account;
  }

  @isTest
  static void testStageZeroOppCreation() {
    Account account = [
      SELECT Id, X6QA__c
      FROM Account
      WHERE Name = 'OpportunityAccountStamperTest'
    ];
    account.X6QA__c = true;
    Id accountId = account.Id;

    Test.startTest();
    update account;
    Test.stopTest();

    List<String> fields = new List<String>{
      'X6sense_Account_6QA_End_Date__c',
      'X6sense_Account_6QA_Start_Date__c',
      'X6sense_Account_Buying_Stage__c',
      'X6sense_Account_Intent_Score__c',
      'X6sense_Account_Profile_Fit__c',
      'X6sense_Account_Reach_Score__c',
      'X6Sense_Segment_Name__c',
      'X6sense_Stage_Awareness__c',
      'X6sense_Stage_Consideration__c',
      'X6sense_Stage_Decision__c',
      'X6sense_Stage_Purchase__c',
      'Named_Account__c',
      'Named_Account_Tier__c'
    };

    List<Opportunity> opps = Database.query(
      'SELECT Id, Account_Stage_at_Creation__c, X6sense_6QA__c, ' +
        String.join(fields, ', ') +
        ' FROM Opportunity WHERE AccountId = :accountId AND RecordType.Name =\'Lead\''
    );

    System.assertEquals(
      1,
      opps.size(),
      'Incorrect number of Opportunity records created.'
    );

    account = (Account) Database.query(
      'SELECT Id, Account_Stage__c, X6QA__c, ' +
        String.join(fields, ', ') +
        ' FROM Account WHERE Id = :accountId'
    );

    System.assertEquals(
      account.Account_Stage__c,
      opps[0].Account_Stage_at_Creation__c,
      'Account Stage at Creation not correctly set on Opportunity'
    );

    System.assertEquals(
      account.X6QA__c,
      opps[0].X6sense_6QA__c,
      '6Sense at Creation not correctly set on Opportunity'
    );
    for (String field : fields) {
      Object expected = account.get(field);
      Object actual = opps[0].get(field);
      System.assertEquals(
        expected,
        actual,
        'Incorrect value set on Opportunity for field: ' + field
      );
    }
  }

  @isTest
  static void testStageOneOpp() {
    Account account = [
      SELECT Id, X6QA__c
      FROM Account
      WHERE Name = 'OpportunityAccountStamperTest'
    ];
    account.X6QA__c = true;
    Id accountId = account.Id;

    update account;

    Test.startTest();

    Opportunity opp = OpportunityTestFactory.getStage1Opp(account.Id);
    insert opp;

    Test.stopTest();

    List<String> fields = new List<String>{
      'X6sense_Account_6QA_End_Date__c',
      'X6sense_Account_6QA_Start_Date__c',
      'X6sense_Account_Buying_Stage__c',
      'X6sense_Account_Intent_Score__c',
      'X6sense_Account_Profile_Fit__c',
      'X6sense_Account_Reach_Score__c',
      'X6Sense_Segment_Name__c',
      'X6sense_Stage_Awareness__c',
      'X6sense_Stage_Consideration__c',
      'X6sense_Stage_Decision__c',
      'X6sense_Stage_Purchase__c',
      'Named_Account__c',
      'Named_Account_Tier__c'
    };

    account = (Account) Database.query(
      'SELECT Id, Account_Stage__c, X6QA__c, ' +
        String.join(fields, ', ') +
        ' FROM Account WHERE Name = \'OpportunityAccountStamperTest\''
    );

    opp = (Opportunity) Database.query(
      'SELECT Id, Account_Stage_at_Creation__c, X6sense_6QA__c, ' +
        String.join(fields, ', ') +
        ' FROM Opportunity WHERE AccountId = :accountId AND RecordType.Name =\'New Business\''
    );

    System.assertEquals(
      account.Account_Stage__c,
      opp.Account_Stage_at_Creation__c,
      'Account Stage at Creation not correctly set on Opportunity'
    );

    System.assertEquals(
      account.X6QA__c,
      opp.X6sense_6QA__c,
      '6Sense at Creation not correctly set on Opportunity'
    );

    for (String field : fields) {
      Object expected = account.get(field);
      Object actual = opp.get(field);
      System.assertEquals(
        expected,
        actual,
        'Incorrect value set on Opportunity for field: ' + field
      );
    }
  }
}