unpackaged/main/default/objects/Account/fields/Account_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Account_Business_Unit__c</fullName>
    <label>Account Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Account_Stage__c.field-meta.xml
<CustomField>
    <fullName>Account_Stage__c</fullName>
    <label>Account Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Stages</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Named_Account__c.field-meta.xml
<CustomField>
    <fullName>Named_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Named Account</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sales_Division__c.field-meta.xml
<CustomField>
    <fullName>Sales_Division__c</fullName>
    <label>Sales Division</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>for customer &amp; Prospect</description>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/globalValueSets/Account_Stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
        <default>true</default>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <customValue>
        <fullName>Former</fullName>
    </customValue>
    <masterLabel>Account Stages</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/StageZeroOppNewBusinessQualifier.cls
/**
 * test coverage is found in Account6QAOppHandlerTest
 */
public with sharing class StageZeroOppNewBusinessQualifier {
  public static Boolean isQualified(Account account) {
    return isNotExistingCustomer(account) && checkNamed(account);
  }

  static Boolean isNotExistingCustomer(Account account) {
    return account.Account_Stage__c != 'Customer';
  }

  static Boolean checkNamed(Account account) {
    return isNamedAccount(account) && isTierQualified(account);
  }

  static Boolean isNamedAccount(Account account) {
    return account.Named_Account__c;
  }

  static Boolean isTierQualified(Account account) {
    return isTopTiered(account) || isQualifiedLowerTier(account);
  }

  static Boolean isTopTiered(Account account) {
    List<String> qualifiedTiers = new List<String>{ 'Tier 1', 'Tier 2' };
    return qualifiedTiers.contains(account.Named_Account_Tier__c);
  }

  static Boolean isQualifiedLowerTier(Account account) {
    List<String> qualifiedTiers = new List<String>{ 'Tier 3' };
    return qualifiedTiers.contains(account.Named_Account_Tier__c) &&
      isMedia(account) &&
      isAmericas(account);
  }

  static Boolean isMedia(Account account) {
    return account.Account_Business_Unit__c == 'Media';
  }

  static Boolean isAmericas(Account account) {
    return account.Sales_Division__c == 'Americas';
  }
}