unpackaged/main/default/objects/Account/fields/Account_Stage__c.field-meta.xml
<CustomField>
    <fullName>Account_Stage__c</fullName>
    <label>Account Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Stages</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>for customer &amp; Prospect</description>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/First_Response__c.field-meta.xml
<CustomField>
    <fullName>First_Response__c</fullName>
    <description>It stores the First response date and time and triggers the auto-complete of the milestone.</description>
    <label>First Response</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/globalValueSets/Account_Stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
        <default>true</default>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <customValue>
        <fullName>Former</fullName>
    </customValue>
    <masterLabel>Account Stages</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CaseEscalationParentHandlerTest.cls
@isTest
private class CaseEscalationParentHandlerTest {
  @TestSetup
  static void makeData() {
    Id accountCustomerRecordType = RecordTypeUtility.getId(
      Account.getSObjectType(),
      'Customer'
    );

    Account parentAccount = new Account(
      Name = 'ParentAccount',
      recordtypeId = accountCustomerRecordType,
      Account_Stage__c = 'Customer',
      BillingCountry = 'Italy'
    );
    Account dummyAccount = new Account(
      Name = 'DummyAccount',
      recordTypeId = accountCustomerRecordType,
      Account_Stage__c = 'Customer',
      BillingCountry = 'Italy'
    );

    List<Account> accountList = new List<Account>();
    accountList.add(parentAccount);
    accountList.add(dummyAccount);

    insert accountList;

    Id caseCaseEscalation = RecordTypeUtility.getId(
      Case.getSObjectType(),
      'Case Escalation'
    );

    Id caseTechnicalSupport = RecordTypeUtility.getId(
      Case.getSObjectType(),
      'Technical Support'
    );

    Case caseTechSupport = new Case(
      Account = parentAccount,
      Description = 'TestParentAccount',
      Subject = 'TestParentAccount',
      RecordTypeId = caseTechnicalSupport,
      Origin = 'Email',
      First_Response__c = system.now()
    );

    Case caseEscalation = new Case(
      Account = dummyAccount,
      Description = 'TestDummyEscalation',
      Subject = 'TestDummyEscalation',
      RecordTypeId = caseCaseEscalation
    );

    List<Case> caseList = new List<Case>();
    caseList.add(caseTechSupport);
    caseList.add(caseEscalation);

    insert caseList;
  }

  @isTest
  static void testAccountUpdate() {
    Case caseTechSupport = [
      SELECT Id, AccountId
      FROM Case
      WHERE Subject = 'TestParentAccount'
    ];

    Case caseEscalation = [
      SELECT Id, AccountId, ParentId, Parent.AccountId
      FROM Case
      WHERE Subject = 'TestDummyEscalation'
    ];

    Test.startTest();
    caseEscalation.ParentId = caseTechSupport.Id;
    update caseEscalation;
    Test.stopTest();

    Case caseEscalationAFTER = [
      SELECT Id, AccountId, ParentId, Parent.AccountId
      FROM Case
      WHERE Subject = 'TestDummyEscalation'
    ];

    System.assertEquals(
      caseTechSupport.AccountId,
      caseEscalationAFTER.AccountId,
      'err: Case Escalation Account not updated'
    );
  }
}