unpackaged/main/default/objects/Account/fields/Account_Stage__c.field-meta.xml
<CustomField>
    <fullName>Account_Stage__c</fullName>
    <label>Account Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Stages</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Client_Termination_Status__c.field-meta.xml
<CustomField>
    <fullName>Client_Termination_Status__c</fullName>
    <label>Client Termination Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Account_Stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
        <default>true</default>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <customValue>
        <fullName>Former</fullName>
    </customValue>
    <masterLabel>Account Stages</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/OpportunityClientTerminationHandler.cls
public with sharing class OpportunityClientTerminationHandler extends DomainLogicHandler {
    List<Account> accounts = new List<Account>();

    public override void check(SObject newObj, SObject oldObj) {
        Opportunity newOpp = (Opportunity) newObj;
        if (isQualified(newObj, oldObj)) {
            accounts.add(
                new Account(Id = newOpp.AccountId, Account_Stage__c = 'Former')
            );
        }
    }

    public override void processRecords() {
        update accounts;
    }

    Boolean isQualified(SObject newObj, SObject oldObj) {
        return isChanged(newObj, oldObj) &&
            isClientTerminiationApproved((Opportunity) newObj);
    }

    Boolean isClientTerminiationApproved(Opportunity newOpp) {
        return newOpp.Client_Termination_Status__c == 'Approved';
    }

    Boolean isChanged(SObject newObj, SObject oldObj) {
        return TriggerUtility.isChanged(
            newObj,
            oldObj,
            Opportunity.Client_Termination_Status__c
        );
    }
}