unpackaged/main/default/objects/Account/fields/Account_Stage__c.field-meta.xml
<CustomField>
    <fullName>Account_Stage__c</fullName>
    <label>Account Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Stages</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6QA__c.field-meta.xml
<CustomField>
    <fullName>X6QA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>6QA</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>for customer &amp; Prospect</description>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard Term Contract</fullName>
            </value>
            <value>
                <fullName>Pilot / PoC / Campaign</fullName>
            </value>
            <value>
                <fullName>Ramp Contract</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <description>What type of opportunity is this?</description>
    <inlineHelpText>New Business = brand new logo

Upgrade = upgrading an Express customer to higher edition

Add-on = selling to existing customer

Renewal = existing deal renewed at end of its term

Early Renewal = existing deal renewed before current term is up</inlineHelpText>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Add-On</fullName>
            </value>
            <value>
                <fullName>Debook</fullName>
            </value>
            <value>
                <fullName>Early Renewal</fullName>
            </value>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Renewal Growth</fullName>
            </value>
            <value>
                <fullName>Services Record Type</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Forecast__c.field-meta.xml
<CustomField>
    <fullName>Forecast__c</fullName>
    <inlineHelpText>Confidence the deal will close in this quarter.</inlineHelpText>
    <label>Forecast</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pipeline</fullName>
            </value>
            <value>
                <fullName>Commit</fullName>
            </value>
            <value>
                <fullName>Upside</fullName>
            </value>
            <value>
                <fullName>Omitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X6QA__c.field-meta.xml
<CustomField>
    <fullName>X6QA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>6QA</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <businessProcess>Lead</businessProcess>
    <label>Lead</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <businessProcess>Standard Sales Process</businessProcess>
    <description>System generated Opportunity used for renewing a Contract at the end of its term</description>
    <label>Renewal</label>
</RecordType>

unpackaged/main/default/globalValueSets/Account_Stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
        <default>true</default>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <customValue>
        <fullName>Former</fullName>
    </customValue>
    <masterLabel>Account Stages</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/Account6QAOppHandler.cls
public with sharing class Account6QAOppHandler extends DomainLogicHandler {
    Map<Id, Account> qualifiedAccounts = new Map<Id, Account>();
    Id oppLeadRecordType = RecordTypeUtility.getId(
        Opportunity.getSObjectType(),
        'Lead'
    );
    Id defaultOwnerId;

    public override void check(SObject newObj, SObject oldObj) {
        Account newAccount = (Account) newObj;
        Account oldAccount = (Account) oldObj;

        if (isQualified(newAccount, oldAccount)) {
            qualifiedAccounts.put(newAccount.Id, newAccount);
        }
    }

    public override void processRecords() {
        BCMap openOpps = getOpenOpps();
        setDefaultOwnerId();

        List<Opportunity> opps = new List<Opportunity>();
        for (Account qualifiedAccount : qualifiedAccounts.values()) {
            if (!openOpps.containsKey(qualifiedAccount.Id)) {
                opps.add(getNewOpp(qualifiedAccount));
            }
        }

        insert opps;
    }

    Opportunity getNewOpp(Account qualifiedAccount) {
        return new Opportunity(
            Name = 'Placeholder',
            RecordTypeId = oppLeadRecordType,
            CloseDate = Date.today().addDays(30),
            AccountId = qualifiedAccount.Id,
            StageName = '0 - Meeting Pending',
            OwnerId = defaultOwnerId,
            Contract_Type__c = 'Standard Term Contract',
            X6QA__c = true,
            Forecast__c = null,
            LeadSource = 'QA',
            Deal_Type__c = qualifiedAccount.Account_Stage__c == 'Customer' ? 'Add-On' : 'New Business'
        );
    }

    BCMap getOpenOpps() {
        List<Opportunity> opps = [
            SELECT Id, AccountId
            FROM Opportunity
            WHERE IsClosed = FALSE AND AccountId IN :qualifiedAccounts.keySet()
            AND (
                 (
                    Account.Account_Stage__c != 'Customer' 
                    AND RecordType.Name IN ('New Business', 'Lead')
                 ) OR (
                    Account.Account_Stage__c = 'Customer'
                    AND RecordType.Name IN ('Add-On', 'Lead', 'Renewal') 
                    AND CloseDate < :Date.today().addDays(90) AND CloseDate >= :Date.today()
                 )
            )
        ];
        
        return new BCMap(opps, 'AccountId');
    }

    Boolean isQualified(Account newAccount, Account oldAccount) {
        return TriggerUtility.isChanged(
                newAccount,
                oldAccount,
                Account.X6QA__c
            ) &&
            newAccount.X6QA__c &&
            (
                StageZeroOppNewBusinessQualifier.isQualified(newAccount) 
                || StageZeroOppAddOnQualifier.isQualified(newAccount)
            );
    }

    void setDefaultOwnerId() {
        String defaultOwnerUserName = Label.Default_Lead_Opp_Owner + '%';
        defaultOwnerId = [
            SELECT Id
            FROM User
            WHERE UserName LIKE :defaultOwnerUserName
        ]
        .Id;
    }
}