unpackaged/main/default/objects/Account/fields/Account_Stage__c.field-meta.xml
<CustomField>
    <fullName>Account_Stage__c</fullName>
    <label>Account Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Stages</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Support_package__c.field-meta.xml
<CustomField>
    <fullName>Support_package__c</fullName>
    <label>Support package</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Platinum+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>for customer &amp; Prospect</description>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/globalValueSets/Account_Stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
        <default>true</default>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <customValue>
        <fullName>Former</fullName>
    </customValue>
    <masterLabel>Account Stages</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/AccountDefaultSupportPackage.cls
public with sharing class AccountDefaultSupportPackage extends DomainLogicHandler {
  Map<Id, Account> accountList = new Map<Id, Account>();
  List<Id> accountCustomerList = new List<Id>();

  public override void check(SObject newObject) {
    Account newAccount = (Account) newObject;
    if (AccountDefaultSupportPackageQualifier.isQualified(newAccount)) {
      accountList.put(newAccount.Id, newAccount);
    }
  }

  public override void check(SObject newObject, SObject oldObject) {
    Account newAccount = (Account) newObject;
    Account oldAccount = (Account) oldObject;
    if (
      AccountDefaultSupportPackageQualifier.isQualified(newAccount, oldAccount)
    ) {
      if (newAccount.Account_Stage__c == 'Former') {
        accountList.put(newAccount.Id, newAccount);
      } else if (newAccount.Account_Stage__c == 'Customer') {
        accountCustomerList.add(newAccount.Id);
      }
    }
  }

  public override void processRecords() {
    if (!accountCustomerList.isEmpty()) {
      endDefaultGold(accountCustomerList);
    }
    if (!accountList.isEmpty()) {
      processAccounts(accountList);
    }
  }

  static void processAccounts(Map<Id, Account> accountList) {
    Map<String, String> accountStageSupportPackages = new Map<String, String>{
      'Prospect' => 'Gold',
      'Former' => 'Silver'
    };

    for (Account account : accountList.values()) {
      account.Support_Package__c = accountStageSupportPackages.get(
        account.Account_Stage__c
      );
    }
  }

  @Future
  static void endDefaultGold(List<Id> accountCustomerList) {
    List<Entitlement> entitlementsNotDefault = [
      SELECT AccountId
      FROM Entitlement
      WHERE AccountId IN :accountCustomerList AND (NOT Name LIKE '%Default')
    ];

    List<Id> accountNoSupport = new List<Id>();
    for (Entitlement ent : entitlementsNotDefault) {
      accountNoSupport.add(ent.AccountId);
    }

    List<Account> accountSupport = [
      SELECT Id, Support_Package__c
      FROM Account
      WHERE Id IN :accountCustomerList AND Id NOT IN :accountNoSupport
    ];

    for (Account accUpdate : accountSupport) {
      accUpdate.Support_Package__c = 'Silver';
    }
    update accountSupport;
  }
}