unpackaged/main/default/objects/Account/fields/Account_Stage__c.field-meta.xml
<CustomField>
    <fullName>Account_Stage__c</fullName>
    <label>Account Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Stages</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>for customer &amp; Prospect</description>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/objects/Lead/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <businessProcess>Lead Process</businessProcess>
    <label>Prospect</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard Term Contract</fullName>
            </value>
            <value>
                <fullName>Pilot / PoC / Campaign</fullName>
            </value>
            <value>
                <fullName>Ramp Contract</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Convert_to_Pipeline__c.field-meta.xml
<CustomField>
    <fullName>Convert_to_Pipeline__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Convert to Pipeline</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <businessProcess>Lead</businessProcess>
    <label>Lead</label>
</RecordType>

unpackaged/main/default/objects/User/fields/Sub_Division__c.field-meta.xml
<CustomField>
    <fullName>Sub_Division__c</fullName>
    <label>Sub Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
                <isActive>false</isActive>
                <label>APAC</label>
            </value>
            <value>
                <fullName>Americas</fullName>
                <isActive>false</isActive>
                <label>Americas</label>
            </value>
            <value>
                <fullName>Commercial</fullName>
                <isActive>false</isActive>
                <label>Commercial</label>
            </value>
            <value>
                <fullName>Expand</fullName>
                <isActive>false</isActive>
                <label>Expand</label>
            </value>
            <value>
                <fullName>LATAM</fullName>
                <isActive>false</isActive>
                <label>LATAM</label>
            </value>
            <value>
                <fullName>Land</fullName>
                <isActive>false</isActive>
                <label>Land</label>
            </value>
            <value>
                <fullName>Mid Market</fullName>
                <isActive>false</isActive>
                <label>Mid Market</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Account_Stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
        <default>true</default>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <customValue>
        <fullName>Former</fullName>
    </customValue>
    <masterLabel>Account Stages</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/OpportunityPipelineConverterTest.cls
@isTest
public with sharing class OpportunityPipelineConverterTest {
  @TestSetup
  static void makeData() {
    User bdr = TestUserProvisioner.getNewUser();
    bdr.UserRoleId = [SELECT Id FROM UserRole WHERE Name = 'BDR' LIMIT 1].Id;
    bdr.LastName = 'OpportunityPipelineConverterTest';
    bdr.Division = 'Japan';
    bdr.Sub_Division__c = 'Korea';
    TestUserProvisioner.insertUsers(JSON.serialize(new List<User>{ bdr }));
  }

  @isTest
  static void testConvert() {
    User bdr = [
      SELECT Id
      FROM User
      WHERE LastName = 'OpportunityPipelineConverterTest'
      LIMIT 1
    ];

    List<Account> accounts = AccountTestFactory.createCustomers(2);

    List<Opportunity> opps = new List<Opportunity>{
      new Opportunity(
        AccountId = accounts[0].Id,
        RecordTypeId = RecordTypeUtility.getId(
          Opportunity.getSObjectType(),
          'Lead'
        ),
        CloseDate = Date.today().addYears(1),
        StageName = '0 - Meeting Pending',
        Contract_Type__c = 'Standard Term Contract',
        OwnerId = bdr.Id
      ),
      new Opportunity(
        AccountId = accounts[1].Id,
        RecordTypeId = RecordTypeUtility.getId(
          Opportunity.getSObjectType(),
          'Lead'
        ),
        CloseDate = Date.today().addYears(1),
        StageName = '0 - Meeting Pending',
        Contract_Type__c = 'Standard Term Contract',
        OwnerId = bdr.Id
      )
    };
    insert opps;

    for (Opportunity opp : opps) {
      opp.StageName = '0 - Meeting Scheduled';
    }
    update opps;

    for (Opportunity opp : opps) {
      opp.StageName = '0 - Meeting Occurred';
    }
    update opps;

    opps = [
      SELECT Id, Convert_to_Pipeline__c
      FROM Opportunity
      WHERE Id IN :opps
    ];

    for (Opportunity opp : opps) {
      opp.Convert_to_Pipeline__c = true;
    }

    Test.startTest();
    update opps;
    Test.stopTest();

    opps = [
      SELECT
        Id,
        Account.Account_Stage__c,
        Account.Name,
        RecordType.Name,
        StageName
      FROM Opportunity
      WHERE Id IN :opps
    ];
    for (Opportunity opp : opps) {
      switch on opp.Account.Account_Stage__c {
        when 'Customer' {
          System.assertEquals(
            'Add-On',
            opp.RecordType.Name,
            'Incorrect Record Type for Customer: ' + opp.Account.Name
          );
        }
        when else {
          System.assertEquals(
            'New Business',
            opp.RecordType.Name,
            'Incorrect Record Type for Prospect: ' + opp.Account.Name
          );
        }
      }

      System.assertEquals(
        '1 - Discovery',
        opp.StageName,
        'Stage was incorrectly set for converted Opportunity.'
      );
    }
  }
}