unpackaged/main/default/objects/Account/fields/Account_Stage__c.field-meta.xml
<CustomField>
    <fullName>Account_Stage__c</fullName>
    <label>Account Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Stages</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Live_Event_Support_Hours_used__c.field-meta.xml
<CustomField>
    <fullName>Live_Event_Support_Hours_used__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>The total number of Live Coverage Hours used for successfully completed Live Event Coverage Requests.</inlineHelpText>
    <label>Live Event Support Hours used</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Total_Live_Event_Support_hours_available__c.field-meta.xml
<CustomField>
    <fullName>Total_Live_Event_Support_hours_available__c</fullName>
    <formula>Total_Live_Event_Support_hours_sold__c - Total_Live_Event_Support_hours_booked__c - Live_Event_Support_Hours_used__c + Manual_Live_Event_Support__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Live Event Support Hours available</inlineHelpText>
    <label>Total Live Event Support hours available</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Total_Live_Event_Support_hours_booked__c.field-meta.xml
<CustomField>
    <fullName>Total_Live_Event_Support_hours_booked__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Live Event Support hours booked</description>
    <inlineHelpText>Total Live Event Support Hours requested and pending coverage assignment.</inlineHelpText>
    <label>Total Live Event Support hours booked</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Total_Live_Event_Support_hours_sold__c.field-meta.xml
<CustomField>
    <fullName>Total_Live_Event_Support_hours_sold__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Live Event Support hours sold</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Total_Live_Support_Events__c.field-meta.xml
<CustomField>
    <fullName>Total_Live_Support_Events__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total number of Live Events done with the Support</inlineHelpText>
    <label>Total Live Support Events</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Total_Remaining_Hours_to__c.field-meta.xml
<CustomField>
    <fullName>Total_Remaining_Hours_to__c</fullName>
    <inlineHelpText>The Live Event Support Hours requested in total are awaiting assignment for coverage.</inlineHelpText>
    <label>Total Remaining Hours pending to cover</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>for customer &amp; Prospect</description>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Account_Stage__c.field-meta.xml
<CustomField>
    <fullName>Account_Stage__c</fullName>
    <formula>Account.Stage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Stage</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage__c/Live_Event_Coverage__c.object-meta.xml
<CustomObject>
    <label>Live Event Coverage</label>
    <nameField>
        <displayFormat>LE - {0}</displayFormat>
        <label>Live Event Coverage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Live Event Coverage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Live_Event_Coverage__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Live Event Coverage</relationshipLabel>
    <relationshipName>Live_Event_Coverage</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage__c/fields/Communication_Channel__c.field-meta.xml
<CustomField>
    <fullName>Communication_Channel__c</fullName>
    <label>Communication Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Slack (Brightcove&#39;s Workspace)</fullName>
            </value>
            <value>
                <fullName>Gotomeeting (Brightcove&#39;s account)</fullName>
            </value>
            <value>
                <fullName>Customer will provide access to their Instant Messanger</fullName>
            </value>
            <value>
                <fullName>Customer will provide a phone bridge</fullName>
            </value>
            <value>
                <fullName>Not yet defined</fullName>
            </value>
            <value>
                <fullName>Salesforce Case/Emails</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage__c/fields/Event_Point_Of_Contact__c.field-meta.xml
<CustomField>
    <fullName>Event_Point_Of_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The primary person to contact during the event coverage &amp; to setup a time to test.</inlineHelpText>
    <label>Event Main Point Of Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Live Event Coverage</relationshipLabel>
    <relationshipName>Live_Event_Coverage</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage__c/fields/Full_Coverage_duration_hours__c.field-meta.xml
<CustomField>
    <fullName>Full_Coverage_duration_hours__c</fullName>
    <description>It replaced the &#39;Full Event duration (hours)&#39; field</description>
    <formula>(DATETIMEVALUE( TEXT(Event_End_Date__c)&amp;&quot; &quot;&amp; LEFT(TEXT(Event_End_Time__c),8)) 
- 
DATETIMEVALUE(TEXT(Event_Start_Date__c)&amp;&quot; &quot;&amp; LEFT(TEXT(Event_Start_Time__c),8)))*24</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Coverage duration (hours)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage__c/fields/Hours_Covered_So_Far__c.field-meta.xml
<CustomField>
    <fullName>Hours_Covered_So_Far__c</fullName>
    <inlineHelpText>This is the sum of the timings that have been created on this object.</inlineHelpText>
    <label>Hours Covered So Far</label>
    <summarizedField>Live_Event_Coverage_Timing__c.Coverage_Duration_hours__c</summarizedField>
    <summaryFilterItems>
        <field>Live_Event_Coverage_Timing__c.Type__c</field>
        <operation>equals</operation>
        <value>Event</value>
    </summaryFilterItems>
    <summaryForeignKey>Live_Event_Coverage_Timing__c.CoverageLink__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage__c/fields/Live_Event_Category__c.field-meta.xml
<CustomField>
    <fullName>Live_Event_Category__c</fullName>
    <description>Live Event Category pick the kind of live event</description>
    <label>Live Event Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commerce - Auction</fullName>
            </value>
            <value>
                <fullName>Commerce - Product Launch</fullName>
            </value>
            <value>
                <fullName>Conference - Sales</fullName>
            </value>
            <value>
                <fullName>Conference - Religion</fullName>
            </value>
            <value>
                <fullName>Conference - Education</fullName>
            </value>
            <value>
                <fullName>Conference - Technology</fullName>
            </value>
            <value>
                <fullName>Conference - Other</fullName>
            </value>
            <value>
                <fullName>Corporate Meetings</fullName>
            </value>
            <value>
                <fullName>Entertainment - Sports</fullName>
            </value>
            <value>
                <fullName>Entertainment - eSports</fullName>
            </value>
            <value>
                <fullName>Entertainment - Music</fullName>
            </value>
            <value>
                <fullName>Entertainment - Cinema</fullName>
            </value>
            <value>
                <fullName>Entertainment - Fashion</fullName>
            </value>
            <value>
                <fullName>Entertainment - Other</fullName>
            </value>
            <value>
                <fullName>Government - Meeting/Townhall</fullName>
            </value>
            <value>
                <fullName>NGO - Meeting</fullName>
            </value>
            <value>
                <fullName>News - Politics</fullName>
            </value>
            <value>
                <fullName>News - Event</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage__c/fields/Number_of_concurrent_streams__c.field-meta.xml
<CustomField>
    <fullName>Number_of_concurrent_streams__c</fullName>
    <description>How many concurrent live jobs is the customer expecting us to monitor during the event?</description>
    <inlineHelpText>How many concurrent live jobs is the customer expecting us to monitor during the event?</inlineHelpText>
    <label>Number of concurrent streams</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage__c/fields/Publisher_ID__c.field-meta.xml
<CustomField>
    <fullName>Publisher_ID__c</fullName>
    <inlineHelpText>The specific Publisher ID hosting the event under the &quot;Account&quot; field.</inlineHelpText>
    <label>Publisher ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage__c/fields/Remaining_Hours_to_cover__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Hours_to_cover__c</fullName>
    <formula>Full_Coverage_duration_hours__c - Hours_Covered_So_Far__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Hours to cover</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Used by Customer Support for Event Coverage Tracking.</inlineHelpText>
    <label>Coverage Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Checking details with AM</fullName>
            </value>
            <value>
                <fullName>Pending - CS - Assigning Resource</fullName>
            </value>
            <value>
                <fullName>Pending - CS - Resource Booked</fullName>
            </value>
            <value>
                <fullName>Closed - Rejected</fullName>
            </value>
            <value>
                <fullName>Closed - Completed [Business Hours]</fullName>
            </value>
            <value>
                <fullName>Closed - Completed [Off-Hours]</fullName>
            </value>
            <value>
                <fullName>Closed - Completed [Mixed]</fullName>
            </value>
            <value>
                <fullName>Need To Close</fullName>
            </value>
            <value>
                <fullName>Closed - Duplicate</fullName>
            </value>
            <value>
                <fullName>Open - Automated Monitoring</fullName>
            </value>
            <value>
                <fullName>Closed - Automated Monitoring</fullName>
            </value>
            <value>
                <fullName>Open - Premium Monitoring</fullName>
            </value>
            <value>
                <fullName>Closed - Premium Monitoring</fullName>
            </value>
            <value>
                <fullName>Pending - ProBono Event Rejected</fullName>
            </value>
            <value>
                <fullName>Closed - Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage_Timing__c/Live_Event_Coverage_Timing__c.object-meta.xml
<CustomObject>
    <label>Live Event Coverage Timing</label>
    <nameField>
        <displayFormat>LEC-{0}</displayFormat>
        <label>Timing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Live Event Coverage Timings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Live_Event_Coverage_Timing__c/fields/Coverage_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coverage Engineer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Live_Event_Coverage_Timings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage_Timing__c/fields/CoverageLink__c.field-meta.xml
<CustomField>
    <fullName>CoverageLink__c</fullName>
    <label>Live Event Coverage</label>
    <referenceTo>Live_Event_Coverage__c</referenceTo>
    <relationshipLabel>Live Event Coverage Timings</relationshipLabel>
    <relationshipName>Live_Event_Coverage_Timings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage_Timing__c/fields/End_of_Coverage__c.field-meta.xml
<CustomField>
    <fullName>End_of_Coverage__c</fullName>
    <label>End of Coverage</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage_Timing__c/fields/Off_Hours_Covered__c.field-meta.xml
<CustomField>
    <fullName>Off_Hours_Covered__c</fullName>
    <label>#Off Hours Covered</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage_Timing__c/fields/Start_of_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Start_of_Coverage__c</fullName>
    <label>Start of Coverage</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/globalValueSets/Account_Stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
        <default>true</default>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <customValue>
        <fullName>Former</fullName>
    </customValue>
    <masterLabel>Account Stages</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/LiveEventCoverageHandlerTest.cls
@isTest(isparallel=true)
private class LiveEventCoverageHandlerTest {
  @TestSetup
  private static void makeData() {
    createAccount();
  }

  @isTest
  private static void testCreateUpdateLes() {
    Account accountBEFORECreateLe = [
      SELECT
        Id,
        Total_Live_Event_Support_hours_sold__c,
        Total_Live_Event_Support_hours_booked__c,
        Total_Remaining_Hours_to__c,
        Total_Live_Event_Support_hours_available__c,
        Live_Event_Support_Hours_used__c
      FROM Account
      WHERE NAME = 'UATTestLiveEvent'
      LIMIT 1
    ];

    Test.startTest();
    createNewLEs();
    Test.stopTest();

    Account accountAFTERCreateLe = [
      SELECT
        Id,
        Total_Live_Event_Support_hours_sold__c,
        Total_Live_Event_Support_hours_booked__c,
        Total_Remaining_Hours_to__c,
        Total_Live_Event_Support_hours_available__c,
        Live_Event_Support_Hours_used__c
      FROM Account
      WHERE NAME = 'UATTestLiveEvent'
      LIMIT 1
    ];

    List<AggregateResult> results = [
      SELECT
        Account__c,
        SUM(Full_Coverage_duration_hours__c) hoursBooked,
        SUM(Remaining_Hours_to_cover__c) hoursRemaining,
        SUM(Hours_Covered_So_Far__c) hoursUsed
      FROM Live_Event_Coverage__c
      WHERE
        Account__c = :accountAFTERCreateLe.ID
        AND (NOT Status__c LIKE '%Completed%')
      GROUP BY Account__c
    ];

    Map<Id, Decimal> accountBookedHours = new Map<Id, Decimal>();
    Map<Id, Decimal> accountRemainingHours = new Map<Id, Decimal>();

    for (AggregateResult result : results) {
      accountBookedHours.put(
        (Id) result.get('Account__c'),
        (Decimal) result.get('hoursBooked')
      );
      accountRemainingHours.put(
        (Id) result.get('Account__c'),
        (Decimal) result.get('hoursBooked')
      );
    }

    System.assertEquals(
      accountAFTERCreateLe.Total_Live_Event_Support_hours_booked__c,
      accountBEFORECreateLe.Total_Live_Event_Support_hours_booked__c +
      accountBookedHours.get(accountAFTERCreateLe.Id),
      'Account: Total Live Event Hours Booked error'
    );

    System.assertEquals(
      accountAFTERCreateLe.Total_Remaining_Hours_to__c,
      accountRemainingHours.get(accountAFTERCreateLe.Id),
      'Account: Total Live Event Hours Remaining error'
    );

    System.assertEquals(
      accountAFTERCreateLe.Total_Live_Event_Support_hours_available__c,
      accountBEFORECreateLe.Total_Live_Event_Support_hours_available__c -
      accountBookedHours.get(accountAFTERCreateLe.Id),
      'Account: Total Live Hours Available error 2'
    );

    System.assertEquals(
      accountAFTERCreateLe.Total_Live_Event_Support_hours_available__c,
      accountAFTERCreateLe.Total_Live_Event_Support_hours_sold__c -
        accountAFTERCreateLe.Total_Live_Event_Support_hours_booked__c -
        accountAFTERCreateLe.Live_Event_Support_Hours_used__c,
      'Account: Total Live Event Hours Available error'
    );
    System.assertEquals(
      accountAFTERCreateLe.Live_Event_Support_Hours_used__c,
      accountBEFORECreateLe.Live_Event_Support_Hours_used__c,
      'Account: Total Live Event hours USED error on creation of LEs'
    );
  }
  @istest
  private static void testCompleteLEs() {
    List<String> qualifiedStatuses = new List<String>{
      'Closed - Completed [Business Hours]',
      'Closed - Completed [Off-Hours]',
      'Closed - Completed [Mixed]'
    };

    createNewLEs();

    Account accountBEFORE = [
      SELECT
        Id,
        Total_Live_Event_Support_hours_sold__c,
        Total_Live_Event_Support_hours_booked__c,
        Total_Remaining_Hours_to__c,
        Total_Live_Event_Support_hours_available__c,
        Total_Live_Support_Events__c,
        Live_Event_Support_Hours_used__c
      FROM Account
      WHERE NAME = 'UATTestLiveEvent'
      LIMIT 1
    ];

    test.startTest();
    completeLEs();
    test.stopTest();

    Account accountAFTER = [
      SELECT
        Id,
        Total_Live_Event_Support_hours_sold__c,
        Total_Live_Event_Support_hours_booked__c,
        Total_Live_Support_Events__c,
        Total_Remaining_Hours_to__c,
        Total_Live_Event_Support_hours_available__c,
        Live_Event_Support_Hours_used__c
      FROM Account
      WHERE NAME = 'UATTestLiveEvent'
      LIMIT 1
    ];

    List<AggregateResult> results = [
      SELECT
        COUNT(Id) nEvents,
        Account__c,
        SUM(Full_Coverage_duration_hours__c) hoursBooked,
        SUM(Hours_Covered_So_Far__c) hoursUsed
      FROM Live_Event_Coverage__c
      WHERE Account__c = :accountAFTER.Id AND Status__c IN :qualifiedStatuses
      GROUP BY Account__c
    ];

    Map<Id, Decimal> accountNEvents = new Map<Id, Decimal>();
    Map<Id, Decimal> accountHoursBooked = new Map<Id, Decimal>();
    Map<Id, Decimal> accountHoursUsed = new Map<Id, Decimal>();

    for (AggregateResult result : results) {
      accountNEvents.put(
        (Id) result.get('Account__c'),
        (Decimal) result.get('nevents')
      );
      accountHoursBooked.put(
        (Id) result.get('Account__c'),
        (Decimal) result.get('hoursBooked')
      );
      accountHoursUsed.put(
        (Id) result.get('Account__c'),
        (Decimal) result.get('hoursUsed')
      );
    }

    System.assertEquals(
      accountAFTER.Total_Live_Support_Events__c,
      accountNEvents.get(accountAFTER.Id),
      'Account Closed LEs: Number of Completed event calculation error'
    );

    System.assert(
      accountAFTER.Total_Live_Support_Events__c >
      accountBEFORE.Total_Live_Support_Events__c,
      'Account Closed LEs: Number of Completed event calculation error'
    );

    System.assertEquals(
      accountAFTER.Total_Live_Event_Support_hours_available__c,
      accountAFTER.Total_Live_Event_Support_hours_sold__c -
        accountAFTER.Total_Live_Event_Support_hours_booked__c -
        AccountAFTER.Live_Event_Support_Hours_used__c,
      'Account Closed LEs: Number of Total Live Event hours available error'
    );
  }

  private static void createAccount() {
    Account customerAccount = AccountTestFactory.getCustomer();
    customerAccount.Name = 'UATTestLiveEvent';
    customerAccount.Account_Stage__c = 'Customer';
    customerAccount.Total_Live_Event_Support_hours_sold__c = 10;

    insert customerAccount;

    ContactTestFactory.createContact(customerAccount);
  }

  private static void completeLEs() {
    Id accountRecordId = [
      SELECT Id
      FROM Account
      WHERE name = 'UATTestLiveEvent'
      LIMIT 1
    ]
    .Id;

    Live_Event_Coverage__c lErecord = [
      SELECT Id, Status__c
      FROM Live_Event_Coverage__c
      WHERE Account__c = :accountRecordId AND (NOT Status__c LIKE '%Completed%')
      LIMIT 1
    ];

    User nOCEng = [
      SELECT Id
      FROM User
      WHERE isActive = TRUE AND UserRole.name = 'Technical Support Rep'
      LIMIT 1
    ];

    Live_Event_Coverage_Timing__c lEtiming = new Live_Event_Coverage_Timing__c(
      Off_Hours_Covered__c = 0,
      CoverageLink__c = lErecord.Id,
      Coverage_Engineer__c = nOCEng.Id,
      Start_of_Coverage__c = Datetime.newInstance(2024, 2, 1, 10, 30, 0),
      End_of_Coverage__c = Datetime.newInstance(2024, 2, 1, 11, 30, 0)
    );

    insert lEtiming;

    lErecord.Status__c = 'Closed - Completed [Mixed]';
    update lErecord;
  }

  private static void createNEWLEs() {
    Id accountRecord = [
      SELECT Id
      FROM Account
      WHERE name = 'UATTestLiveEvent'
      LIMIT 1
    ]
    .Id;

    Contact contactRecord = [
      SELECT Id
      FROM Contact
      WHERE AccountId = :accountRecord
      LIMIT 1
    ];

    Id liveEventCoverageRecordTypeId = RecordTypeUtility.getId(
      Live_Event_Coverage__c.getSObjectType(),
      'Live Event Support'
    );

    Live_Event_Coverage__c lErecord = new Live_Event_Coverage__c(
      Event_Point_Of_Contact__c = contactRecord.Id,
      Account__c = accountRecord,
      RecordTypeId = liveEventCoverageRecordTypeId,
      Publisher_ID__c = '11111',
      Communication_Channel__c = 'Not yet defined',
      Live_Event_Category__c = 'Other',
      Number_of_concurrent_streams__c = 1,
      MAX_CCU_Estimated__c = 1,
      High_Profile__c = 'No',
      Live_Product__c = 'Brightcove Live',
      Timezone__c = '(GMT-10:00) Hawaii',
      Status__c = 'New',
      BGS_Managed_Event__c = 'No',
      Test_Start_Time__c = Time.newInstance(10, 0, 0, 0),
      Test_End_Time__c = Time.newInstance(10, 30, 0, 0),
      Test_Date__c = Date.today(),
      Event_Start_Date__c = Date.today(),
      Event_End_Date__c = Date.today(),
      Event_Start_Time__c = Time.newInstance(9, 0, 0, 0),
      Event_End_Time__c = Time.newInstance(11, 0, 0, 0)
    );
    Live_Event_Coverage__c lErecord2 = new Live_Event_Coverage__c(
      Event_Point_Of_Contact__c = contactRecord.Id,
      Account__c = accountRecord,
      RecordTypeId = liveEventCoverageRecordTypeId,
      Status__c = 'New',
      Publisher_ID__c = '11111',
      Communication_Channel__c = 'Not yet defined',
      Live_Event_Category__c = 'Other',
      Number_of_concurrent_streams__c = 1,
      MAX_CCU_Estimated__c = 1,
      High_Profile__c = 'No',
      Live_Product__c = 'Brightcove Live',
      Timezone__c = '(GMT-10:00) Hawaii',
      BGS_Managed_Event__c = 'No',
      Test_Start_Time__c = Time.newInstance(10, 0, 0, 0),
      Test_End_Time__c = Time.newInstance(10, 30, 0, 0),
      Test_Date__c = Date.today(),
      Event_Start_Date__c = Date.today(),
      Event_End_Date__c = Date.today(),
      Event_Start_Time__c = Time.newInstance(9, 0, 0, 0),
      Event_End_Time__c = Time.newInstance(13, 0, 0, 0)
    );

    List<Live_Event_Coverage__c> lEList = new List<Live_Event_Coverage__c>{
      lErecord,
      lErecord2
    };
    insert lEList;
  }
}