unpackaged/main/default/objects/Account/fields/Customer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Customer_Tier__c</fullName>
    <description>It marks the tiering based on the revenue bucket.</description>
    <label>Customer Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
            <value>
                <fullName>Tier 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Naming_Rights__c.field-meta.xml
<CustomField>
    <fullName>Naming_Rights__c</fullName>
    <label>Naming Rights</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard Naming Rights</fullName>
            </value>
            <value>
                <fullName>Earnings Call Only</fullName>
            </value>
            <value>
                <fullName>No Rights/Custom Language</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <isActive>false</isActive>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
                <isActive>false</isActive>
                <label>Yes</label>
            </value>
            <value>
                <fullName>Yes with Consent</fullName>
                <isActive>false</isActive>
                <label>Yes with Consent</label>
            </value>
            <value>
                <fullName>Yes with Restriction</fullName>
                <isActive>false</isActive>
                <label>Yes with Restriction</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Partner_Category__c.field-meta.xml
<CustomField>
    <fullName>Partner_Category__c</fullName>
    <label>Partner Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Advertising</fullName>
            </value>
            <value>
                <fullName>AI &amp; Video Enrichment</fullName>
            </value>
            <value>
                <fullName>Analytics</fullName>
            </value>
            <value>
                <fullName>App Development</fullName>
            </value>
            <value>
                <fullName>Audience Measurement</fullName>
            </value>
            <value>
                <fullName>Broadcasting solution</fullName>
            </value>
            <value>
                <fullName>Cloud Storage</fullName>
            </value>
            <value>
                <fullName>Consent Management</fullName>
            </value>
            <value>
                <fullName>Consulting company</fullName>
            </value>
            <value>
                <fullName>Content and Social Syndication</fullName>
            </value>
            <value>
                <fullName>Content Management System</fullName>
            </value>
            <value>
                <fullName>Digital Agency</fullName>
            </value>
            <value>
                <fullName>DRM and Content Protection</fullName>
            </value>
            <value>
                <fullName>eCommerce Platform</fullName>
            </value>
            <value>
                <fullName>eLearning Solutions</fullName>
            </value>
            <value>
                <fullName>Enterprise Content Delivery</fullName>
            </value>
            <value>
                <fullName>Event Management Platform</fullName>
            </value>
            <value>
                <fullName>FAST</fullName>
            </value>
            <value>
                <fullName>Global Systems Integrator</fullName>
            </value>
            <value>
                <fullName>Interactive Video</fullName>
            </value>
            <value>
                <fullName>IT Services Company</fullName>
            </value>
            <value>
                <fullName>Live Streaming Hardware/Software/Services</fullName>
            </value>
            <value>
                <fullName>MAP</fullName>
            </value>
            <value>
                <fullName>Marketing Agency</fullName>
            </value>
            <value>
                <fullName>Marketing Automation Platform</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>OTT Platforms and Extensions</fullName>
            </value>
            <value>
                <fullName>Paywall and Payment Gateways</fullName>
            </value>
            <value>
                <fullName>Recommendations</fullName>
            </value>
            <value>
                <fullName>Social Media Management</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Partner_Type__c.field-meta.xml
<CustomField>
    <fullName>Partner_Type__c</fullName>
    <label>Partner Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Marketplace Partner</fullName>
            </value>
            <value>
                <fullName>Channel Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>for customer &amp; Prospect</description>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>For Partner accounts</description>
    <label>Partner</label>
</RecordType>

unpackaged/main/default/classes/AccountTestFactory.cls
@isTest
public with sharing class AccountTestFactory {
  static Database.DMLOptions getDmlOption() {
    Database.DMLOptions dmlOption = new Database.DMLOptions();
    dmlOption.DuplicateRuleHeader.AllowSave = true;
    return dmlOption;
  }

  public static Account getCustomer() {
    return getCustomers(1)[0];
  }

  public static List<Account> getCustomers(Integer count) {
    List<Account> customers = new List<Account>();
    for (Integer i = 0; i < count; i++) {
      String guid = GuidUtility.generateGuid();
      customers.add(
        new Account(
          Name = 'AccountTestFactory' + guid,
          Naming_Rights__c = Account.Naming_Rights__c.getDescribe()
              .getPicklistValues()[0]
            .getValue(),
          RecordTypeId = RecordTypeUtility.getId(
            Account.getSObjectType(),
            'Customer'
          ),
          GUID__c = guid,
          BillingCountryCode = 'US',
          BillingCity = 'Test City',
          BillingPostalCode = '41234',
          BillingState = 'New York',
          BillingStreet = '123 Main st',
          Customer_Tier__c = Account.Customer_Tier__c.getDescribe()
              .getPicklistValues()[0]
            .getValue()
        )
      );
    }
    return customers;
  }

  public static Account createCustomer() {
    return createCustomers(1)[0];
  }

  public static List<Account> createCustomers(Integer count) {
    List<Account> customers = getCustomers(count);
    Database.insert(customers, getDmlOption());
    return customers;
  }

  public static Account getPartner() {
    return getPartners(1)[0];
  }

  public static List<Account> getPartners(Integer count) {
    List<Account> partners = new List<Account>();
    for (Integer i = 0; i < count; i++) {
      partners.add(
        new Account(
          Name = 'AccountTestFactory Partner ' + String.valueOf(i + 1),
          RecordTypeId = RecordTypeUtility.getId(
            Account.getSObjectType(),
            'Partner'
          ),
          Website = 'www.dummytesterthisisfakebeepbop.cob',
          Partner_Type__c = Account.Partner_Type__c.getDescribe()
              .getPicklistValues()[0]
            .getValue(),
          Partner_Category__c = Account.Partner_Category__c.getDescribe()
              .getPicklistValues()[0]
            .getValue(),
          BillingCountryCode = 'US',
          BillingCity = 'Test City',
          BillingPostalCode = '41234',
          BillingState = 'New York',
          BillingStreet = '123 Main st'
        )
      );
    }
    return partners;
  }

  public static List<Account> createPartners(Integer count) {
    List<Account> partners = getPartners(count);
    Database.insert(partners);
    return partners;
  }

  public static Account createPartner() {
    return createPartners(1)[0];
  }
}