unpackaged/main/default/objects/Account/fields/Email_Domain_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain_Name__c</fullName>
    <label>Email Domain Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/Brightcove_Account__c.object-meta.xml
<CustomObject>
    <label>Brightcove Account</label>
    <nameField>
        <label>Brightcove Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brightcove Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brightcove Account</relationshipLabel>
    <relationshipName>Brightcove_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Brightcove_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Brightcove_Account_Id__c</fullName>
    <description>The Pub ID of the Brightcove account&#39;s Id in our own database. Updated via sync from origin-services account.</description>
    <externalId>true</externalId>
    <inlineHelpText>The Pub ID of the Brightcove account&#39;s Id in our own database. Updated via sync from origin-services account.</inlineHelpText>
    <label>Brightcove Account Id</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain__c</fullName>
    <formula>RIGHT(Email_Address__c, (LEN(Email_Address__c)-FIND(&#39;@&#39;, Email_Address__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email Domain</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/BCAccountCustomerAccountLookupTest.cls
@isTest(isparallel=true)
public with sharing class BCAccountCustomerAccountLookupTest {
  @TestSetup
  static void makeData() {
    Account account = AccountTestFactory.getCustomer();
    account.Name = 'BCAccountCustomerAccountLookupTest';
    account.Email_Domain_Name__c = 'BCAccountCustomerAccountLookupTest.com';
    insert account;
  }

  @isTest
  static void testLookup() {
    Account expectedAccount = [
      SELECT Id
      FROM Account
      WHERE Email_Domain_Name__C = 'BCAccountCustomerAccountLookupTest.com'
      LIMIT 1
    ];
    Brightcove_Account__c brightcoveAccount = new Brightcove_Account__c(
      Brightcove_Account_Id__c = '12345',
      Email_Address__c = 'mhigel@bcAccountCustomerAccountLookupTest.com'
    );
    insert brightcoveAccount;

    brightcoveAccount = [
      SELECT Id, Account__c, Account__r.Email_Domain_Name__c, Email_Domain__c
      FROM Brightcove_Account__c
      WHERE Id = :brightcoveAccount.Id
    ];

    System.assertEquals(
      expectedAccount.Id,
      brightcoveAccount.Account__c,
      'Brightcove Account not correctly related to Salesforce Account.'
    );
  }
}