unpackaged/main/default/objects/Account/fields/Email_Domain_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain_Name__c</fullName>
    <label>Email Domain Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/Brightcove_Account__c.object-meta.xml
<CustomObject>
    <label>Brightcove Account</label>
    <nameField>
        <label>Brightcove Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brightcove Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brightcove Account</relationshipLabel>
    <relationshipName>Brightcove_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Account_Profile__c.field-meta.xml
<CustomField>
    <fullName>Account_Profile__c</fullName>
    <label>Account Profile</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
                <default>true</default>
                <label>Trial</label>
            </value>
            <value>
                <fullName>CUSTOMER</fullName>
            </value>
            <value>
                <fullName>Solution Partner</fullName>
            </value>
            <value>
                <fullName>Technology Partner</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Brightcove_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Brightcove_Account_Id__c</fullName>
    <description>The Pub ID of the Brightcove account&#39;s Id in our own database. Updated via sync from origin-services account.</description>
    <externalId>true</externalId>
    <inlineHelpText>The Pub ID of the Brightcove account&#39;s Id in our own database. Updated via sync from origin-services account.</inlineHelpText>
    <label>Brightcove Account Id</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain__c</fullName>
    <formula>RIGHT(Email_Address__c, (LEN(Email_Address__c)-FIND(&#39;@&#39;, Email_Address__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email Domain</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/AccountDomainNameHandlerTest.cls
@isTest(isparallel=true)
public with sharing class AccountDomainNameHandlerTest {
  @TestSetup
  private static void makeData() {
    insert new Brightcove_Account__c(
      Brightcove_Account_Id__c = '12345',
      Email_Address__c = 'bcAccount@example.com',
      Account_Profile__c = 'Trial'
    );
  }

  @isTest
  private static void testOnInsert() {
    List<Brightcove_Account__c> bcAccounts = [
      SELECT Id, Account__c, Email_Domain__c
      FROM Brightcove_Account__c
      WHERE Email_Domain__c = 'example.com' AND Account__c = NULL
      LIMIT 1
    ];
    System.assert(
      !bcAccounts.isEmpty(),
      'No qualifying Brightcove Accounts were initialized.'
    );

    Account account = AccountTestFactory.createCustomer();

    account.Email_Domain_Name__c = 'example.com';

    Test.startTest();
    update account;
    Test.stopTest();

    bcAccounts = [
      SELECT Id, Account__c
      FROM Brightcove_Account__c
      WHERE Id IN :bcAccounts
    ];
    for (Brightcove_Account__C bcAccount : bcAccounts) {
      System.assertEquals(
        account.Id,
        bcAccount.Account__c,
        'Salesforce Account was not correctly related to the Brightcove Account.'
      );
    }
  }

  @isTest
  private static void testOnUpdate() {
    List<Brightcove_Account__c> bcAccounts = [
      SELECT Id, Account__c, Email_Domain__c
      FROM Brightcove_Account__c
      WHERE Email_Domain__c = 'example.com' AND Account__c = NULL
      LIMIT 1
    ];
    System.assert(
      !bcAccounts.isEmpty(),
      'No qualifying Brightcove Accounts were initialized.'
    );

    Account account = AccountTestFactory.createCustomer();

    account.Email_Domain_Name__c = 'example.com';

    Test.startTest();
    update account;
    Test.stopTest();

    bcAccounts = [
      SELECT Id, Account__c
      FROM Brightcove_Account__c
      WHERE Id IN :bcAccounts
    ];
    for (Brightcove_Account__C bcAccount : bcAccounts) {
      System.assertEquals(
        account.Id,
        bcAccount.Account__c,
        'Salesforce Account was not correctly related to the Brightcove Account.'
      );
    }
  }
}