unpackaged/main/default/objects/Account/fields/Email_Domain_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain_Name__c</fullName>
    <label>Email Domain Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Email_Address_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Address_Domain__c</fullName>
    <formula>RIGHT(Email, (LEN(Email)-FIND(&quot;@&quot;,Email)+1) )
/*RIGHT(Email,  FIND(&quot;@&quot;, Email)-1 )*/</formula>
    <label>Email Address Domain</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ContactAccountEmailDomainHandlerTest.cls
@isTest(isparallel=true)
public with sharing class ContactAccountEmailDomainHandlerTest {
  @TestSetup
  static void makeData() {
    AccountTestFactory.createCustomer();
  }

  @isTest
  private static void testSetEmailDomain() {
    Account account = [
      SELECT Id
      FROM Account
      WHERE Email_Domain_Name__c = NULL
      LIMIT 1
    ];
    Contact contact = ContactTestFactory.getContact(account);

    Test.startTest();
    insert contact;
    Test.stopTest();
    contact = [
      SELECT Id, Email_Address_Domain__c
      FROM Contact
      WHERE Id = :contact.Id
    ];
    account = [
      SELECT Id, Email_Domain_Name__c
      FROM Account
      WHERE Id = :account.Id
    ];

    System.assertEquals(
      contact.Email_Address_Domain__c,
      account.Email_Domain_Name__c,
      'Account Email Domain Name not correctly set from new Contact.'
    );
  }
}