unpackaged/main/default/objects/Account/fields/Email_Domain_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain_Name__c</fullName>
    <label>Email Domain Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/Brightcove_Account__c.object-meta.xml
<CustomObject>
    <label>Brightcove Account</label>
    <nameField>
        <label>Brightcove Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brightcove Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brightcove Account</relationshipLabel>
    <relationshipName>Brightcove_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain__c</fullName>
    <formula>RIGHT(Email_Address__c, (LEN(Email_Address__c)-FIND(&#39;@&#39;, Email_Address__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email Domain</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/AccountDomainNameHandler.cls
public with sharing class AccountDomainNameHandler extends DomainLogicHandler {
    private Map<String, Id> accountIdsByDomains = new Map<String, Id>();
    public override void check(SObject newObj) {
        Account newAccount = (Account) newObj;
        if (isQualified(newAccount)) {
            accountIdsByDomains.put(
                newAccount.Email_Domain_Name__c,
                newAccount.Id
            );
        }
    }

    public override void check(SObject newObj, SObject oldObj) {
        Account newAccount = (Account) newObj;
        Account oldAccount = (Account) oldObj;
        if (isQualified(newAccount, oldAccount)) {
            accountIdsByDomains.put(
                newAccount.Email_Domain_Name__c,
                newAccount.Id
            );
        }
    }

    public override void processRecords() {
        if (!accountIdsByDomains.isEmpty()) {
            List<Brightcove_Account__c> bcAccounts = [
                SELECT Id, Account__c, Email_Domain__c
                FROM Brightcove_Account__c
                WHERE
                    Account__c = NULL
                    AND Email_Domain__c IN :accountIdsByDomains.keySet()
            ];

            for (Brightcove_Account__c bcAccount : bcAccounts) {
                bcAccount.Account__c = accountIdsByDomains.get(
                    bcAccount.Email_Domain__c
                );
            }

            update bcAccounts;
        }
    }

    private Boolean isQualified(Account newAccount) {
        return newAccount.Email_Domain_Name__c != null;
    }

    private Boolean isQualified(Account newAccount, Account oldAccount) {
        return isQualified(newAccount) &&
            TriggerUtility.isChanged(
                newAccount,
                oldAccount,
                Account.Email_Domain_Name__c
            );
    }
}