unpackaged/main/default/objects/Account/fields/Live_Event_Support_Hours_used__c.field-meta.xml
<CustomField>
    <fullName>Live_Event_Support_Hours_used__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>The total number of Live Coverage Hours used for successfully completed Live Event Coverage Requests.</inlineHelpText>
    <label>Live Event Support Hours used</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Total_Live_Event_Support_hours_booked__c.field-meta.xml
<CustomField>
    <fullName>Total_Live_Event_Support_hours_booked__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Live Event Support hours booked</description>
    <inlineHelpText>Total Live Event Support Hours requested and pending coverage assignment.</inlineHelpText>
    <label>Total Live Event Support hours booked</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Total_Live_Support_Events__c.field-meta.xml
<CustomField>
    <fullName>Total_Live_Support_Events__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total number of Live Events done with the Support</inlineHelpText>
    <label>Total Live Support Events</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Total_Remaining_Hours_to__c.field-meta.xml
<CustomField>
    <fullName>Total_Remaining_Hours_to__c</fullName>
    <inlineHelpText>The Live Event Support Hours requested in total are awaiting assignment for coverage.</inlineHelpText>
    <label>Total Remaining Hours pending to cover</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage__c/Live_Event_Coverage__c.object-meta.xml
<CustomObject>
    <label>Live Event Coverage</label>
    <nameField>
        <displayFormat>LE - {0}</displayFormat>
        <label>Live Event Coverage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Live Event Coverage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Live_Event_Coverage__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Live Event Coverage</relationshipLabel>
    <relationshipName>Live_Event_Coverage</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage__c/fields/Full_Coverage_duration_hours__c.field-meta.xml
<CustomField>
    <fullName>Full_Coverage_duration_hours__c</fullName>
    <description>It replaced the &#39;Full Event duration (hours)&#39; field</description>
    <formula>(DATETIMEVALUE( TEXT(Event_End_Date__c)&amp;&quot; &quot;&amp; LEFT(TEXT(Event_End_Time__c),8)) 
- 
DATETIMEVALUE(TEXT(Event_Start_Date__c)&amp;&quot; &quot;&amp; LEFT(TEXT(Event_Start_Time__c),8)))*24</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Coverage duration (hours)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage__c/fields/Hours_Covered_So_Far__c.field-meta.xml
<CustomField>
    <fullName>Hours_Covered_So_Far__c</fullName>
    <inlineHelpText>This is the sum of the timings that have been created on this object.</inlineHelpText>
    <label>Hours Covered So Far</label>
    <summarizedField>Live_Event_Coverage_Timing__c.Coverage_Duration_hours__c</summarizedField>
    <summaryFilterItems>
        <field>Live_Event_Coverage_Timing__c.Type__c</field>
        <operation>equals</operation>
        <value>Event</value>
    </summaryFilterItems>
    <summaryForeignKey>Live_Event_Coverage_Timing__c.CoverageLink__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage__c/fields/Pro_bono__c.field-meta.xml
<CustomField>
    <fullName>Pro_bono__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Pro bono events require pre-approval from Finance and CS leadership. Before ticking this box, you need to start an email conversation with both teams as per process. Checking this box will prevent the coverage from subtracting hours from the Opportunity associated, so the customer won&#39;t be billed for it.</inlineHelpText>
    <label>Pro bono?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage__c/fields/Remaining_Hours_to_cover__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Hours_to_cover__c</fullName>
    <formula>Full_Coverage_duration_hours__c - Hours_Covered_So_Far__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Hours to cover</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Used by Customer Support for Event Coverage Tracking.</inlineHelpText>
    <label>Coverage Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Checking details with AM</fullName>
            </value>
            <value>
                <fullName>Pending - CS - Assigning Resource</fullName>
            </value>
            <value>
                <fullName>Pending - CS - Resource Booked</fullName>
            </value>
            <value>
                <fullName>Closed - Rejected</fullName>
            </value>
            <value>
                <fullName>Closed - Completed [Business Hours]</fullName>
            </value>
            <value>
                <fullName>Closed - Completed [Off-Hours]</fullName>
            </value>
            <value>
                <fullName>Closed - Completed [Mixed]</fullName>
            </value>
            <value>
                <fullName>Need To Close</fullName>
            </value>
            <value>
                <fullName>Closed - Duplicate</fullName>
            </value>
            <value>
                <fullName>Open - Automated Monitoring</fullName>
            </value>
            <value>
                <fullName>Closed - Automated Monitoring</fullName>
            </value>
            <value>
                <fullName>Open - Premium Monitoring</fullName>
            </value>
            <value>
                <fullName>Closed - Premium Monitoring</fullName>
            </value>
            <value>
                <fullName>Pending - ProBono Event Rejected</fullName>
            </value>
            <value>
                <fullName>Closed - Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/LiveEventCoverageHandler.cls
/**
 *  This trigger reacts to the creation and update of a Live_Event_Coverage__c record and recalculates
 *  the information about the number of live event hours available on the account
 *  SObject Live_Event_Coverage__c
 *  Event After_Insert, After_Update
 */

public with sharing class LiveEventCoverageHandler extends DomainLogicHandler {
  List<Id> accountIds = new List<Id>();
  Map<Id, Account> accounts = new Map<Id, Account>();

  public override void check(SObject newobj) {
    Live_Event_Coverage__c liveEventCoverage = (Live_Event_Coverage__c) newobj;

    if (isQualifiedRecordType(newobj)) {
      accountIds.add(liveEventCoverage.Account__c);
    }
  }

  public override void check(SObject newobj, SObject oldobj) {
    Live_Event_Coverage__c liveEventCoverage = (Live_Event_Coverage__c) newobj;
    if (isQualifiedRecordType(newobj)) {
      accountIds.add(liveEventCoverage.Account__c);
    }
  }

  public override void processRecords() {
    for (Id accountId : accountIds) {
      accounts.put(
        accountId,
        new Account(
          Id = accountId,
          Total_Live_Event_Support_hours_booked__c = 0,
          Total_Remaining_Hours_to__c = 0,
          Total_Live_Support_Events__c = 0,
          Live_Event_Support_Hours_used__c = 0
        )
      );
    }

    accountOpenLEsUpdate();
    accountCompletedLEsUpdate();
    update accounts.values();
  }

  private void accountOpenLEsUpdate() {
    List<String> unqualifiedStatuses = new List<String>{
      'Closed - Rejected',
      'Closed - Completed [Business Hours]',
      'Closed - Completed [Off-Hours]',
      'Closed - Completed [Mixed]'
    };

    List<AggregateResult> resultsBookedHoursToUpdate = [
      SELECT
        Account__c,
        SUM(Full_Coverage_duration_hours__c) totalBookedHours,
        SUM(Remaining_Hours_to_cover__c) pendingHours
      FROM Live_Event_Coverage__c
      WHERE
        Account__c = :accountIds
        AND Status__c NOT IN :unqualifiedStatuses
        AND Pro_Bono__c = FALSE
      GROUP BY Account__c
    ];

    for (AggregateResult results : resultsBookedHoursToUpdate) {
      Id accountId = (Id) results.get('Account__c');

      Account account = accounts.get(accountId);
      account.Total_Live_Event_Support_hours_booked__c = (Decimal) results.get(
        'totalBookedHours'
      );
      account.Total_Remaining_Hours_to__c = (Decimal) results.get(
        'pendingHours'
      );

      accounts.put(accountId, account);
    }
  }

  private void accountCompletedLEsUpdate() {
    List<String> qualifiedStatuses = new List<String>{
      'Closed - Completed [Business Hours]',
      'Closed - Completed [Off-Hours]',
      'Closed - Completed [Mixed]'
    };

    List<AggregateResult> resultsAccountNEventsToUpdate = [
      SELECT
        Count(Id) nEvents,
        SUM(Hours_Covered_So_Far__c) hoursUsed,
        Account__c
      FROM Live_Event_Coverage__c
      WHERE
        Account__c = :accountIds
        AND Status__c IN :qualifiedStatuses
        AND Status__c != 'Closed - Rejected'
        AND Pro_Bono__c = FALSE
      GROUP BY Account__c
    ];

    for (AggregateResult results : resultsAccountNEventsToUpdate) {
      Id accountId = (Id) results.get('Account__c');

      Account account = accounts.get(accountId);

      account.Total_Live_Support_Events__c = (Decimal) results.get('nEvents');
      account.Live_Event_Support_Hours_used__c = (Decimal) results.get(
        'hoursUsed'
      );

      accounts.put(accountId, account);
    }
  }

  private Boolean isQualifiedRecordType(SObject newObj) {
    return RecordTypeUtility.getName((Live_Event_Coverage__c) newObj)
      .equals('Live Event Support');
  }
}