unpackaged/main/default/objects/Account/fields/Partner_Type__c.field-meta.xml
<CustomField>
    <fullName>Partner_Type__c</fullName>
    <label>Partner Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Marketplace Partner</fullName>
            </value>
            <value>
                <fullName>Channel Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>for customer &amp; Prospect</description>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>For Partner accounts</description>
    <label>Partner</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Partner)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Partner_Type__c.field-meta.xml
<CustomField>
    <fullName>Partner_Type__c</fullName>
    <label>Partner Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Master License Partner</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Solution Partner</fullName>
            </value>
            <value>
                <fullName>Technology Partner</fullName>
            </value>
            <value>
                <fullName>Technology Partner - BC Reselles</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Partner_Relationship__c/Partner_Relationship__c.object-meta.xml
<CustomObject>
    <label>Partner Relationship</label>
    <nameField>
        <displayFormat>Partner-{0000}</displayFormat>
        <label>Partner Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Partner_Relationship__c/fields/Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Relationships</relationshipLabel>
    <relationshipName>Partner_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Partner_Relationship__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <label>Partner Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Relationships (Partner)</relationshipLabel>
    <relationshipName>Partner_Relationships1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Partner_Relationship__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Transactional</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
                <isActive>false</isActive>
                <label>OEM</label>
            </value>
            <value>
                <fullName>Referral Partner</fullName>
                <isActive>false</isActive>
                <label>Referral Partner</label>
            </value>
            <value>
                <fullName>Reseller</fullName>
                <isActive>false</isActive>
                <label>Reseller</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/OppPartnerRelationshipHandlerTest.cls
@isTest
public with sharing class OppPartnerRelationshipHandlerTest {
  @TestSetup
  static void testDataSetup() {
    AccountTestFactory.createPartners(3);
    AccountTestFactory.createCustomer();
  }

  @isTest
  static void testPartnerRelationship() {
    List<Account> accounts = [
      SELECT Id, Name
      FROM Account
      WHERE Name LIKE 'AccountTestFactory%'
      ORDER BY RecordType.Name
    ];
    Account customer = accounts[0];
    Account partner1 = accounts[1];
    Account partner2 = accounts[2];
    Account partner3 = accounts[3];

    List<Opportunity> opps = new List<Opportunity>{
      OpportunityTestFactory.getStage1Opp(customer.Id),
      OpportunityTestFactory.getStage1Opp(customer.Id),
      OpportunityTestFactory.getStage1Opp(customer.Id),
      OpportunityTestFactory.getStage1Opp(customer.Id)
    };
    opps[0].Partner__c = partner1.Id;
    opps[0].Partner_Type__c = 'Transactional';

    opps[1].Partner__c = partner2.Id;
    opps[1].Partner_Type__c = 'Technical';

    opps[2].Partner__c = partner2.Id;
    opps[2].Partner_Type__c = 'Transactional';

    insert opps;

    Test.startTest();

    List<Partner_Relationship__c> relationships = [
      SELECT Id, Partner_Account__r.Name, Type__c
      FROM Partner_Relationship__c
      WHERE Customer_Account__c = :customer.Id
      ORDER BY Partner_Account__r.Name ASC, Type__c ASC
    ];

    System.assertEquals(
      3,
      relationships.size(),
      'Incorrect number of Partner Relationship records created.'
    );

    System.assertEquals(
      partner1.Name,
      relationships[0].Partner_Account__r.Name,
      'Incorrect Partner assigned to Partner Relationship record'
    );
    System.assertEquals(
      'Transactional',
      relationships[0].Type__c,
      'Incorrect Type assigned to Partner Relationship record: ' +
      relationships[0].Type__c
    );

    System.assertEquals(
      partner2.Name,
      relationships[1].Partner_Account__r.Name,
      'Incorrect Partner assigned to Partner Relationship record'
    );
    System.assertEquals(
      'Transactional',
      relationships[1].Type__c,
      'Incorrect Type assigned to Partner Relationship record: ' +
      relationships[1].Type__c
    );

    System.assertEquals(
      partner2.Name,
      relationships[2].Partner_Account__r.Name,
      'Incorrect Partner assigned to Partner Relationship record'
    );
    System.assertEquals(
      'Technical',
      relationships[2].Type__c,
      'Incorrect Type assigned to Partner Relationship record: ' +
      relationships[2].Type__c
    );

    opps[0].Partner__c = partner3.Id;
    opps[0].Partner_Type__c = 'Transactional';
    opps[1].Partner__c = partner2.Id;
    opps[1].Partner_Type__c = 'Technical';
    opps[3].Partner__c = partner2.Id;
    opps[3].Partner_Type__c = 'Transactional';

    update opps;

    Test.stopTest();

    relationships = [
      SELECT Id, Type__c, Partner_Account__r.Name
      FROM Partner_Relationship__c
      WHERE Customer_Account__c = :customer.Id
      ORDER BY Partner_Account__r.Name ASC, Type__c ASC
    ];

    System.assertEquals(
      3,
      relationships.size(),
      'Incorrect number of Partner Relationship records created.'
    );

    System.assertEquals(
      partner2.Name,
      relationships[0].Partner_Account__r.Name,
      'Incorrect Partner assigned to Partner Relationship record'
    );
    System.assertEquals(
      'Transactional',
      relationships[0].Type__c,
      'Incorrect Partner Type assigned to Partner Relationship record'
    );

    System.assertEquals(
      partner2.Name,
      relationships[1].Partner_Account__r.Name,
      'Incorrect Partner assigned to Partner Relationship record'
    );
    System.assertEquals(
      'Technical',
      relationships[1].Type__c,
      'Incorrect Partner Type assigned to Partner Relationship record'
    );

    System.assertEquals(
      partner3.Name,
      relationships[2].Partner_Account__r.Name,
      'Incorrect Partner assigned to Partner Relationship record'
    );
    System.assertEquals(
      'Transactional',
      relationships[2].Type__c,
      'Incorrect Partner Type assigned to Partner Relationship record'
    );
  }
}