unpackaged/main/default/objects/Account/fields/Sales_Division__c.field-meta.xml
<CustomField>
    <fullName>Sales_Division__c</fullName>
    <label>Sales Division</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Sales_Division_Contact__c.field-meta.xml
<CustomField>
    <fullName>Sales_Division_Contact__c</fullName>
    <label>Sales Division (Contact)</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sales_Division__mdt/Sales_Division__mdt.object-meta.xml
<CustomObject>
    <description>Custom distribution of countries into Sales Division.
Created by Nubik - 2023</description>
    <label>Sales Division</label>
    <pluralLabel>Sales Divisions</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Sales_Division__mdt/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <label>CountryCode</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sales_Division__mdt/fields/Sales_Division__c.field-meta.xml
<CustomField>
    <fullName>Sales_Division__c</fullName>
    <label>Sales Division</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <default>true</default>
                <label>Americas</label>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA, A-L</fullName>
            </value>
            <value>
                <fullName>EMEA, M-Z</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/SalesDivisionAssignment.cls
public with sharing class SalesDivisionAssignment {
    public static Map<SObjectType, SObjectField> countryFieldMap = new Map<SObjectType, SObjectField>{
        Account.getSObjectType() => Account.BillingCountryCode,
        Contact.getSObjectType() => Contact.MailingCountryCode,
        Lead.getSObjectType() => Lead.CountryCode
    };

    static Map<String, String> salesDivisionMap = getSalesDivisionMap();
    static Map<SObjectType, SObjectField> salesDivisionFieldMap = new Map<SObjectType, SObjectField>{
        Account.getSObjectType() => Account.Sales_Division__c,
        Contact.getSObjectType() => Contact.Sales_Division_Contact__c,
        Lead.getSObjectType() => Lead.Sales_Division_Contact__c
    };

    public static void assign(SObject sobj) {
        String countryCode = (String) sobj.get(getCountryField(sobj));
        sobj.put(
            getSalesDivisionField(sobj),
            salesDivisionMap.get(countryCode)
        );
    }

    static Map<String, String> getSalesDivisionMap() {
        if (salesDivisionMap == null) {
            salesDivisionMap = new Map<String, String>();
            List<Sales_Division__mdt> salesDivisionMdts = [
                SELECT CountryCode__c, Sales_Division__c
                FROM Sales_Division__mdt
            ];
            for (Sales_Division__mdt salesDivisionMdt : salesDivisionMdts) {
                salesDivisionMap.put(
                    salesDivisionMdt.CountryCode__c,
                    salesDivisionMdt.Sales_Division__c
                );
            }
        }

        return salesDivisionMap;
    }

    static SObjectField getSalesDivisionField(SObject sobj) {
        return salesDivisionFieldMap.get(sobj.getSObjectType());
    }

    static SObjectField getCountryField(SObject sobj) {
        return countryFieldMap.get(sobj.getSObjectType());
    }
}