unpackaged/main/default/objects/Account/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Name</fullName>
            </value>
            <value>
                <fullName>Response</fullName>
            </value>
            <value>
                <fullName>Actionable Response</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Add_On_Type__c.field-meta.xml
<CustomField>
    <fullName>Add_On_Type__c</fullName>
    <label>Add-On Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pricing Uplift</fullName>
            </value>
            <value>
                <fullName>Exchange Rate Impact</fullName>
            </value>
            <value>
                <fullName>Cross-Sell</fullName>
            </value>
            <value>
                <fullName>Upsell</fullName>
            </value>
            <value>
                <fullName>Entitlements</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
                <isActive>false</isActive>
                <label>Upgrade</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <description>What type of opportunity is this?</description>
    <inlineHelpText>New Business = brand new logo

Upgrade = upgrading an Express customer to higher edition

Add-on = selling to existing customer

Renewal = existing deal renewed at end of its term

Early Renewal = existing deal renewed before current term is up</inlineHelpText>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Add-On</fullName>
            </value>
            <value>
                <fullName>Debook</fullName>
            </value>
            <value>
                <fullName>Early Renewal</fullName>
            </value>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Renewal Growth</fullName>
            </value>
            <value>
                <fullName>Services Record Type</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <businessProcess>Standard Sales Process</businessProcess>
    <description>System generated Opportunity used for renewing a Contract at the end of its term</description>
    <label>Renewal</label>
</RecordType>

unpackaged/main/default/classes/OpportunityClosedHandlerTest.cls
@isTest
public with sharing class OpportunityClosedHandlerTest {
  @TestSetup
  static void makeData() {
    TestUserProvisioner provisioner = new TestUserProvisioner(
      UserInfo.getUserId()
    );
    provisioner.setPermissionSetGroup('Sales Rep');
    provisioner.assignPermissions();

    List<Account> accounts = AccountTestFactory.getCustomers(2);
    accounts[0].Name = 'OpportunityClosedLostHandlerTest';
    accounts[1].Name = 'testRecyleContacts';
    insert accounts;
  }

  @isTest
  static void testRecyleContactsNewBus() {
    Account account = [
      SELECT Id
      FROM Account
      WHERE Name = 'OpportunityClosedLostHandlerTest'
      LIMIT 1
    ];

    Opportunity opp = OpportunityTestFactory.getStageZeroOpp();
    opp.Deal_Type__c = 'New Business';
    opp.AccountId = account.Id;
    insert opp;

    OpportunityTestFactory.disqualifyStageZeroOpp(opp);

    SBQQ.TriggerControl.disable();

    Test.startTest();
    update opp;
    Test.stopTest();

    Id contactId = opp.ContactId;

    Contact contact = [
      SELECT Id, Stage__c
      FROM Contact
      WHERE Id = :opp.ContactId
    ];

    System.assertEquals(
      'Recycled',
      contact.Stage__c,
      'Contact Stage was not set to "Recycled"'
    );
  }

  @isTest
  static void testRecyleContactsAddOn() {
    Account account = [
      SELECT Id
      FROM Account
      WHERE Name = 'OpportunityClosedLostHandlerTest'
      LIMIT 1
    ];

    Opportunity opp = OpportunityTestFactory.getStage1Opp(
      account.Id,
      RecordTypeUtility.getId(Opportunity.getSObjectType(), 'Add-On')
    );
    opp.Deal_Type__c = 'Add-On';
    opp.Add_On_Type__c = 'Upsell';

    upsert opp;
    OpportunityTestFactory.setStage2(opp);
    update opp;
    OpportunityTestFactory.setStage3(opp);
    update opp;
    OpportunityTestFactory.setStage4(opp);
    update opp;
    opp.StageName = 'Closed Lost';

    SBQQ.TriggerControl.disable();

    Test.startTest();
    update opp;
    Test.stopTest();

    Id contactId = opp.ContactId;

    Contact contact = [
      SELECT Id, Stage__c
      FROM Contact
      WHERE Id = :opp.ContactId
    ];

    System.assertEquals(
      'Recycled',
      contact.Stage__c,
      'Contact Stage was not set to "Recycled"'
    );
  }

  @isTest
  static void testRecyleContactsRenewalContactOpenOpp() {
    Account account1 = [
      SELECT Id
      FROM Account
      WHERE Name = 'OpportunityClosedLostHandlerTest'
      LIMIT 1
    ];

    Account account2 = [
      SELECT Id
      FROM Account
      WHERE Name = 'testRecyleContacts'
      LIMIT 1
    ];

    Opportunity opp = OpportunityTestFactory.getStage1Opp(
      account1.Id,
      RecordTypeUtility.getId(
        Opportunity.getSObjectType(),
        'Renewal Growth Add-on'
      )
    );
    opp.Deal_Type__c = 'Renewal Growth';
    opp.Add_On_Type__c = 'Upsell';

    upsert opp;
    OpportunityTestFactory.setStage2(opp);
    update opp;
    OpportunityTestFactory.setStage3(opp);
    update opp;
    OpportunityTestFactory.setStage4(opp);
    update opp;
    opp.StageName = 'Closed Lost';

    Contact newContact = ContactTestFactory.createContact(account2);

    Opportunity opp2 = OpportunityTestFactory.getStageZeroOpp();
    opp.AccountId = account2.Id;
    insert opp2;

    OpportunityContactRole newContactRole = new OpportunityContactRole();
    newContactRole.ContactId = newContact.Id;
    newContactRole.OpportunityId = opp.Id;
    insert newContactRole;

    SBQQ.TriggerControl.disable();

    Test.startTest();
    update opp;
    Test.stopTest();

    Id contactId = opp.ContactId;

    Contact contact = [
      SELECT Id, Stage__c
      FROM Contact
      WHERE Id = :opp.ContactId
    ];

    System.assertEquals(
      'Recycled',
      contact.Stage__c,
      'Contact Stage was not set to "Recycled"'
    );
    System.assertNotEquals(
      'Recycled',
      newcontact.Stage__c,
      'Contact Stage was set to "Recycled"'
    );
  }
}