unpackaged/main/default/objects/Account/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Name</fullName>
            </value>
            <value>
                <fullName>Response</fullName>
            </value>
            <value>
                <fullName>Actionable Response</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <description>What type of opportunity is this?</description>
    <inlineHelpText>New Business = brand new logo

Upgrade = upgrading an Express customer to higher edition

Add-on = selling to existing customer

Renewal = existing deal renewed at end of its term

Early Renewal = existing deal renewed before current term is up</inlineHelpText>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Add-On</fullName>
            </value>
            <value>
                <fullName>Debook</fullName>
            </value>
            <value>
                <fullName>Early Renewal</fullName>
            </value>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Renewal Growth</fullName>
            </value>
            <value>
                <fullName>Services Record Type</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/OpportunityContactRoleContactStageTest.cls
@isTest
public with sharing class OpportunityContactRoleContactStageTest {
  @TestSetup
  static void makeData() {
    ContactTestFactory.createContact();
  }

  @isTest
  static void testOppContactRolecontactStage() {
    Account account = [
      SELECT Id
      FROM Account
      WHERE Name LIKE 'AccountTestFactory%'
      LIMIT 1
    ];

    Opportunity opp = OpportunityTestFactory.getStage1Opp(
      account.Id,
      RecordTypeUtility.getId(Opportunity.getSObjectType(), 'New Business')
    );
    opp.Deal_Type__c = 'New Business';
    insert opp;

    Contact newContact = [
      SELECT Id
      FROM Contact
      WHERE LastName LIKE 'ContactTestFactory%'
    ];

    OpportunityContactRole contactRole = new OpportunityContactRole();
    contactRole.ContactId = newContact.Id;
    contactRole.OpportunityId = opp.Id;

    Test.startTest();
    insert contactRole;
    Test.stopTest();

    newContact = [
      SELECT Id, Stage__c
      FROM Contact
      WHERE Id = :newContact.Id
    ];

    System.assertEquals(
      'Opportunity',
      newContact.Stage__c,
      'Contact stage was not updated to Opportunity'
    );
  }
}