unpackaged/main/default/objects/Account/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Name</fullName>
            </value>
            <value>
                <fullName>Response</fullName>
            </value>
            <value>
                <fullName>Actionable Response</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <description>What type of opportunity is this?</description>
    <inlineHelpText>New Business = brand new logo

Upgrade = upgrading an Express customer to higher edition

Add-on = selling to existing customer

Renewal = existing deal renewed at end of its term

Early Renewal = existing deal renewed before current term is up</inlineHelpText>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Add-On</fullName>
            </value>
            <value>
                <fullName>Debook</fullName>
            </value>
            <value>
                <fullName>Early Renewal</fullName>
            </value>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Renewal Growth</fullName>
            </value>
            <value>
                <fullName>Services Record Type</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <businessProcess>Standard Sales Process</businessProcess>
    <description>System generated Opportunity used for renewing a Contract at the end of its term</description>
    <label>Renewal</label>
</RecordType>

unpackaged/main/default/classes/OpportunityContactStageHandlerTest.cls
@isTest
public with sharing class OpportunityContactStageHandlerTest {
  @TestSetup
  static void makeData() {
    ContactTestFactory.createContact();
  }

  @isTest
  static void testContactStageHandlingNewBus() {
    Account account = [
      SELECT Id
      FROM Account
      WHERE Name LIKE 'AccountTestFactory%'
      LIMIT 1
    ];
    Opportunity opp = OpportunityTestFactory.getStage1Opp(
      account.Id,
      RecordTypeUtility.getId(Opportunity.getSObjectType(), 'New Business')
    );
    opp.Deal_Type__c = 'New Business';

    Test.startTest();

    insert opp;

    Test.stopTest();
    Contact contact = [
      SELECT Id, Stage__c
      FROM Contact
      WHERE Id IN (SELECT ContactId FROM Opportunity WHERE Id = :opp.Id)
    ];

    System.assertEquals(
      'Opportunity',
      contact.Stage__c,
      'Contact Stage was not set to Opportunity.'
    );
  }

  @isTest
  static void testContactStageHandlingAddOn() {
    Account account = [
      SELECT Id
      FROM Account
      WHERE Name LIKE 'AccountTestFactory%'
      LIMIT 1
    ];
    Opportunity opp = OpportunityTestFactory.getStage1Opp(
      account.Id,
      RecordTypeUtility.getId(Opportunity.getSObjectType(), 'Add-On')
    );
    opp.Deal_Type__c = 'Add-On';

    Test.startTest();

    insert opp;

    Test.stopTest();
    Contact contact = [
      SELECT Id, Stage__c
      FROM Contact
      WHERE Id IN (SELECT ContactId FROM Opportunity WHERE Id = :opp.Id)
    ];

    System.assertEquals(
      'Opportunity',
      contact.Stage__c,
      'Contact Stage was not set to Opportunity.'
    );
  }

  @isTest
  static void testContactStageHandlingRenGrowth() {
    Account account = [
      SELECT Id
      FROM Account
      WHERE Name LIKE 'AccountTestFactory%'
      LIMIT 1
    ];
    Opportunity opp = OpportunityTestFactory.getStage1Opp(
      account.Id,
      RecordTypeUtility.getId(
        Opportunity.getSObjectType(),
        'Renewal Growth Add-on'
      )
    );

    opp.Deal_Type__c = 'Renewal Growth';

    Test.startTest();

    insert opp;

    Test.stopTest();
    Contact contact = [
      SELECT Id, Stage__c
      FROM Contact
      WHERE Id IN (SELECT ContactId FROM Opportunity WHERE Id = :opp.Id)
    ];

    System.assertEquals(
      'Opportunity',
      contact.Stage__c,
      'Contact Stage was not set to Opportunity.'
    );
  }
}