unpackaged/main/default/objects/Account/fields/Support_package__c.field-meta.xml
<CustomField>
    <fullName>Support_package__c</fullName>
    <label>Support package</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Platinum+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>for customer &amp; Prospect</description>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/Account_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_Account_ID__c</fullName>
    <formula>Account.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account: Account ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Account_Edition__c.field-meta.xml
<CustomField>
    <fullName>Account_Edition__c</fullName>
    <label>Account Edition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Account_Tier__c.field-meta.xml
<CustomField>
    <fullName>Account_Tier__c</fullName>
    <label>Account Tier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Support_Package__c.field-meta.xml
<CustomField>
    <fullName>Support_Package__c</fullName>
    <description>Video Cloud support package</description>
    <label>Support Package</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Platinum+</fullName>
            </value>
            <value>
                <fullName>DealDesk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Zapier_Case_Owner__c.field-meta.xml
<CustomField>
    <fullName>Zapier_Case_Owner__c</fullName>
    <formula>IF(ISBLANK(Owner:User.FirstName), Owner:Queue.QueueName ,
Owner:User.FirstName &amp; &quot; &quot; &amp; Owner:User.LastName)</formula>
    <label>Zapier Case Owner</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/PostChatRatingTest.cls
@isTest(isparallel=true)
public class PostChatRatingTest {
  @isTest
  static void testPostChat() {
    Contact contact = ContactTestFactory.getContact();
    contact.FirstName = 'TestName';
    contact.LastName = 'TestLastName';
    contact.Phone = '415.555.1212';
    contact.Email = 'Gamati@brightcove.com';
    insert contact;
    Id personContact = [
      SELECT Id, Name
      FROM Contact
      WHERE Contact.Name = 'TestName TestLastName'
    ]
    .Id;

    Case case1 = new Case();
    case1.ContactId = personContact;
    case1.Type = 'Customer Support Cases';
    case1.Origin = 'Live Chat';
    case1.Status = 'Status example';
    insert case1;
    Case[] case2;
    case2 = [
      SELECT
        ContactId,
        Contact.Name,
        Id,
        AccountId,
        Status,
        Account.Name,
        Account_Account_ID__c,
        OwnerId,
        Zapier_Case_Owner__c,
        CaseNumber,
        CreatedDate,
        ClosedDate,
        Account_Tier__c,
        Support_Package__c,
        Origin,
        ContactEmail,
        Account_Edition__c
      FROM Case
      WHERE ContactId = :personContact
      ORDER BY CaseNumber DESC
      LIMIT 1
    ];

    if (case2.size() != 0) {
      case2[0].Origin = 'Live Chat';
      update case2;
    }

    PostChatRating postChat = new PostChatRating();
    postChat.getCase();
  }

  @isTest
  static void testErrorChat() {
    Contact contact = ContactTestFactory.getContact();
    contact.FirstName = 'TestName';
    contact.LastName = 'TestLastName';
    contact.Phone = '415.555.1212';
    contact.Email = 'Gamati@brightcove.com';

    insert contact;
    Id personContact = [
      SELECT Id, Name
      FROM Contact
      WHERE Contact.Name = 'TestName TestLastName'
    ]
    .Id;

    Case case1 = new Case();
    case1.ContactId = personContact;
    case1.Type = 'Customer Support Cases';
    case1.Origin = 'Live Chat';
    case1.Status = 'Status example';
    insert case1;
    Case[] case2;
    case2 = [
      SELECT
        ContactId,
        Contact.Name,
        Id,
        AccountId,
        Status,
        Account.Name,
        Account_Account_ID__c,
        OwnerId,
        Zapier_Case_Owner__c,
        CaseNumber,
        CreatedDate,
        ClosedDate,
        Account_Tier__c,
        Support_Package__c,
        Origin,
        ContactEmail,
        Account_Edition__c
      FROM Case
      WHERE ContactId = :personContact
      ORDER BY CaseNumber DESC
      LIMIT 1
    ];

    PostChatRating postChat = new PostChatRating();
    postChat.getCase();
  }
}