unpackaged/main/default/objects/Account/fields/Total_Live_Event_Support_hours_available__c.field-meta.xml
<CustomField>
    <fullName>Total_Live_Event_Support_hours_available__c</fullName>
    <formula>Total_Live_Event_Support_hours_sold__c - Total_Live_Event_Support_hours_booked__c - Live_Event_Support_Hours_used__c + Manual_Live_Event_Support__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Live Event Support Hours available</inlineHelpText>
    <label>Total Live Event Support hours available</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Total_Live_Event_Support_hours_booked__c.field-meta.xml
<CustomField>
    <fullName>Total_Live_Event_Support_hours_booked__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Live Event Support hours booked</description>
    <inlineHelpText>Total Live Event Support Hours requested and pending coverage assignment.</inlineHelpText>
    <label>Total Live Event Support hours booked</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Total_Live_Event_Support_hours_sold__c.field-meta.xml
<CustomField>
    <fullName>Total_Live_Event_Support_hours_sold__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Live Event Support hours sold</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>for customer &amp; Prospect</description>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/objects/Live_Event_Coverage__c/Live_Event_Coverage__c.object-meta.xml
<CustomObject>
    <label>Live Event Coverage</label>
    <nameField>
        <displayFormat>LE - {0}</displayFormat>
        <label>Live Event Coverage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Live Event Coverage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Live_Event_Coverage__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Live Event Coverage</relationshipLabel>
    <relationshipName>Live_Event_Coverage</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage__c/fields/Communication_Channel__c.field-meta.xml
<CustomField>
    <fullName>Communication_Channel__c</fullName>
    <label>Communication Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Slack (Brightcove&#39;s Workspace)</fullName>
            </value>
            <value>
                <fullName>Gotomeeting (Brightcove&#39;s account)</fullName>
            </value>
            <value>
                <fullName>Customer will provide access to their Instant Messanger</fullName>
            </value>
            <value>
                <fullName>Customer will provide a phone bridge</fullName>
            </value>
            <value>
                <fullName>Not yet defined</fullName>
            </value>
            <value>
                <fullName>Salesforce Case/Emails</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage__c/fields/Event_Point_Of_Contact__c.field-meta.xml
<CustomField>
    <fullName>Event_Point_Of_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The primary person to contact during the event coverage &amp; to setup a time to test.</inlineHelpText>
    <label>Event Main Point Of Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Live Event Coverage</relationshipLabel>
    <relationshipName>Live_Event_Coverage</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage__c/fields/Full_Coverage_duration_hours__c.field-meta.xml
<CustomField>
    <fullName>Full_Coverage_duration_hours__c</fullName>
    <description>It replaced the &#39;Full Event duration (hours)&#39; field</description>
    <formula>(DATETIMEVALUE( TEXT(Event_End_Date__c)&amp;&quot; &quot;&amp; LEFT(TEXT(Event_End_Time__c),8)) 
- 
DATETIMEVALUE(TEXT(Event_Start_Date__c)&amp;&quot; &quot;&amp; LEFT(TEXT(Event_Start_Time__c),8)))*24</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Coverage duration (hours)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage__c/fields/High_Profile__c.field-meta.xml
<CustomField>
    <fullName>High_Profile__c</fullName>
    <label>High Profile?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage__c/fields/Hours_Covered_So_Far__c.field-meta.xml
<CustomField>
    <fullName>Hours_Covered_So_Far__c</fullName>
    <inlineHelpText>This is the sum of the timings that have been created on this object.</inlineHelpText>
    <label>Hours Covered So Far</label>
    <summarizedField>Live_Event_Coverage_Timing__c.Coverage_Duration_hours__c</summarizedField>
    <summaryFilterItems>
        <field>Live_Event_Coverage_Timing__c.Type__c</field>
        <operation>equals</operation>
        <value>Event</value>
    </summaryFilterItems>
    <summaryForeignKey>Live_Event_Coverage_Timing__c.CoverageLink__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage__c/fields/Live_Event_Category__c.field-meta.xml
<CustomField>
    <fullName>Live_Event_Category__c</fullName>
    <description>Live Event Category pick the kind of live event</description>
    <label>Live Event Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commerce - Auction</fullName>
            </value>
            <value>
                <fullName>Commerce - Product Launch</fullName>
            </value>
            <value>
                <fullName>Conference - Sales</fullName>
            </value>
            <value>
                <fullName>Conference - Religion</fullName>
            </value>
            <value>
                <fullName>Conference - Education</fullName>
            </value>
            <value>
                <fullName>Conference - Technology</fullName>
            </value>
            <value>
                <fullName>Conference - Other</fullName>
            </value>
            <value>
                <fullName>Corporate Meetings</fullName>
            </value>
            <value>
                <fullName>Entertainment - Sports</fullName>
            </value>
            <value>
                <fullName>Entertainment - eSports</fullName>
            </value>
            <value>
                <fullName>Entertainment - Music</fullName>
            </value>
            <value>
                <fullName>Entertainment - Cinema</fullName>
            </value>
            <value>
                <fullName>Entertainment - Fashion</fullName>
            </value>
            <value>
                <fullName>Entertainment - Other</fullName>
            </value>
            <value>
                <fullName>Government - Meeting/Townhall</fullName>
            </value>
            <value>
                <fullName>NGO - Meeting</fullName>
            </value>
            <value>
                <fullName>News - Politics</fullName>
            </value>
            <value>
                <fullName>News - Event</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage__c/fields/Live_Product__c.field-meta.xml
<CustomField>
    <fullName>Live_Product__c</fullName>
    <description>Please specify the live-event product for this event.</description>
    <inlineHelpText>Please specify the live-event product for this event.</inlineHelpText>
    <label>Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Brightcove Live</fullName>
            </value>
            <value>
                <fullName>Brightcove Live with SSAI</fullName>
                <label>Live SSAI</label>
            </value>
            <value>
                <fullName>Live DVR</fullName>
            </value>
            <value>
                <fullName>Live DRM</fullName>
            </value>
            <value>
                <fullName>Live Redundancy</fullName>
            </value>
            <value>
                <fullName>Clipping</fullName>
                <label>Live Clipping</label>
            </value>
            <value>
                <fullName>Remote Asset (3rd party Live) - BC Managed</fullName>
            </value>
            <value>
                <fullName>Remote Asset (3rd party Live) - BYO</fullName>
            </value>
            <value>
                <fullName>Cloud Playout</fullName>
            </value>
            <value>
                <fullName>Simulive</fullName>
            </value>
            <value>
                <fullName>Virtual Events Template</fullName>
            </value>
            <value>
                <fullName>Gallery</fullName>
            </value>
            <value>
                <fullName>Playback Rights/Geo-restriction</fullName>
            </value>
            <value>
                <fullName>Key Rotation</fullName>
            </value>
            <value>
                <fullName>Non-live (Ingestion/Playback API/etc.)</fullName>
            </value>
            <value>
                <fullName>Pigeonhole</fullName>
            </value>
            <value>
                <fullName>Beacon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage__c/fields/MAX_CCU_Estimated__c.field-meta.xml
<CustomField>
    <fullName>MAX_CCU_Estimated__c</fullName>
    <description>Max concurrent users ESTIMATED</description>
    <inlineHelpText>Max concurrent users estimated</inlineHelpText>
    <label>MAX CCU - Estimated</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage__c/fields/Number_of_concurrent_streams__c.field-meta.xml
<CustomField>
    <fullName>Number_of_concurrent_streams__c</fullName>
    <description>How many concurrent live jobs is the customer expecting us to monitor during the event?</description>
    <inlineHelpText>How many concurrent live jobs is the customer expecting us to monitor during the event?</inlineHelpText>
    <label>Number of concurrent streams</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage__c/fields/Publisher_ID__c.field-meta.xml
<CustomField>
    <fullName>Publisher_ID__c</fullName>
    <inlineHelpText>The specific Publisher ID hosting the event under the &quot;Account&quot; field.</inlineHelpText>
    <label>Publisher ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Live_Event_Coverage__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Used by Customer Support for Event Coverage Tracking.</inlineHelpText>
    <label>Coverage Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Checking details with AM</fullName>
            </value>
            <value>
                <fullName>Pending - CS - Assigning Resource</fullName>
            </value>
            <value>
                <fullName>Pending - CS - Resource Booked</fullName>
            </value>
            <value>
                <fullName>Closed - Rejected</fullName>
            </value>
            <value>
                <fullName>Closed - Completed [Business Hours]</fullName>
            </value>
            <value>
                <fullName>Closed - Completed [Off-Hours]</fullName>
            </value>
            <value>
                <fullName>Closed - Completed [Mixed]</fullName>
            </value>
            <value>
                <fullName>Need To Close</fullName>
            </value>
            <value>
                <fullName>Closed - Duplicate</fullName>
            </value>
            <value>
                <fullName>Open - Automated Monitoring</fullName>
            </value>
            <value>
                <fullName>Closed - Automated Monitoring</fullName>
            </value>
            <value>
                <fullName>Open - Premium Monitoring</fullName>
            </value>
            <value>
                <fullName>Closed - Premium Monitoring</fullName>
            </value>
            <value>
                <fullName>Pending - ProBono Event Rejected</fullName>
            </value>
            <value>
                <fullName>Closed - Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/LiveEventCoverageDeleteHandlerTest.cls
@isTest(isparallel=true)
public with sharing class LiveEventCoverageDeleteHandlerTest {
  @TestSetup
  private static void makeData() {
    createAccounts();
    createLE();
  }

  @isTest
  private static void deleteLE() {
    Account accountRecord = [
      SELECT
        Id,
        Total_Live_Event_Support_hours_sold__c,
        Total_Live_Event_Support_hours_booked__c,
        Total_Live_Event_Support_hours_available__c
      FROM Account
      WHERE NAME = 'UATTestLiveEvent'
    ];

    Live_Event_Coverage__c lE = [
      SELECT Id, Full_Coverage_duration_hours__c, Hours_Covered_So_Far__c
      FROM Live_Event_Coverage__c
      WHERE
        Account__c = :accountRecord.Id
        AND Status__c NOT IN (
          'Closed - Completed [Business Hours]',
          'Closed - Completed [Off-Hours]',
          'Closed - Completed [Mixed]'
        )
      LIMIT 1
    ];

    test.startTest();
    delete lE;
    test.stopTest();

    Account accountRecordAfterDelete = [
      SELECT
        Id,
        Total_Live_Event_Support_hours_sold__c,
        Total_Live_Event_Support_hours_booked__c,
        Total_Live_Event_Support_hours_available__c
      FROM Account
      WHERE NAME = 'UATTestLiveEvent'
    ];

    System.assertEquals(
      accountRecordAfterDelete.Total_Live_Event_Support_hours_booked__c,
      accountRecord.Total_Live_Event_Support_hours_booked__c -
      LE.Full_Coverage_duration_hours__c,
      'LE Deletion: Live Event Hours Booked calculation unsuccessful '
    );

    System.assertEquals(
      accountRecordAfterDelete.Total_Live_Event_Support_hours_available__c,
      accountRecord.Total_Live_Event_Support_hours_available__c +
      LE.Full_Coverage_duration_hours__c,
      'LE Deletion: Live Event Hours Avaialble calculation unsuccessful'
    );
  }

  static void createLE() {
    Id accountRecord = [
      SELECT Id
      FROM Account
      WHERE name = 'UATTestLiveEvent'
      LIMIT 1
    ]
    .Id;
    Contact contactRecord = [
      SELECT Id
      FROM Contact
      WHERE AccountId = :accountRecord
      LIMIT 1
    ];

    Id liveEventCoverageRecordTypeId = RecordTypeUtility.getId(
      Live_Event_Coverage__c.getSObjectType(),
      'Live Event Support'
    );

    Live_Event_Coverage__c lErecord = new Live_Event_Coverage__c(
      Event_Point_Of_Contact__c = contactRecord.Id,
      Account__c = accountRecord,
      RecordTypeId = liveEventCoverageRecordTypeId,
      Publisher_ID__c = '11111',
      Communication_Channel__c = 'Not yet defined',
      Live_Event_Category__c = 'Other',
      Number_of_concurrent_streams__c = 1,
      MAX_CCU_Estimated__c = 1,
      High_Profile__c = 'No',
      Status__c = 'New',
      Live_Product__c = 'Brightcove Live',
      Timezone__c = '(GMT-10:00) Hawaii',
      BGS_Managed_Event__c = 'No',
      Test_Start_Time__c = Time.newInstance(10, 0, 0, 0),
      Test_End_Time__c = Time.newInstance(10, 30, 0, 0),
      Test_Date__c = Date.today(),
      Event_Start_Date__c = Date.today(),
      Event_End_Date__c = Date.today(),
      Event_Start_Time__c = Time.newInstance(1, 0, 0, 0),
      Event_End_Time__c = Time.newInstance(3, 0, 0, 0)
    );

    Live_Event_Coverage__c lErecord2 = new Live_Event_Coverage__c(
      Event_Point_Of_Contact__c = contactRecord.Id,
      Account__c = accountRecord,
      RecordTypeId = liveEventCoverageRecordTypeId,
      Status__c = 'Closed - Completed [Off-Hours]',
      Publisher_ID__c = '11111',
      Communication_Channel__c = 'Not yet defined',
      Live_Event_Category__c = 'Other',
      Number_of_concurrent_streams__c = 1,
      MAX_CCU_Estimated__c = 1,
      High_Profile__c = 'No',
      Live_Product__c = 'Brightcove Live',
      Timezone__c = '(GMT-10:00) Hawaii',
      BGS_Managed_Event__c = 'No',
      Test_Start_Time__c = Time.newInstance(10, 0, 0, 0),
      Test_End_Time__c = Time.newInstance(10, 30, 0, 0),
      Test_Date__c = Date.today(),
      Event_Start_Date__c = Date.today(),
      Event_End_Date__c = Date.today(),
      Event_Start_Time__c = Time.newInstance(1, 0, 0, 0),
      Event_End_Time__c = Time.newInstance(3, 0, 0, 0)
    );

    Live_Event_Coverage__c lErecord3 = new Live_Event_Coverage__c(
      Event_Point_Of_Contact__c = contactRecord.Id,
      Account__c = accountRecord,
      RecordTypeId = liveEventCoverageRecordTypeId,
      Publisher_ID__c = '11111',
      Communication_Channel__c = 'Not yet defined',
      Live_Event_Category__c = 'Other',
      Number_of_concurrent_streams__c = 1,
      MAX_CCU_Estimated__c = 1,
      High_Profile__c = 'No',
      Status__c = 'New',
      Live_Product__c = 'Brightcove Live',
      Timezone__c = '(GMT-10:00) Hawaii',
      BGS_Managed_Event__c = 'No',
      Test_Start_Time__c = Time.newInstance(10, 0, 0, 0),
      Test_End_Time__c = Time.newInstance(10, 30, 0, 0),
      Test_Date__c = Date.today(),
      Event_Start_Date__c = Date.today(),
      Event_End_Date__c = Date.today(),
      Event_Start_Time__c = Time.newInstance(1, 0, 0, 0),
      Event_End_Time__c = Time.newInstance(3, 0, 0, 0)
    );

    List<Live_Event_Coverage__c> lEList = new List<Live_Event_Coverage__c>{
      lErecord,
      lErecord2,
      lErecord3
    };

    insert lEList;
  }

  private static void createAccounts() {
    Account customerAccount = AccountTestFactory.getCustomer();
    customerAccount.Name = 'UATTestLiveEvent';
    customerAccount.Account_Stage__c = 'Customer';
    customerAccount.Total_Live_Event_Support_hours_sold__c = 20;

    insert customerAccount;

    ContactTestFactory.createContact(customerAccount);
  }
}