unpackaged/main/default/objects/Lead/fields/Rejected_Reason__c.field-meta.xml
<CustomField>
    <fullName>Rejected_Reason__c</fullName>
    <label>Rejected Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rejected_Reasons</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Name</fullName>
                <default>true</default>
                <label>Name</label>
            </value>
            <value>
                <fullName>Response</fullName>
            </value>
            <value>
                <fullName>Actionable Response</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Stage_Date__c.field-meta.xml
<CustomField>
    <fullName>Stage_Date__c</fullName>
    <label>Stage Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/globalValueSets/Rejected_Reasons.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bad contact information</fullName>
    </customValue>
    <customValue>
        <fullName>Competitor</fullName>
    </customValue>
    <customValue>
        <fullName>Left organization</fullName>
    </customValue>
    <customValue>
        <fullName>Not a business</fullName>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Trash (Spam)</fullName>
    </customValue>
    <customValue>
        <fullName>Vendor</fullName>
    </customValue>
    <masterLabel>Rejected Reasons</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/LeadStamperTest.cls
@isTest(isparallel=true)
public with sharing class LeadStamperTest {
  @isTest
  private static void testStamp() {
    List<PicklistEntry> stages = Lead.Stage__c.getDescribe()
      .getPicklistValues();
    Lead testLead = LeadTestFactory.getLead();
    testLead.Stage__c = stages[0].getValue();
    insert testLead;

    testLead = [
      SELECT Id, n2de__Is_rejected__c, Rejected_Reason__c, Stage_Date__c
      FROM Lead
      WHERE Id = :testLead.Id
    ];

    System.assertEquals(
      Date.today(),
      testLead.Stage_Date__c,
      'Stage Date not set correctly.'
    );
  }
}