unpackaged/main/default/objects/Case/fields/Case_Language__c.field-meta.xml
<CustomField>
    <fullName>Case_Language__c</fullName>
    <label>Case Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>Korean</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/First_Response__c.field-meta.xml
<CustomField>
    <fullName>First_Response__c</fullName>
    <description>It stores the First response date and time and triggers the auto-complete of the milestone.</description>
    <label>First Response</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Contract_ID__c.field-meta.xml
<CustomField>
    <fullName>Contract_ID__c</fullName>
    <formula>SBQQ__Opportunity__r.Contract_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This is pulled from the Opportunity that generated this contract record</inlineHelpText>
    <label>Contract ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contract_Id__c.field-meta.xml
<CustomField>
    <fullName>Contract_Id__c</fullName>
    <label>Contract Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Is_the_Contract_Auto_Renewing__c.field-meta.xml
<CustomField>
    <fullName>Is_the_Contract_Auto_Renewing__c</fullName>
    <inlineHelpText>Indicate if the contract is Auto-Renewing, please mark &quot;Yes&quot; if you are closing Won the renewal as &quot;Auto-Renew&quot;</inlineHelpText>
    <label>Is the Contract Auto-Renewing?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Trial_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Trial_Account_Id__c</fullName>
    <label>Trial Account Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <businessProcess>Standard Sales Process</businessProcess>
    <description>System generated Opportunity used for renewing a Contract at the end of its term</description>
    <label>Renewal</label>
</RecordType>

unpackaged/main/default/classes/OpportunityStageCaseHandler.cls
public with sharing class OpportunityStageCaseHandler extends DomainLogicHandler {
  List<Id> qualifiedOppIds = new List<Id>();
  Id technicalSupportRecordType;
  Database.DMLOptions dmlOpts;

  public override void check(Sobject newObj, Sobject oldObj) {
    Opportunity newOpp = (Opportunity) newObj;
    Opportunity oldOpp = (Opportunity) oldObj;

    if (isQualified(newOpp, oldOpp)) {
      qualifiedOppIds.add(newOpp.Id);
    }
  }

  public override void processRecords() {
    if (qualifiedOppIds.isEmpty()) {
      return;
    }

    technicalSupportRecordType = RecordTypeUtility.getid(
      Case.getSObjectType(),
      'Technical Support'
    );
    setDmlOptions();

    List<Opportunity> opportunities = [
      SELECT Id, Name, AccountId, Account.Name, RecordType.Name, Owner.Name, Contract_Id__c, Trial_Account_Id__c
      FROM Opportunity
      WHERE Id IN :qualifiedOppIds
    ];

    List<Case> cases = new List<Case>();
    for (Opportunity opp : opportunities) {
      cases.add(getCase(opp));
    }

    insert cases;
  }

  Boolean isQualified(Opportunity newOpp, Opportunity oldOpp) {
    return (newOpp.StageName == 'Closed Won') &&
      (newOpp.StageName != oldOpp.StageName) &&
      (isRecordTypeQualified(newOpp));
  }

  Boolean isRecordTypeQualified(Opportunity newOpp) {
    return (RecordTypeUtility.getName(newOpp) == 'New Business' ||
      RecordTypeUtility.getName(newOpp) == 'Add-on') ||
      (RecordTypeUtility.getName(newOpp) == 'Renewal' &&
      newOPP.Is_the_Contract_Auto_Renewing__c != 'Yes');
  }

  void setDmlOptions() {
    AssignmentRule caseAssignRule = [
      SELECT Id, name
      FROM AssignmentRule
      WHERE SObjectType = 'Case' AND Active = TRUE
    ];

    dmlOpts = new Database.DMLOptions();
    dmlOpts.AssignmentRuleHeader.AssignmentRuleId = caseAssignRule.Id;
  }

  Case getCase(Opportunity opp) {
    Case techSupportCase = new Case();

    techSupportCase.setOptions(dmlOpts);
    techSupportCase.AccountId = opp.AccountId;
    techSupportCase.RecordTypeId = technicalSupportRecordType;
    techSupportCase.Status = 'New';
    techSupportCase.Subject =
      '[Automated] Review ' +
      opp.RecordType.name +
      ': ' +
      opp.Name;
    techSupportCase.First_Response__c = System.now();
    techSupportCase.Case_Language__c = 'English';
    techSupportCase.Description =
      'Account Name: ' +
      opp.Account.Name +
      '\n' + 
      'Contract ID: ' +
      opp.Contract_Id__c +
      '\n' +
      'Brightcove Account Number: ' +
      opp.Trial_Account_Id__c +
      '\n' +
      'Account Link: ' +
      URL.getSalesforceBaseUrl().toExternalForm() +
      '/' +
      opp.AccountId +
      '\n' +
      'Opportunity Owner: ' +
      opp.Owner.Name +
      '\n' +
      'Opportunity Type: ' +
      opp.RecordType.Name +
      '\n' +
      'Opportunity Link: ' +
      URL.getSalesforceBaseUrl().toExternalForm() +
      '/' +
      opp.Id +
      '\n \n' +
      'Thank you. \n Technical Support Team';
    techSupportCase.Type = 'Automated Task';
    techSupportCase.Priority = 'P3 - Normal';
    techSupportCase.Origin = 'System';

    return techSupportCase;
  }
}