unpackaged/main/default/objects/Contact/fields/Communication_Opt_In__c.field-meta.xml
<CustomField>
    <fullName>Communication_Opt_In__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes if the contact has explicitly opted in communication from Brightcove</description>
    <inlineHelpText>Denotes if the contact has explicitly opted in communication from Brightcove</inlineHelpText>
    <label>Communication - Opt-In</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Communication_Opt_Out__c.field-meta.xml
<CustomField>
    <fullName>Communication_Opt_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes if the contact has explicitly opted out of communication from Brightcove</description>
    <inlineHelpText>Denotes if the contact has explicitly opted out of communication from Brightcove</inlineHelpText>
    <label>Communication - Opt-Out</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Phone_Opt_In__c.field-meta.xml
<CustomField>
    <fullName>Phone_Opt_In__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes if the contact has explicitly opted in to phone communication from Brightcove</description>
    <inlineHelpText>Denotes if the contact has explicitly opted in to phone communication from Brightcove</inlineHelpText>
    <label>Phone - Opt-In</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Phone_Opt_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Phone_Opt_In_Date__c</fullName>
    <description>Captures the latest date on which the contact expressed their consent to receive phone communication from Brightcove.</description>
    <inlineHelpText>Captures the latest date on which the contact expressed their consent to receive phone communication from Brightcove.</inlineHelpText>
    <label>Phone - Opt-In Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Phone_Opt_Out__c.field-meta.xml
<CustomField>
    <fullName>Phone_Opt_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes if the contact has explicitly opted in to phone communication from Brightcove</description>
    <inlineHelpText>Denotes if the contact has explicitly opted in to phone communication from Brightcove</inlineHelpText>
    <label>Phone - Opt-Out</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Phone_Opt_Out_Date__c.field-meta.xml
<CustomField>
    <fullName>Phone_Opt_Out_Date__c</fullName>
    <description>Captures the latest date on which the contact opted out from receiving phone communication from Brightcove.</description>
    <inlineHelpText>Captures the latest date on which the contact opted out from receiving phone communication from Brightcove.</inlineHelpText>
    <label>Phone - Opt-Out Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Communication_Opt_In__c.field-meta.xml
<CustomField>
    <fullName>Communication_Opt_In__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Communication - Opt-In</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Communication_Opt_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Communication_Opt_In_Date__c</fullName>
    <label>Communication - Opt-In Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Communication_Opt_Out__c.field-meta.xml
<CustomField>
    <fullName>Communication_Opt_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Communication - Opt-Out</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Communication_Opt_Out_Date__c.field-meta.xml
<CustomField>
    <fullName>Communication_Opt_Out_Date__c</fullName>
    <label>Communication - Opt-Out Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Phone_Opt_In__c.field-meta.xml
<CustomField>
    <fullName>Phone_Opt_In__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes if the lead has explicitly opted in to phone communication from Brightcove</description>
    <inlineHelpText>Denotes if the lead has explicitly opted in to phone communication from Brightcove</inlineHelpText>
    <label>Phone - Opt-In</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Phone_Opt_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Phone_Opt_In_Date__c</fullName>
    <description>Captures the latest date on which the lead expressed their consent to receive phone communication from Brightcove.</description>
    <inlineHelpText>Captures the latest date on which the lead expressed their consent to receive phone communication from Brightcove.</inlineHelpText>
    <label>Phone - Opt-In Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Phone_Opt_Out__c.field-meta.xml
<CustomField>
    <fullName>Phone_Opt_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes if the lead has explicitly opted in to phone communication from Brightcove</description>
    <inlineHelpText>Denotes if the lead has explicitly opted in to phone communication from Brightcove</inlineHelpText>
    <label>Phone - Opt-Out</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Phone_Opt_Out_Date__c.field-meta.xml
<CustomField>
    <fullName>Phone_Opt_Out_Date__c</fullName>
    <description>Captures the latest date on which the lead opted out from receiving phone communication from Brightcove.</description>
    <inlineHelpText>Captures the latest date on which the lead opted out from receiving phone communication from Brightcove.</inlineHelpText>
    <label>Phone - Opt-Out Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/CommunicationOptDateStamperTest.cls
@IsTest(isparallel=true)
public with sharing class CommunicationOptDateStamperTest {
  @IsTest
  private static void testInsertandUpdateContact() {
    Contact contact = ContactTestFactory.getContact();
    contact.Communication_Opt_In__c = true;
    contact.Communication_Opt_Out__c = true;
    contact.Phone_Opt_In__c = true;
    contact.Phone_Opt_Out__c = true;
    insert contact;

    contact = [
      SELECT
        Id,
        Communication_Opt_In_Date__c,
        Communication_Opt_Out_Date__c,
        Phone_Opt_In_Date__c,
        Phone_Opt_Out_Date__c
      FROM Contact
      WHERE Id = :contact.Id
    ];

    system.assertEquals(
      Date.today(),
      contact.Communication_Opt_In_Date__c,
      'Communication_Opt_In_Date__c has not updated to todays date when created'
    );
    system.assertEquals(
      Date.today(),
      contact.Communication_Opt_Out_Date__c,
      'Communication_Opt_Out_Date__c has not updated to todays date when created'
    );
    system.assertEquals(
      Date.today(),
      contact.Phone_Opt_In_Date__c,
      'Phone_Opt_In_Date__c has not updated to todays date when created'
    );
    system.assertEquals(
      Date.today(),
      contact.Phone_Opt_Out_Date__c,
      'Phone_Opt_Out_Date__c has not updated to todays date when created'
    );

    contact.Communication_Opt_In__c = false;
    contact.Communication_Opt_Out__c = false;
    contact.Phone_Opt_In__c = false;
    contact.Phone_Opt_Out__c = false;

    update contact;
    contact = [
      SELECT
        Id,
        Communication_Opt_In_Date__c,
        Communication_Opt_Out_Date__c,
        Phone_Opt_In_Date__c,
        Phone_Opt_Out_Date__c
      FROM Contact
      WHERE Id = :contact.Id
    ];

    system.assertEquals(
      null,
      contact.Communication_Opt_In_Date__c,
      'Communication_Opt_In_Date__c has not cleared'
    );
    system.assertEquals(
      null,
      contact.Communication_Opt_Out_Date__c,
      'Communication_Opt_Out_Date__c has not cleared'
    );
    system.assertEquals(
      null,
      contact.Phone_Opt_In_Date__c,
      'Phone_Opt_In_Date__c has not cleared'
    );
    system.assertEquals(
      null,
      contact.Phone_Opt_Out_Date__c,
      'Phone_Opt_Out_Date__c has not cleared'
    );

    contact.Communication_Opt_In__c = true;
    contact.Communication_Opt_Out__c = true;
    contact.Phone_Opt_In__c = true;
    contact.Phone_Opt_Out__c = true;

    update contact;
    contact = [
      SELECT
        Id,
        Communication_Opt_In_Date__c,
        Communication_Opt_Out_Date__c,
        Phone_Opt_In_Date__c,
        Phone_Opt_Out_Date__c
      FROM Contact
      WHERE Id = :contact.Id
    ];

    system.assertEquals(
      Date.today(),
      contact.Communication_Opt_In_Date__c,
      'Communication_Opt_In_Date__c has not updated to todays date when updated'
    );
    system.assertEquals(
      Date.today(),
      contact.Communication_Opt_Out_Date__c,
      'Communication_Opt_Out_Date__c has not updated to todays date when updated'
    );
    system.assertEquals(
      Date.today(),
      contact.Phone_Opt_In_Date__c,
      'Phone_Opt_In_Date__c has not updated to todays date when updated'
    );
    system.assertEquals(
      Date.today(),
      contact.Phone_Opt_Out_Date__c,
      'Phone_Opt_Out_Date__c has not updated to todays date when updated'
    );
  }

  @IsTest
  private static void testInsertandUpdatelead() {
    Lead lead = LeadTestFactory.getLead();

    lead.Communication_Opt_In__c = true;
    lead.Communication_Opt_Out__c = true;
    lead.Phone_Opt_In__c = true;
    lead.Phone_Opt_Out__c = true;

    insert lead;

    lead = [
      SELECT
        Id,
        Communication_Opt_In_Date__c,
        Communication_Opt_Out_Date__c,
        Phone_Opt_In_Date__c,
        Phone_Opt_Out_Date__c
      FROM Lead
      WHERE Id = :lead.Id
    ];

    system.assertEquals(
      Date.today(),
      lead.Communication_Opt_In_Date__c,
      'Communication_Opt_In_Date__c has not updated to todays date when created'
    );
    system.assertEquals(
      Date.today(),
      lead.Communication_Opt_Out_Date__c,
      'Communication_Opt_Out_Date__c has not updated to todays date when created'
    );
    system.assertEquals(
      Date.today(),
      lead.Phone_Opt_In_Date__c,
      'Phone_Opt_In_Date__c has not updated to todays date when created'
    );
    system.assertEquals(
      Date.today(),
      lead.Phone_Opt_Out_Date__c,
      'Phone_Opt_Out_Date__c has not updated to todays date when created'
    );

    lead.Communication_Opt_In__c = false;
    lead.Communication_Opt_Out__c = false;
    lead.Phone_Opt_In__c = false;
    lead.Phone_Opt_Out__c = false;

    update lead;
    lead = [
      SELECT
        Id,
        Communication_Opt_In_Date__c,
        Communication_Opt_Out_Date__c,
        Phone_Opt_In_Date__c,
        Phone_Opt_Out_Date__c
      FROM Lead
      WHERE Id = :lead.Id
    ];

    system.assertEquals(
      null,
      lead.Communication_Opt_In_Date__c,
      'Communication_Opt_In_Date__c has not cleared'
    );
    system.assertEquals(
      null,
      lead.Communication_Opt_Out_Date__c,
      'Communication_Opt_Out_Date__c has not cleared'
    );
    system.assertEquals(
      null,
      lead.Phone_Opt_In_Date__c,
      'Phone_Opt_In_Date__c has not cleared'
    );
    system.assertEquals(
      null,
      lead.Phone_Opt_Out_Date__c,
      'Phone_Opt_Out_Date__c has not cleared'
    );

    lead.Communication_Opt_In__c = true;
    lead.Communication_Opt_Out__c = true;
    lead.Phone_Opt_In__c = true;
    lead.Phone_Opt_Out__c = true;

    update lead;
    lead = [
      SELECT
        Id,
        Communication_Opt_In_Date__c,
        Communication_Opt_Out_Date__c,
        Phone_Opt_In_Date__c,
        Phone_Opt_Out_Date__c
      FROM Lead
      WHERE Id = :lead.Id
    ];

    system.assertEquals(
      Date.today(),
      lead.Communication_Opt_In_Date__c,
      'Communication_Opt_In_Date__c has not updated to todays date when updated'
    );
    system.assertEquals(
      Date.today(),
      lead.Communication_Opt_Out_Date__c,
      'Communication_Opt_Out_Date__c has not updated to todays date when updated'
    );
    system.assertEquals(
      Date.today(),
      lead.Phone_Opt_In_Date__c,
      'Phone_Opt_In_Date__c has not updated to todays date when updated'
    );
    system.assertEquals(
      Date.today(),
      lead.Phone_Opt_Out_Date__c,
      'Phone_Opt_Out_Date__c has not updated to todays date when updated'
    );
  }
}