unpackaged/main/default/objects/Contact/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Name</fullName>
            </value>
            <value>
                <fullName>Response</fullName>
            </value>
            <value>
                <fullName>Actionable Response</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <description>What type of opportunity is this?</description>
    <inlineHelpText>New Business = brand new logo

Upgrade = upgrading an Express customer to higher edition

Add-on = selling to existing customer

Renewal = existing deal renewed at end of its term

Early Renewal = existing deal renewed before current term is up</inlineHelpText>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Add-On</fullName>
            </value>
            <value>
                <fullName>Debook</fullName>
            </value>
            <value>
                <fullName>Early Renewal</fullName>
            </value>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Renewal Growth</fullName>
            </value>
            <value>
                <fullName>Services Record Type</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <businessProcess>Standard Sales Process</businessProcess>
    <description>System generated Opportunity used for renewing a Contract at the end of its term</description>
    <label>Renewal</label>
</RecordType>

unpackaged/main/default/classes/OpportunityContactRoleContactStage.cls
public with sharing class OpportunityContactRoleContactStage extends DomainLogicHandler {
    List<Id> contacts = new List<Id>();
    List<Id> opps = new List<Id>();
    Map<Id, List<Id>> oppcontactIdMap = new Map<Id, List<Id>>();

    public override void check(SObject newObject) {
        OpportunityContactRole newRole = (OpportunityContactRole) newObject;

        contacts.add(newRole.ContactId);

        if (!oppContactIdMap.containskey(newRole.OpportunityId)) {
            oppContactIdMap.put(newRole.OpportunityId, new List<Id>());
        }
        oppContactIdMap.get(newRole.OpportunityId).add(newRole.ContactId);
    }

    public override void processRecords() {
        List<Opportunity> workingOpps = [
            SELECT Id, Deal_Type__c
            FROM Opportunity
            WHERE
                Id IN :oppContactIdMap.keyset()
                AND Deal_Type__c IN ('New Business', 'Add-On', 'Renewal Growth')
        ];
        Map<Id, Contact> contactRecords = new Map<Id, Contact>(
            [
                SELECT Id, Stage__c
                FROM Contact
                WHERE Id IN :contacts AND Stage__c != 'Opportunity'
            ]
        );
        for (Opportunity newOpp : workingOpps) {
            List<Id> contactIds = oppcontactIdMap.get(newopp.Id);
            for (Id contactId : contactIds) {
                if (contactRecords.containsKey(contactId)) {
                    Contact contact = contactRecords.get(contactId);
                    contact.Stage__c = 'Opportunity';
                }
            }
        }
        update contactRecords.values();
    }
}