unpackaged/main/default/objects/Contact/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Name</fullName>
            </value>
            <value>
                <fullName>Response</fullName>
            </value>
            <value>
                <fullName>Actionable Response</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <description>What type of opportunity is this?</description>
    <inlineHelpText>New Business = brand new logo

Upgrade = upgrading an Express customer to higher edition

Add-on = selling to existing customer

Renewal = existing deal renewed at end of its term

Early Renewal = existing deal renewed before current term is up</inlineHelpText>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Add-On</fullName>
            </value>
            <value>
                <fullName>Debook</fullName>
            </value>
            <value>
                <fullName>Early Renewal</fullName>
            </value>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Renewal Growth</fullName>
            </value>
            <value>
                <fullName>Services Record Type</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <businessProcess>Standard Sales Process</businessProcess>
    <description>System generated Opportunity used for renewing a Contract at the end of its term</description>
    <label>Renewal</label>
</RecordType>

unpackaged/main/default/classes/OpportunityClosedHandler.cls
public with sharing class OpportunityClosedHandler extends DomainLogicHandler {
    List<Id> oppIds = new List<Id>();

    public override void check(SObject newObject, SObject oldObject) {
        Opportunity newOpp = (Opportunity) newObject;
        Opportunity oldOpp = (Opportunity) oldObject;
        if (isQualified(newOpp, oldOpp)) {
            oppIds.add(newOpp.Id);
        }
    }

    public override void processRecords() {
        List<OpportunityContactRole> roles = [
            SELECT Id, ContactId
            FROM OpportunityContactRole
            WHERE OpportunityId IN :oppIds
        ];

        List<Id> contactIds = new List<Id>();
        for (OpportunityContactRole role : roles) {
            contactIds.add(role.ContactId);
        }

        List<Contact> contacts = [
            SELECT
                Id,
                (
                    SELECT Id
                    FROM OpportunityContactRoles
                    WHERE Opportunity.IsClosed = FALSE
                )
            FROM Contact
            WHERE Id IN :contactIds
        ];

        List<Contact> recycledContacts = new List<Contact>();
        for (Contact contact : contacts) {
            if (contact.OpportunityContactRoles.isEmpty()) {
                contact.Stage__c = 'Recycled';
                recycledContacts.add(contact);
            }
        }
        update recycledContacts;
    }

    Boolean isQualified(Opportunity newOpp, Opportunity oldOpp) {
        return newOpp.isClosed &&
            isChanged(newOpp, oldOpp) &&
            //newOpp.ContactId != null &&
            isDealTypeQualified(newOpp);
    }

    Boolean isDealTypeQualified(Opportunity newOpp) {
        return newOpp.Deal_Type__c == 'New Business' ||
            newOpp.Deal_Type__c == 'Add-On' ||
            newOpp.Deal_Type__c == 'Renewal Growth';
    }

    Boolean isChanged(Opportunity newOpp, Opportunity oldOpp) {
        return newOpp.StageName != oldOpp.StageName;
    }
}