unpackaged/main/default/objects/Brightcove_Account__c/Brightcove_Account__c.object-meta.xml
<CustomObject>
    <label>Brightcove Account</label>
    <nameField>
        <label>Brightcove Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brightcove Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Date_of_Last_Subscription_Change__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Last_Subscription_Change__c</fullName>
    <label>Date of Last Subscription Change</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Date_of_Subscription_Initial__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Subscription_Initial__c</fullName>
    <label>Date of Subscription (Initial)</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Date_of_Subscription_Latest__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Subscription_Latest__c</fullName>
    <label>Date of Subscription (Latest)</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Tier</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Prime</fullName>
            </value>
            <value>
                <fullName>Basic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/BrightcoveAccountSubscriptionDateManager.cls
public with sharing class BrightcoveAccountSubscriptionDateManager extends DomainLogicHandler {
    public override void check(SObject newObj) {
        Brightcove_Account__c newBcAccount = (Brightcove_Account__c)newObj;
        if(isQualified(newBcAccount)) {
            newBcAccount.Date_of_Subscription_Initial__c = Date.today();
            setSubscriptionDates(newBcAccount);
        }
    }

    public override void check(SObject newObj, SObject oldObj) {
        Brightcove_Account__c newBcAccount = (Brightcove_Account__c)newObj;
        Brightcove_Account__c oldBcAccount = (Brightcove_Account__c)oldObj;
        if(isQualified(newBcAccount, oldBcAccount)) {
            setSubscriptionDates(newBcAccount);
            if(isQualified(newBcAccount)) {
                newBcAccount.Date_of_Subscription_Initial__c = Date.today();
            }
        }
    }

    Boolean isQualified(Brightcove_Account__c newBcAccount) {
        return newBcAccount.Tier__c == 'Premium';
    }

    Boolean isQualified(Brightcove_Account__C newBcAccount, Brightcove_Account__C oldBcAccount) {
        return TriggerUtility.isChanged(newBcAccount, oldBcAccount, Brightcove_Account__c.Tier__c);
    }

    void setSubscriptionDates(Brightcove_Account__c newBcAccount) {
        newBcAccount.Date_of_Subscription_Latest__c = Date.today();
        newBcAccount.Date_of_Last_Subscription_Change__c = Date.today();
    }
}