unpackaged/main/default/objects/Brightcove_Account__c/Brightcove_Account__c.object-meta.xml
<CustomObject>
    <label>Brightcove Account</label>
    <nameField>
        <label>Brightcove Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brightcove Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brightcove Account</relationshipLabel>
    <relationshipName>Brightcove_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Brightcove_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Brightcove_Account_Id__c</fullName>
    <description>The Pub ID of the Brightcove account&#39;s Id in our own database. Updated via sync from origin-services account.</description>
    <externalId>true</externalId>
    <inlineHelpText>The Pub ID of the Brightcove account&#39;s Id in our own database. Updated via sync from origin-services account.</inlineHelpText>
    <label>Brightcove Account Id</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Brightcove_Account__c.field-meta.xml
<CustomField>
    <fullName>Brightcove_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brightcove Account</label>
    <referenceTo>Brightcove_Account__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Brightcove_Accounts_to_Terminate__c.field-meta.xml
<CustomField>
    <fullName>Brightcove_Accounts_to_Terminate__c</fullName>
    <label>Brightcove Accounts to Terminate</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Client_Termination_Date__c.field-meta.xml
<CustomField>
    <fullName>Client_Termination_Date__c</fullName>
    <label>Client Termination Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Client_Termination_Date_Stamp__c.field-meta.xml
<CustomField>
    <fullName>Client_Termination_Date_Stamp__c</fullName>
    <label>Client Termination Date Stamp</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Client_Termination_Rights__c.field-meta.xml
<CustomField>
    <fullName>Client_Termination_Rights__c</fullName>
    <label>Client Termination Rights</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Client_Termination_Status__c.field-meta.xml
<CustomField>
    <fullName>Client_Termination_Status__c</fullName>
    <label>Client Termination Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Client_Termination_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Client_Termination_Submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Client Termination Submitted?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contract_Ids_to_Terminate__c.field-meta.xml
<CustomField>
    <fullName>Contract_Ids_to_Terminate__c</fullName>
    <label>Contract Ids to Terminate</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contract_URL__c.field-meta.xml
<CustomField>
    <fullName>Contract_URL__c</fullName>
    <label>Contract URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contracts_to_Terminate__c.field-meta.xml
<CustomField>
    <fullName>Contracts_to_Terminate__c</fullName>
    <label>Contracts to Terminate</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Deactivation_Date__c.field-meta.xml
<CustomField>
    <fullName>Deactivation_Date__c</fullName>
    <description>Populate the date we should lock their BCAccounts</description>
    <inlineHelpText>Populate the date we should lock their BCAccounts</inlineHelpText>
    <label>Deactivation Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <description>Populate the contract end date or agreed upon contract termination/expiration date</description>
    <inlineHelpText>Populate the contract end date or agreed upon contract termination/expiration date</inlineHelpText>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Existing_MRR__c.field-meta.xml
<CustomField>
    <fullName>Existing_MRR__c</fullName>
    <label>Existing MRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Reason_for_Win_Loss__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Win_Loss__c</fullName>
    <label>Reason for Win / Loss</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Business Change</fullName>
            </value>
            <value>
                <fullName>Business Priority or Budget</fullName>
            </value>
            <value>
                <fullName>External Factor</fullName>
            </value>
            <value>
                <fullName>Not a Brightcove Priority</fullName>
            </value>
            <value>
                <fullName>Price to Value (Closed Lost)</fullName>
            </value>
            <value>
                <fullName>Price to Value (Closed Won)</fullName>
            </value>
            <value>
                <fullName>Relationship (Closed Lost)</fullName>
            </value>
            <value>
                <fullName>Relationship (Closed Won)</fullName>
            </value>
            <value>
                <fullName>Salesforce Correction</fullName>
            </value>
            <value>
                <fullName>Technology or Capability (Closed Lost)</fullName>
            </value>
            <value>
                <fullName>Technology or Capability (Closed Won)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Request_Narrative_for_Finance_Review__c.field-meta.xml
<CustomField>
    <fullName>Request_Narrative_for_Finance_Review__c</fullName>
    <label>Request Narrative for Finance Review</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/SubReason_for_winloss__c.field-meta.xml
<CustomField>
    <fullName>SubReason_for_winloss__c</fullName>
    <label>Sub-Reason for Win / Loss</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Reason_for_Win_Loss__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Better solution, not worth the price</fullName>
            </value>
            <value>
                <fullName>Better solution, worth the price</fullName>
            </value>
            <value>
                <fullName>BGS/Services ability to create a highly custom solution</fullName>
            </value>
            <value>
                <fullName>BGS/Services cost too high</fullName>
            </value>
            <value>
                <fullName>Brightcove used on other teams in organization</fullName>
            </value>
            <value>
                <fullName>Challenging customer</fullName>
            </value>
            <value>
                <fullName>Change of company control</fullName>
            </value>
            <value>
                <fullName>Company-wide budget freezes or RIFS</fullName>
            </value>
            <value>
                <fullName>Contact not the ultimate buyer</fullName>
            </value>
            <value>
                <fullName>Customer non-payments</fullName>
            </value>
            <value>
                <fullName>Executive or board level relationships</fullName>
            </value>
            <value>
                <fullName>Expected deal size is too small</fullName>
            </value>
            <value>
                <fullName>Insufficient ROI</fullName>
            </value>
            <value>
                <fullName>Integrated into our tech stack</fullName>
            </value>
            <value>
                <fullName>Lack of solution completeness</fullName>
            </value>
            <value>
                <fullName>M&amp;A</fullName>
            </value>
            <value>
                <fullName>Missing tablestakes feature/unable to serve use case</fullName>
            </value>
            <value>
                <fullName>Non-responsive contact / Decision maker left</fullName>
            </value>
            <value>
                <fullName>Only one who could solve the problem / uniquely able to solve</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Poor buyer experience</fullName>
            </value>
            <value>
                <fullName>Prior experience with Brightcove (didn&#39;t consider alternatives)</fullName>
            </value>
            <value>
                <fullName>Reliability/Scalability/Customer Support</fullName>
            </value>
            <value>
                <fullName>Salesforce Correction</fullName>
            </value>
            <value>
                <fullName>Similar solution, not the best price</fullName>
            </value>
            <value>
                <fullName>Similar solution, won on price</fullName>
            </value>
            <value>
                <fullName>Solution completeness</fullName>
            </value>
            <value>
                <fullName>Too difficult to onboard or switch from existing solution</fullName>
            </value>
            <value>
                <fullName>Trusted sales advisor</fullName>
            </value>
            <value>
                <fullName>Unable to come to legal or contractual terms</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Termination_Type__c.field-meta.xml
<CustomField>
    <fullName>Termination_Type__c</fullName>
    <label>Termination Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non-Renewal</fullName>
            </value>
            <value>
                <fullName>Account Termination</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Won_Lost_Against__c.field-meta.xml
<CustomField>
    <fullName>Won_Lost_Against__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Won/Lost Against</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Competitor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Won/Lost Against)</relationshipLabel>
    <relationshipName>Opportunities_WonLost_Against</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Won_Lost_Story__c.field-meta.xml
<CustomField>
    <fullName>Won_Lost_Story__c</fullName>
    <label>Won/Lost Story</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/ClientTerminationController.cls
public with sharing class ClientTerminationController {
  private Map<String, String> availableBCAccountsMap;
  private Map<String, String> selectedBCAccountsMap;
  private Map<String, String> availableContractsMap;
  private Map<String, String> selectedContractsMap;

  public Opportunity opp { get; set; }
  public Boolean confirmMode { get; set; }
  public String parentURL { get; set; }
  public String accountOwnerName { get; set; }
  public String accountManagerName { get; set; }
  public Boolean closeWindow { get; set; }
  public String title { get; set; }
  public String contactInformation { get; set; }
  public List<String> selectedBCAccountIds { get; set; }
  public List<String> removedBCAccountIds { get; set; }
  public List<String> selectedContractIds { get; set; }
  public List<String> removedContractIds { get; set; }

  public Map<String, String> getAvailableContractsMap() {
    return availableContractsMap;
  }

  public Map<String, String> getAvailableBCAccountsMap() {
    return availableBCAccountsMap;
  }

  public ClientTerminationController(
    ApexPages.StandardController stdController
  ) {
    initializeController();
  }

  public void initializeController() {
    contactInformation = '';
    title = 'Client Termination Request';
    closeWindow = false;
    String tempUrl = ApexPages.currentPage().getParameters().get('parenturl');
    parentURL = '';
    if (!String.isEmpty(tempUrl)) {
      parentURL = EncodingUtil.urlDecode(tempUrl, 'UTF-8');
    }
    confirmMode = false;
    Id oppId = ApexPages.currentPage().getParameters().get('oppId');
    opp = [
      SELECT
        Id,
        Name,
        StageName,
        Existing_MRR__c,
        AccountId,
        Owner.Name,
        Account.Owner.Name,
        CloseDate,
        Account.Name,
        Termination_Type__c,
        Request_Narrative_for_Finance_Review__c,
        Client_Termination_Rights__c,
        SubReason_for_winloss__c,
        Reason_for_Win_Loss__c,
        Client_Termination_Date__c,
        Deactivation_Date__c,
        Effective_Date__c,
        Contract_URL__c,
        Won_Lost_Against__c,
        Won_Lost_Story__c
      FROM Opportunity
      WHERE Id = :oppId
    ];

    Account account = [
      SELECT
        Id,
        Name,
        OwnerId,
        Owner.Name,
        (
          SELECT Id, User.Name
          FROM AccountTeamMembers
          WHERE TeamMemberRole = 'Account Manager'
        )
      FROM Account
      WHERE Id = :opp.AccountId
    ];

    accountOwnerName = account.AccountTeamMembers.isEmpty()
      ? account.Owner.Name
      : account.AccountTeamMembers[0].User.Name;

    initializeCollections();
    getBCAccounts();
    getContracts();
  }

  public PageReference cancel() {
    return new PageReference('/' + opp.Id);
  }

  public PageReference saveClientTermination() {
    confirmMode = false;
    String tempStr = '';

    if (selectedBCAccountsMap.keySet().isEmpty()) {
      tempStr = 'Select BC Accounts for termination';
    }

    if (!String.isEmpty(tempStr)) {
      Exception expObj = new BaseException(tempStr);
      expObj.setMessage(tempStr);
      ApexPages.addMessages(expObj);
      return null;
    }

    try {
      String bcAccountIds = '';
      for (String tempBcId : selectedBCAccountsMap.values()) {
        bcAccountIds += (!String.isEmpty(bcAccountIds))
          ? ';' + tempBcId
          : tempBcId;
      }

      String contractIds = '';
      String contractNames = '';
      for (String tempContractId : selectedContractsMap.keySet()) {
        contractIds += (!String.isEmpty(contractIds))
          ? ';' + tempContractId
          : tempContractId;
        String tempName = selectedContractsMap.get(tempContractId);
        contractNames += (!String.isEmpty(contractNames))
          ? ';' + tempName
          : tempName;
      }

      Opportunity updateOpp = new Opportunity(
        Id = opp.Id,
        Brightcove_Accounts_to_Terminate__c = bcAccountIds,
        Contracts_to_Terminate__c = contractNames,
        Contract_Ids_to_Terminate__c = contractIds,
        Client_Termination_Submitted__c = true,
        Client_Termination_Status__c = 'In Process',
        Client_Termination_Date_Stamp__c = Datetime.now(),
        Request_Narrative_for_Finance_Review__c = opp.Request_Narrative_for_Finance_Review__c,
        Client_Termination_Date__c = opp.Client_Termination_Date__c,
        Client_Termination_Rights__c = opp.Client_Termination_Rights__c,
        Effective_Date__c = opp.Effective_Date__c,
        Deactivation_Date__c = opp.Deactivation_Date__c,
        Contract_URL__c = opp.Contract_URL__c
      );

      update updateOpp;

      // Create an approval request for the account
      Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
      req.setComments('Client Termination Request');
      req.setObjectId(opp.id);

      // Client Termination Request
      Approval.ProcessResult result = Approval.process(req);
    } catch (Exception exp) {
      ApexPages.addMessages(exp);
      return null;
    }
    confirmMode = true;
    return new Pagereference('/' + opp.Id);
  }

  public void initializeCollections() {
    selectedBCAccountIds = new List<String>();
    removedBCAccountIds = new List<String>();
    availableBCAccountsMap = new Map<String, String>();
    selectedBCAccountsMap = new Map<String, String>();

    selectedContractIds = new List<String>();
    removedContractIds = new List<String>();
    availableContractsMap = new Map<String, String>();
    selectedContractsMap = new Map<String, String>();
  }

  public void getBCAccounts() {
    List<Brightcove_Account__c> brightCoveAccounts = [
      SELECT Id, Name, Brightcove_Account_Id__c
      FROM Brightcove_Account__c
      WHERE Account__c = :opp.AccountId
    ];
    for (Brightcove_Account__c brightCoveAccount : brightCoveAccounts) {
      availableBCAccountsMap.put(
        brightcoveAccount.Name,
        brightcoveAccount.Brightcove_Account_Id__c
      );
    }
  }

  public void getContracts() {
    List<Contract> contracts = [
      SELECT Id, Name, AccountId, ContractNumber
      FROM Contract
      WHERE AccountId = :opp.AccountId
    ];
    for (Contract contract : contracts) {
      availableContractsMap.put(contract.Id, contract.ContractNumber);
    }
  }

  public void add() {
    if (!selectedBCAccountIds.isEmpty()) {
      for (String bcAccountId : selectedBCAccountIds) {
        selectedBCAccountsMap.put(
          bcAccountId,
          availableBCAccountsMap.get(bcAccountId)
        );
        availableBCAccountsMap.remove(bcAccountId);
      }
    }
  }

  public void addContracts() {
    if (!selectedContractIds.isEmpty()) {
      for (String contractId : selectedContractIds) {
        selectedContractsMap.put(
          contractId,
          availableContractsMap.get(contractId)
        );
        availableContractsMap.remove(contractId);
      }
    }
  }

  public void remove() {
    if (!removedBCAccountIds.isEmpty()) {
      for (String bcAccountId : removedBCAccountIds) {
        availableBCAccountsMap.put(
          bcAccountId,
          selectedBCAccountsMap.get(bcAccountId)
        );
        selectedBCAccountsMap.remove(bcAccountId);
      }
    }
  }

  public void removeContracts() {
    if (!removedContractIds.isEmpty()) {
      for (String contractId : removedContractIds) {
        availableContractsMap.put(
          contractId,
          selectedContractsMap.get(contractId)
        );
        selectedContractsMap.remove(contractId);
      }
    }
  }

  public List<SelectOption> getAvailableBCAccounts() {
    List<SelectOption> availableBCAccounts = new List<SelectOption>();
    for (String bcAccountId : availableBCAccountsMap.keySet()) {
      availableBCAccounts.add(
        new SelectOption(bcAccountId, availableBCAccountsMap.get(bcAccountId))
      );
    }
    return availableBCAccounts;
  }

  public List<SelectOption> getAvailableContracts() {
    List<SelectOption> availableContracts = new List<SelectOption>();
    for (String contractId : availableContractsMap.keySet()) {
      String temp = availableContractsMap.get(contractId);
      if (!String.isEmpty(temp)) {
        availableContracts.add(new SelectOption(contractId, temp));
      }
    }
    return availableContracts;
  }

  public List<SelectOption> getSelectedBCAccounts() {
    List<SelectOption> selectedBCAccounts = new List<SelectOption>();
    for (String bcAccountId : selectedBCAccountsMap.keySet()) {
      selectedBCAccounts.add(
        new SelectOption(bcAccountId, selectedBCAccountsMap.get(bcAccountId))
      );
    }
    return selectedBCAccounts;
  }

  public List<SelectOption> getSelectedContracts() {
    List<SelectOption> selectedContracts = new List<SelectOption>();
    for (String contractId : selectedContractsMap.keySet()) {
      selectedContracts.add(
        new SelectOption(contractId, selectedContractsMap.get(contractId))
      );
    }
    return selectedContracts;
  }

  public class BaseException extends Exception {
  }
}