unpackaged/main/default/objects/Brightcove_Account__c/Brightcove_Account__c.object-meta.xml
<CustomObject>
    <label>Brightcove Account</label>
    <nameField>
        <label>Brightcove Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brightcove Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Account_Profile__c.field-meta.xml
<CustomField>
    <fullName>Account_Profile__c</fullName>
    <label>Account Profile</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
                <default>true</default>
                <label>Trial</label>
            </value>
            <value>
                <fullName>CUSTOMER</fullName>
            </value>
            <value>
                <fullName>Solution Partner</fullName>
            </value>
            <value>
                <fullName>Technology Partner</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Billing_Account_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account_Expiration_Date__c</fullName>
    <label>Billing Account Expiration Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/fields/GUID__c.field-meta.xml
<CustomField>
    <fullName>GUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>GUID</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Publisher_Status__c.field-meta.xml
<CustomField>
    <fullName>Publisher_Status__c</fullName>
    <description>Current status of the publisher&#39;s account.</description>
    <inlineHelpText>Current status of the publisher&#39;s account. Updated via sync from origin-services account.</inlineHelpText>
    <label>Publisher Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED</fullName>
            </value>
            <value>
                <fullName>UNREQUESTED</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
            </value>
            <value>
                <fullName>ENROLLED</fullName>
            </value>
            <value>
                <fullName>DENIED</fullName>
            </value>
            <value>
                <fullName>CLOSED</fullName>
            </value>
            <value>
                <fullName>LOCKED</fullName>
            </value>
            <value>
                <fullName>LOCKED_NON_PAYMENT</fullName>
            </value>
            <value>
                <fullName>LOCKED_TRIAL_EXPIRED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Tier</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Prime</fullName>
            </value>
            <value>
                <fullName>Basic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/BrightcoveAccountDataProcessorTest.cls
@isTest(isparallel=true)
public with sharing class BrightcoveAccountDataProcessorTest {
    @isTest
    static void testPut() {
        RestRequest request = new RestRequest();
        request.requestBody = Blob.valueOf(getRequestJson());
        RestContext.request = request;
        RestContext.response = new RestResponse();
        DataService.doPut();

        RestResponse response = RestContext.response;

        String responseBody = String.valueOf(response.responseBody);
        Integer responseCode = response.statusCode;

        System.assertNotEquals(null, responseBody, 'Response was null.');

        List<Brightcove_Account__c> brightAccounts = [
            SELECT Id, GUID__c
            FROM Brightcove_Account__c
            LIMIT 1
        ];
        System.assertEquals(
            1,
            brightAccounts.size(),
            'Incorrect number of records created.'
        );
    }

    @isTest
    static void testInvalidProcessor() {
        RestRequest request = new RestRequest();
        Map<String, Object> requestMap = new Map<String, Object>{
            'requestName' => 'Bad Request Name',
            'data' => getDataMap()
        };
        request.requestBody = Blob.valueOf(JSON.serialize(requestMap));
        RestContext.request = request;
        RestContext.response = new RestResponse();
        DataService.doPut();

        RestResponse response = RestContext.response;

        String responseBody = response.responseBody.toString();
        Integer responseCode = response.statusCode;

        System.assertNotEquals(null, responseBody, 'Response was null.');

        Map<String, Object> responseObjMap = (Map<String, Object>) JSON.deserializeUntyped(
            responseBody
        );

        System.assertEquals(
            false,
            (Boolean) responseObjMap.get('success'),
            'Invocation was successful'
        );

        System.assertEquals(
            'Invalid Request',
            (String) responseObjMap.get('message'),
            'Incorrect message returned.'
        );
    }

    @isTest
    static void testException() {
        RestRequest request = new RestRequest();
        Map<String, Object> requestMap = new Map<String, Object>{
            'requestName' => 'CreateBrightcoveAccounts',
            'data' => 'bad data'
        };
        request.requestBody = Blob.valueOf(JSON.serialize(requestMap));
        RestContext.request = request;
        RestContext.response = new RestResponse();

        Test.startTest();
        DataService.doPut();
        Test.stopTest();

        RestResponse response = RestContext.response;

        System.assertEquals(null, response.responseBody, 'Response was null.');
    }

    static String getRequestJson() {
        Map<String, Object> requestMap = new Map<String, Object>{
            'requestName' => 'CreateBrightcoveAccounts',
            'data' => getDataMap()
        };

        return JSON.serialize(requestMap);
    }

    static Object getDataMap() {
        Map<String, SObjectField> fields = Brightcove_Account__c.getSObjectType()
            .getDescribe(SObjectDescribeOptions.DEFERRED)
            .fields.getMap();

        return new List<Map<String, Object>>{
            new Map<String, Object>{
                'primaryAccountOwnerEmail' => 'BrightcoveAccountDataProcessorTest@example.com',
                'max_users' => 10,
                'account_profile' => fields.get('Account_Profile__c')
                        .getDescribe()
                        .getPicklistValues()[0]
                    .getValue(),
                'Publisher_Status__c' => fields.get('Publisher_Status__c')
                        .getDescribe()
                        .getPicklistValues()[0]
                    .getValue(),
                'tier' => fields.get('Tier__c')
                        .getDescribe()
                        .getPicklistValues()[0]
                    .getValue(),
                'bcAccountId' => 'BrightcoveAccountDataProcess',
                'Billing_Account_Expiration_Date__c' => '2023-05-05'
            }
        };
    }
}