unpackaged/main/default/objects/Brightcove_Account__c/Brightcove_Account__c.object-meta.xml
<CustomObject>
    <label>Brightcove Account</label>
    <nameField>
        <label>Brightcove Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brightcove Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Brightcove_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Brightcove_Account_Id__c</fullName>
    <description>The Pub ID of the Brightcove account&#39;s Id in our own database. Updated via sync from origin-services account.</description>
    <externalId>true</externalId>
    <inlineHelpText>The Pub ID of the Brightcove account&#39;s Id in our own database. Updated via sync from origin-services account.</inlineHelpText>
    <label>Brightcove Account Id</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Date_of_Last_Subscription_Change__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Last_Subscription_Change__c</fullName>
    <label>Date of Last Subscription Change</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Date_of_Subscription_Initial__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Subscription_Initial__c</fullName>
    <label>Date of Subscription (Initial)</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Date_of_Subscription_Latest__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Subscription_Latest__c</fullName>
    <label>Date of Subscription (Latest)</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Brightcove_Account__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Tier</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Prime</fullName>
            </value>
            <value>
                <fullName>Basic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/BCAccountSubscriptionDateManagerTest.cls
@isTest(isparallel=true)
public with sharing class BCAccountSubscriptionDateManagerTest {
    @isTest
    static void testSetSubscriptionDates() {
        Brightcove_Account__c bcAccount = new Brightcove_Account__c(
            Email_Address__c = 'mhigel@example.com',
            Tier__c = 'Premium',
            Brightcove_Account_Id__c = '123456'
        );
        insert bcAccount;

        bcAccount = [SELECT Id, Date_of_Subscription_Initial__c, Date_of_Subscription_Latest__c, Date_of_Last_Subscription_Change__c FROM Brightcove_Account__c WHERE Id = :bcAccount.Id];
        System.assertEquals(Date.today(), bcAccount.Date_of_Subscription_Initial__c);
        System.assertEquals(Date.today(), bcAccount.Date_of_Subscription_Latest__c);
        System.assertEquals(Date.today(), bcAccount.Date_of_Last_Subscription_Change__c);

        bcAccount.Date_of_Subscription_Latest__c = null;
        bcAccount.Date_of_Last_Subscription_Change__c = null;
        update bcAccount;

        bcAccount = [SELECT Id, Date_of_Subscription_Latest__c, Date_of_Last_Subscription_Change__c FROM Brightcove_Account__c WHERE Id = :bcAccount.Id];
        System.assertEquals(null, bcAccount.Date_of_Subscription_Latest__c);
        System.assertEquals(null, bcAccount.Date_of_Last_Subscription_Change__c);

        bcAccount.Tier__c = 'Basic';
        update bcAccount;

        bcAccount = [SELECT Id, Date_of_Subscription_Latest__c, Date_of_Last_Subscription_Change__c FROM Brightcove_Account__c WHERE Id = :bcAccount.Id];
        System.assertEquals(Date.today(), bcAccount.Date_of_Subscription_Latest__c);
        System.assertEquals(Date.today(), bcAccount.Date_of_Last_Subscription_Change__c);
    }
}