unpackaged/main/default/objects/Opportunity/fields/ACV__c.field-meta.xml
<CustomField>
    <fullName>ACV__c</fullName>
    <formula>IF(Has_Primary_Quote__c, IF(SBQQ__PrimaryQuote__r.ACV__c &lt;= 0, IF(NOT(ISBLANK(Manual_ACV__c)) &amp;&amp; Manual_ACV__c &gt; 0, Manual_ACV__c, Total_ACV_Admin__c), SBQQ__PrimaryQuote__r.ACV__c), If(and(OR(ISPICKVAL(StageName, &quot;closed won&quot;),ISPICKVAL(StageName, &quot;closed lost&quot;)),CloseDate &lt; DATE(2023,04,15)) ,Total_ACV_Admin__c,
IF(NOT(ISBLANK(Manual_ACV__c)) &amp;&amp; Manual_ACV__c &gt; 1, Manual_ACV__c, Total_ACV_Admin__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ACV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/ACVH__c.field-meta.xml
<CustomField>
    <fullName>ACVH__c</fullName>
    <description>ACV for field Tracking history-Mo</description>
    <label>ACV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Existing_MRR__c.field-meta.xml
<CustomField>
    <fullName>Existing_MRR__c</fullName>
    <label>Existing MRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/MRR_Commit__c.field-meta.xml
<CustomField>
    <fullName>MRR_Commit__c</fullName>
    <label>MRR Commit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/TCV__c.field-meta.xml
<CustomField>
    <fullName>TCV__c</fullName>
    <formula>If( and (OR(ISPICKVAL(StageName, &quot;closed won&quot;),ISPICKVAL(StageName, &quot;closed lost&quot;)),CloseDate &lt; DATE(2023,04,15)) ,Legacy_TCV__c,
IF(NOT(ISBLANK(SBQQ__PrimaryQuote__r.SBQQ__NetAmount__c))&amp;&amp;SBQQ__PrimaryQuote__r.SBQQ__NetAmount__c &gt;1, SBQQ__PrimaryQuote__r.SBQQ__NetAmount__c,  

IF(NOT(ISBLANK(Manual_TCV__c))&amp;&amp; Manual_TCV__c &gt; 1, Manual_TCV__c, Legacy_TCV__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TCV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/TCVH__c.field-meta.xml
<CustomField>
    <fullName>TCVH__c</fullName>
    <description>field Tracking for TCV-Mo</description>
    <label>TCV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/USD_Existing_MRR__c.field-meta.xml
<CustomField>
    <fullName>USD_Existing_MRR__c</fullName>
    <label>USD Existing MRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/USD_MRR_Commit__c.field-meta.xml
<CustomField>
    <fullName>USD_MRR_Commit__c</fullName>
    <label>USD MRR Commit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/USD_Total_ACV__c.field-meta.xml
<CustomField>
    <fullName>USD_Total_ACV__c</fullName>
    <label>USD Total ACV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/OpportunityRevenueFieldHandler.cls
public with sharing class OpportunityRevenueFieldHandler extends DomainLogicHandler {
    private static CurrencyUtility cuInstance;
    List<Opportunity> workSet = new List<Opportunity>();

    public override void check(SObject newObj) {
        newObj.put('ACVH__c', newObj.get('ACV__c'));
        newObj.put('TCVH__c', newObj.get('TCV__c'));
        workSet.add((Opportunity)newObj);
    }
    
    public override void check(SObject newObj, SObject oldObj) {
        newObj.put('ACVH__c', newObj.get('ACV__c'));
        newObj.put('TCVH__c', newObj.get('TCV__c'));
        workSet.add((Opportunity)newObj);
    }

    public override void processRecords() {
        Set<Date> closeDates = new Set<Date>();
        for(Opportunity opp : workSet) {
            closeDates.add(opp.CloseDate);
        }

        cuInstance = CurrencyUtility.getInstance(closeDates);

        for(Opportunity opp : workSet) {
            opp.USD_Existing_MRR__c = cuInstance.convertPriceToUSD(opp.Existing_MRR__c, opp.CurrencyIsoCode, opp.CloseDate);
            opp.USD_MRR_Commit__c = cuInstance.convertPriceToUSD(opp.MRR_Commit__c, opp.CurrencyIsoCode, opp.CloseDate);
            opp.USD_Total_ACV__c = cuInstance.convertPriceToUSD(opp.ACV__c, opp.CurrencyIsoCode, opp.CloseDate);
        }
    }
}