unpackaged/main/default/objects/Opportunity/fields/ACV__c.field-meta.xml
<CustomField>
    <fullName>ACV__c</fullName>
    <formula>IF(Has_Primary_Quote__c, IF(SBQQ__PrimaryQuote__r.ACV__c &lt;= 0, IF(NOT(ISBLANK(Manual_ACV__c)) &amp;&amp; Manual_ACV__c &gt; 0, Manual_ACV__c, Total_ACV_Admin__c), SBQQ__PrimaryQuote__r.ACV__c), If(and(OR(ISPICKVAL(StageName, &quot;closed won&quot;),ISPICKVAL(StageName, &quot;closed lost&quot;)),CloseDate &lt; DATE(2023,04,15)) ,Total_ACV_Admin__c,
IF(NOT(ISBLANK(Manual_ACV__c)) &amp;&amp; Manual_ACV__c &gt; 1, Manual_ACV__c, Total_ACV_Admin__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ACV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Existing_MRR__c.field-meta.xml
<CustomField>
    <fullName>Existing_MRR__c</fullName>
    <label>Existing MRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/MRR_Commit__c.field-meta.xml
<CustomField>
    <fullName>MRR_Commit__c</fullName>
    <label>MRR Commit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/New_MRR__c.field-meta.xml
<CustomField>
    <fullName>New_MRR__c</fullName>
    <label>New MRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Renewal_Growth_Amount__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Growth_Amount__c</fullName>
    <label>Renewal Growth Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/OpportunityRenewalGrowthHandler.cls
public with sharing class OpportunityRenewalGrowthHandler extends DomainLogicHandler {
    List<Opportunity> workSet = new List<Opportunity>();
    Map<Id,Opportunity> oldOpps = new Map<Id,Opportunity>();

    public override void check(SObject newObj, SObject oldObj) {
        if (isQualified((Opportunity) newObj, (Opportunity) oldObj)) {
            workSet.add((Opportunity) newObj);
            oldOpps.put(oldObj.Id, (Opportunity)oldObj);
        }
    }

    public override void processRecords() {
        Set<Id> quoteIds = new Set<Id>();

        for (Opportunity opp : workSet) {
            if (opp.SBQQ__PrimaryQuote__c != null) {
                quoteIds.add(opp.SBQQ__PrimaryQuote__c);
            }
        }

        Map<Id, SBQQ__Quote__c> quoteInfo = new Map<Id, SBQQ__Quote__c>([
            SELECT Id, SBQQ__SubscriptionTerm__c
            FROM SBQQ__Quote__c
            WHERE Id IN :quoteIds
        ]);

        for (Opportunity opp : workSet) {
            processOpportunity(opp, quoteInfo);
        }
    }

    private void processOpportunity(Opportunity opp, Map<Id, SBQQ__Quote__c> quoteInfo) {
        Integer subscriptionTerm = 12;
        
        if (opp.SBQQ__PrimaryQuote__c != null) {
            subscriptionTerm = quoteInfo.get(opp?.SBQQ__PrimaryQuote__c)
                    .SBQQ__SubscriptionTerm__c < 12
                ? (Integer)quoteInfo.get(opp?.SBQQ__PrimaryQuote__c)
                        .SBQQ__SubscriptionTerm__c
                : 12;
        }

        Decimal newMRR = opp.ACV__c / subscriptionTerm;
        Decimal renewalGrowth =
            newMRR - opp.Existing_MRR__c;

        opp.New_MRR__c = newMRR;
        if(renewalGrowth < 0.0) {
            renewalGrowth = 0.0;
        }
        opp.Renewal_Growth_Amount__c = renewalGrowth * subscriptionTerm;

        if(opp.StageName == 'Closed Won' && opp.StageName != oldOpps.get(opp.Id).StageName) {
            if(opp.New_MRR__c > opp.Existing_MRR__c) {
                opp.MRR_Commit__c = opp.Existing_MRR__c;
            } else {
                opp.MRR_Commit__c = newMRR;
            }
        }
    }

    private Boolean isQualified(Opportunity newOpp, Opportunity oldOpp) {
        if (
            (newOpp.ACV__c != oldOpp.ACV__c ||
            newOpp.SBQQ__PrimaryQuote__c != oldOpp.SBQQ__PrimaryQuote__c ||
            newOpp.Existing_MRR__c != oldOpp.Existing_MRR__c ||
            newOpp.StageName != oldOpp.StageName) &&
            newOpp.Existing_MRR__c != null &&
            newOpp.ACV__c != null &&
            newOpp.StageName != null
        ) {
            return true;
        }
        return false;
    }
}