unpackaged/main/default/objects/Opportunity/fields/Existing_MRR__c.field-meta.xml
<CustomField>
    <fullName>Existing_MRR__c</fullName>
    <label>Existing MRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Manual_ACV__c.field-meta.xml
<CustomField>
    <fullName>Manual_ACV__c</fullName>
    <label>Manual ACV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/MRR_Commit__c.field-meta.xml
<CustomField>
    <fullName>MRR_Commit__c</fullName>
    <label>MRR Commit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/New_MRR__c.field-meta.xml
<CustomField>
    <fullName>New_MRR__c</fullName>
    <label>New MRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Renewal_Growth_Amount__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Growth_Amount__c</fullName>
    <label>Renewal Growth Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <businessProcess>Standard Sales Process</businessProcess>
    <description>System generated Opportunity used for renewing a Contract at the end of its term</description>
    <label>Renewal</label>
</RecordType>

unpackaged/main/default/classes/OpportunityRenewalGrowthHandlerTest.cls
@IsTest
public with sharing class OpportunityRenewalGrowthHandlerTest {
  @IsTest
  public static void opportunityRenewalGrowthTestNotClosed() {
    Account account = AccountTestFactory.createCustomer();

    Opportunity opp = OpportunityTestFactory.getStage1Opp(account.Id);
    insert opp;

    //lol
    Test.startTest();
    opp.Manual_ACV__c = 12000.00;
    opp.Existing_MRR__c = 800.0;
    opp.MRR_Commit__c = 600.0;
    update opp;
    Test.stopTest();

    opp = [
      SELECT Id, New_MRR__c, Renewal_Growth_Amount__c, MRR_Commit__c
      FROM Opportunity
      WHERE Id = :opp.Id
    ];

    System.assertEquals(1000.00, opp.New_MRR__c, 'New MRR is not correct');
    System.assertEquals(
      2400.00,
      opp.Renewal_Growth_Amount__c,
      'Renewal Growth Amount is not correct'
    );

    System.assertEquals(600.00, opp.MRR_Commit__c, 'MRR Commit is not correct');
  }

  @IsTest
  public static void opportunityRenewalGrowthTestClosedWon() {
    Account account = AccountTestFactory.createCustomer();

    Opportunity opp = OpportunityTestFactory.getStage1Opp(account.Id);
    insert opp;

    OpportunityTestFactory.setStage2(opp);
    update opp;

    OpportunityTestFactory.setStage3(opp);
    update opp;

    OpportunityTestFactory.setStage4(opp);
    update opp;

    SBQQ.TriggerControl.disable();
    Test.startTest();

    opp.Manual_ACV__c = 10000.00;
    opp.Existing_MRR__c = 1000.0;
    opp.MRR_Commit__c = 600.0;
    OpportunityTestFactory.closeWin(opp);
    update opp;

    Test.stopTest();
    SBQQ.TriggerControl.enable();

    opp = [
      SELECT Id, New_MRR__c, Renewal_Growth_Amount__c, MRR_Commit__c
      FROM Opportunity
      WHERE Id = :opp.Id
    ];

    System.assertEquals(10000.0 / 12, opp.New_MRR__c, 'New MRR is not correct');
    System.assertEquals(
      0.00,
      opp.Renewal_Growth_Amount__c,
      'Renewal Growth Amount is not correct'
    );

    System.assertEquals(
      10000.0 / 12,
      opp.MRR_Commit__c,
      'MRR Commit is not correct'
    );
  }
}