unpackaged/main/default/objects/Opportunity/fields/Owner_Division__c.field-meta.xml
<CustomField>
    <fullName>Owner_Division__c</fullName>
    <label>Owner Division</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Owner_Sub_Division__c.field-meta.xml
<CustomField>
    <fullName>Owner_Sub_Division__c</fullName>
    <label>Owner Sub Division</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Sub_Division__c.field-meta.xml
<CustomField>
    <fullName>Sub_Division__c</fullName>
    <label>Sub Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
                <isActive>false</isActive>
                <label>APAC</label>
            </value>
            <value>
                <fullName>Americas</fullName>
                <isActive>false</isActive>
                <label>Americas</label>
            </value>
            <value>
                <fullName>Commercial</fullName>
                <isActive>false</isActive>
                <label>Commercial</label>
            </value>
            <value>
                <fullName>Expand</fullName>
                <isActive>false</isActive>
                <label>Expand</label>
            </value>
            <value>
                <fullName>LATAM</fullName>
                <isActive>false</isActive>
                <label>LATAM</label>
            </value>
            <value>
                <fullName>Land</fullName>
                <isActive>false</isActive>
                <label>Land</label>
            </value>
            <value>
                <fullName>Mid Market</fullName>
                <isActive>false</isActive>
                <label>Mid Market</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/OppOwnerDivisionStamper.cls
public with sharing class OppOwnerDivisionStamper extends DomainLogicHandler {
    List<Opportunity> qualifiedOpps = new List<Opportunity>();

    public override void check(SObject newObj) {
        if (isQualified(newObj)) {
            qualifiedOpps.add((Opportunity) newObj);
        }
    }

    public override void check(SObject newObj, SObject oldObj) {
        if (isQualified(newObj, oldObj)) {
            qualifiedOpps.add((Opportunity) newObj);
        }
    }

    public override void processRecords() {
        if (!qualifiedOpps.isEmpty()) {
            /**
             * note that the Opp Owner can change via
             * OpportunityOwnerHandler, meaning that OwnerIds
             * collected in this class' check method could
             * differ from those found on Opps in this processRecords
             * method.
             */
            List<Id> userIds = new List<Id>();
            for (Opportunity opp : qualifiedOpps) {
                userIds.add(opp.OwnerId);
            }

            Map<Id, User> users = new Map<Id, User>(
                [
                    SELECT Id, Division, Sub_Division__c
                    FROM User
                    WHERE Id IN :userIds
                ]
            );
            for (Opportunity opp : qualifiedOpps) {
                opp.Owner_Division__c = users.get(opp.OwnerId).Division;
                opp.Owner_Sub_Division__c = users.get(opp.OwnerId)
                    .Sub_Division__c;
            }
        }
    }

    Boolean isQualified(Sobject newObj) {
        return !(Boolean) newObj.get(Opportunity.IsClosed);
    }

    Boolean isQualified(SObject newObj, SObject oldObj) {
        return TriggerUtility.isChanged(newObj, oldObj, Opportunity.OwnerId) &&
            isQualified(newObj);
    }
}